{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/streamlit%20run%20app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "```python\n",
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "app.py\n",
        "\n",
        "Streamlit web dashboard for the complete automation system.\n",
        "\n",
        "Features:\n",
        "    - Dashboard\n",
        "    - AI / Robotics News\n",
        "    - STEM Tips\n",
        "    - Project Ideas\n",
        "    - Class Updates\n",
        "    - Weekly Reports\n",
        "    - Competition / GitHub monitoring\n",
        "    - Gmail testing\n",
        "    - Manual agent execution\n",
        "    - Automation schedule\n",
        "    - Service health checks\n",
        "\n",
        "Run:\n",
        "    streamlit run app.py\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import os\n",
        "import sys\n",
        "import traceback\n",
        "from datetime import datetime\n",
        "from pathlib import Path\n",
        "\n",
        "import streamlit as st\n",
        "from dotenv import load_dotenv\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# PROJECT PATH\n",
        "# ============================================================\n",
        "\n",
        "BASE_DIR = Path(__file__).resolve().parent\n",
        "\n",
        "if str(BASE_DIR) not in sys.path:\n",
        "    sys.path.insert(\n",
        "        0,\n",
        "        str(BASE_DIR),\n",
        "    )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# ENVIRONMENT\n",
        "# ============================================================\n",
        "\n",
        "load_dotenv(\n",
        "    BASE_DIR / \".env\"\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# PAGE CONFIGURATION\n",
        "# ============================================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"AI STEM Automation Hub\",\n",
        "    page_icon=\"🤖\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\",\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# CUSTOM CSS\n",
        "# ============================================================\n",
        "\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    <style>\n",
        "\n",
        "    .main-title {\n",
        "        font-size: 2.4rem;\n",
        "        font-weight: 700;\n",
        "        margin-bottom: 0.2rem;\n",
        "    }\n",
        "\n",
        "    .subtitle {\n",
        "        color: #777;\n",
        "        font-size: 1.05rem;\n",
        "        margin-bottom: 1.5rem;\n",
        "    }\n",
        "\n",
        "    .status-card {\n",
        "        padding: 1rem;\n",
        "        border-radius: 12px;\n",
        "        border: 1px solid #ddd;\n",
        "        background: rgba(128,128,128,0.05);\n",
        "        min-height: 120px;\n",
        "    }\n",
        "\n",
        "    .status-title {\n",
        "        font-size: 0.9rem;\n",
        "        font-weight: 600;\n",
        "    }\n",
        "\n",
        "    .status-value {\n",
        "        font-size: 1.5rem;\n",
        "        font-weight: 700;\n",
        "        margin-top: 0.4rem;\n",
        "    }\n",
        "\n",
        "    .section-title {\n",
        "        font-size: 1.5rem;\n",
        "        font-weight: 700;\n",
        "        margin-top: 1rem;\n",
        "        margin-bottom: 1rem;\n",
        "    }\n",
        "\n",
        "    .agent-card {\n",
        "        padding: 1rem;\n",
        "        border-radius: 12px;\n",
        "        border: 1px solid #ddd;\n",
        "        margin-bottom: 1rem;\n",
        "    }\n",
        "\n",
        "    </style>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True,\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# HELPERS\n",
        "# ============================================================\n",
        "\n",
        "def safe_import_agents():\n",
        "    \"\"\"\n",
        "    Import all six agents.\n",
        "\n",
        "    Returns:\n",
        "        dict[str, callable]\n",
        "    \"\"\"\n",
        "\n",
        "    agents = {}\n",
        "\n",
        "    imports = [\n",
        "        (\n",
        "            \"news\",\n",
        "            \"agents.news_agent\",\n",
        "            \"run_daily_news\",\n",
        "        ),\n",
        "        (\n",
        "            \"class\",\n",
        "            \"agents.class_agent\",\n",
        "            \"run_class_update\",\n",
        "        ),\n",
        "        (\n",
        "            \"stem_tip\",\n",
        "            \"agents.stem_tip_agent\",\n",
        "            \"run_stem_tip\",\n",
        "        ),\n",
        "        (\n",
        "            \"project\",\n",
        "            \"agents.project_agent\",\n",
        "            \"run_project_idea\",\n",
        "        ),\n",
        "        (\n",
        "            \"weekly\",\n",
        "            \"agents.weekly_report_agent\",\n",
        "            \"run_weekly_report\",\n",
        "        ),\n",
        "        (\n",
        "            \"competition\",\n",
        "            \"agents.competition_agent\",\n",
        "            \"run_competition_update\",\n",
        "        ),\n",
        "    ]\n",
        "\n",
        "    for key, module_name, function_name in imports:\n",
        "\n",
        "        try:\n",
        "\n",
        "            module = __import__(\n",
        "                module_name,\n",
        "                fromlist=[\n",
        "                    function_name\n",
        "                ],\n",
        "            )\n",
        "\n",
        "            function = getattr(\n",
        "                module,\n",
        "                function_name,\n",
        "            )\n",
        "\n",
        "            agents[key] = function\n",
        "\n",
        "        except Exception as exc:\n",
        "\n",
        "            agents[key] = {\n",
        "                \"error\": str(exc)\n",
        "            }\n",
        "\n",
        "    return agents\n",
        "\n",
        "\n",
        "def run_agent(\n",
        "    agent_name,\n",
        "    agents,\n",
        "):\n",
        "    \"\"\"\n",
        "    Execute an agent safely.\n",
        "    \"\"\"\n",
        "\n",
        "    agent = agents.get(\n",
        "        agent_name\n",
        "    )\n",
        "\n",
        "    if agent is None:\n",
        "\n",
        "        st.error(\n",
        "            f\"Agent '{agent_name}' is not available.\"\n",
        "        )\n",
        "\n",
        "        return None\n",
        "\n",
        "    if isinstance(\n",
        "        agent,\n",
        "        dict,\n",
        "    ):\n",
        "\n",
        "        st.error(\n",
        "            f\"Could not load {agent_name} agent:\"\n",
        "        )\n",
        "\n",
        "        st.code(\n",
        "            agent.get(\n",
        "                \"error\",\n",
        "                \"Unknown error\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "        return None\n",
        "\n",
        "    try:\n",
        "\n",
        "        with st.spinner(\n",
        "            f\"Running {agent_name.replace('_', ' ').title()}...\"\n",
        "        ):\n",
        "\n",
        "            result = agent()\n",
        "\n",
        "        st.success(\n",
        "            f\"{agent_name.replace('_', ' ').title()} completed.\"\n",
        "        )\n",
        "\n",
        "        if result is not None:\n",
        "\n",
        "            return result\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        st.error(\n",
        "            f\"{agent_name.replace('_', ' ').title()} failed.\"\n",
        "        )\n",
        "\n",
        "        with st.expander(\n",
        "            \"Technical error\"\n",
        "        ):\n",
        "\n",
        "            st.code(\n",
        "                traceback.format_exc()\n",
        "            )\n",
        "\n",
        "        return None\n",
        "\n",
        "\n",
        "def service_status():\n",
        "    \"\"\"\n",
        "    Check availability of major services.\n",
        "    \"\"\"\n",
        "\n",
        "    status = {}\n",
        "\n",
        "    # Gemini\n",
        "    status[\"Gemini\"] = bool(\n",
        "        os.getenv(\n",
        "            \"GEMINI_API_KEY\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    # Gmail\n",
        "    status[\"Gmail\"] = bool(\n",
        "        os.getenv(\n",
        "            \"GMAIL_ADDRESS\"\n",
        "        )\n",
        "        and os.getenv(\n",
        "            \"GMAIL_APP_PASSWORD\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    # GitHub\n",
        "    status[\"GitHub\"] = bool(\n",
        "        os.getenv(\n",
        "            \"GITHUB_REPOSITORY\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    # Web search\n",
        "    status[\"Web Search\"] = True\n",
        "\n",
        "    # Database\n",
        "    status[\"Database\"] = True\n",
        "\n",
        "    # Scheduler\n",
        "    status[\"Scheduler\"] = True\n",
        "\n",
        "    return status\n",
        "\n",
        "\n",
        "def status_badge(value):\n",
        "    if value:\n",
        "        return \"🟢 Connected\"\n",
        "\n",
        "    return \"🔴 Not configured\"\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# LOAD AGENTS\n",
        "# ============================================================\n",
        "\n",
        "agents = safe_import_agents()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# SIDEBAR\n",
        "# ============================================================\n",
        "\n",
        "with st.sidebar:\n",
        "\n",
        "    st.markdown(\n",
        "        \"# 🤖 AI STEM Hub\"\n",
        "    )\n",
        "\n",
        "    st.caption(\n",
        "        \"AI-powered STEM automation platform\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    page = st.radio(\n",
        "        \"Navigation\",\n",
        "        [\n",
        "            \"🏠 Dashboard\",\n",
        "            \"📰 AI & Robotics News\",\n",
        "            \"💡 STEM Tip\",\n",
        "            \"🔧 Project Ideas\",\n",
        "            \"🏫 Class Updates\",\n",
        "            \"🏆 Competition\",\n",
        "            \"📊 Weekly Report\",\n",
        "            \"📧 Gmail\",\n",
        "            \"⚙️ Automation\",\n",
        "            \"🔍 System Health\",\n",
        "        ],\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.caption(\n",
        "        f\"Today: \"\n",
        "        f\"{datetime.now().strftime('%d %b %Y')}\"\n",
        "    )\n",
        "\n",
        "    st.caption(\n",
        "        f\"Time: \"\n",
        "        f\"{datetime.now().strftime('%I:%M:%S %p')}\"\n",
        "    )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# DASHBOARD\n",
        "# ============================================================\n",
        "\n",
        "if page == \"🏠 Dashboard\":\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"main-title\">'\n",
        "        '🤖 AI STEM Automation Hub'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True,\n",
        "    )\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"subtitle\">'\n",
        "        'Central control panel for AI, Robotics, STEM '\n",
        "        'and project automation'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True,\n",
        "    )\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # STATUS CARDS\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    status = service_status()\n",
        "\n",
        "    columns = st.columns(6)\n",
        "\n",
        "    for column, (name, value) in zip(\n",
        "        columns,\n",
        "        status.items(),\n",
        "    ):\n",
        "\n",
        "        with column:\n",
        "\n",
        "            st.metric(\n",
        "                name,\n",
        "                \"ONLINE\"\n",
        "                if value\n",
        "                else \"OFFLINE\",\n",
        "            )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # QUICK ACTIONS\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"section-title\">'\n",
        "        '⚡ Quick Actions'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True,\n",
        "    )\n",
        "\n",
        "    c1, c2, c3 = st.columns(3)\n",
        "\n",
        "    with c1:\n",
        "\n",
        "        if st.button(\n",
        "            \"📰 Run News Agent\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"news\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "        if st.button(\n",
        "            \"💡 Generate STEM Tip\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"stem_tip\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "    with c2:\n",
        "\n",
        "        if st.button(\n",
        "            \"🔧 Generate Project\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"project\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "        if st.button(\n",
        "            \"🏫 Generate Class Update\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"class\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "    with c3:\n",
        "\n",
        "        if st.button(\n",
        "            \"🏆 Check Competition\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"competition\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "        if st.button(\n",
        "            \"📊 Generate Weekly Report\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"weekly\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # AGENT STATUS\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    st.markdown(\n",
        "        \"### 🤖 Agent Status\"\n",
        "    )\n",
        "\n",
        "    agent_labels = {\n",
        "        \"news\": \"📰 News Agent\",\n",
        "        \"stem_tip\": \"💡 STEM Tip Agent\",\n",
        "        \"project\": \"🔧 Project Agent\",\n",
        "        \"class\": \"🏫 Class Agent\",\n",
        "        \"competition\": \"🏆 Competition Agent\",\n",
        "        \"weekly\": \"📊 Weekly Report Agent\",\n",
        "    }\n",
        "\n",
        "    cols = st.columns(3)\n",
        "\n",
        "    for index, (\n",
        "        key,\n",
        "        label,\n",
        "    ) in enumerate(\n",
        "        agent_labels.items()\n",
        "    ):\n",
        "\n",
        "        with cols[\n",
        "            index % 3\n",
        "        ]:\n",
        "\n",
        "            available = (\n",
        "                key in agents\n",
        "                and not isinstance(\n",
        "                    agents[key],\n",
        "                    dict,\n",
        "                )\n",
        "            )\n",
        "\n",
        "            st.write(\n",
        "                f\"{label}: \"\n",
        "                f\"{'🟢 Ready' if available else '🔴 Error'}\"\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# NEWS\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"📰 AI & Robotics News\":\n",
        "\n",
        "    st.title(\n",
        "        \"📰 AI & Robotics News\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Collect current AI, robotics, electronics and IoT news, \"\n",
        "        \"summarize it with Gemini and send it through Gmail.\"\n",
        "    )\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        if st.button(\n",
        "            \"🔎 Collect & Send News\",\n",
        "            type=\"primary\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            result = run_agent(\n",
        "                \"news\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "            if result:\n",
        "\n",
        "                st.info(\n",
        "                    \"The news agent completed its configured workflow.\"\n",
        "                )\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        if st.button(\n",
        "            \"🔄 Refresh\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.web_search import (\n",
        "            search_news,\n",
        "            compact_articles,\n",
        "        )\n",
        "\n",
        "        hours = st.slider(\n",
        "            \"Search period (hours)\",\n",
        "            min_value=6,\n",
        "            max_value=168,\n",
        "            value=48,\n",
        "        )\n",
        "\n",
        "        limit = st.slider(\n",
        "            \"Number of articles\",\n",
        "            min_value=5,\n",
        "            max_value=30,\n",
        "            value=10,\n",
        "        )\n",
        "\n",
        "        if st.button(\n",
        "            \"🔍 Preview Latest News\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            with st.spinner(\n",
        "                \"Collecting news...\"\n",
        "            ):\n",
        "\n",
        "                articles = search_news(\n",
        "                    categories=[\n",
        "                        \"AI\",\n",
        "                        \"Robotics\",\n",
        "                        \"Electronics\",\n",
        "                        \"IoT\",\n",
        "                    ],\n",
        "                    hours=hours,\n",
        "                    limit=limit,\n",
        "                )\n",
        "\n",
        "                articles = compact_articles(\n",
        "                    articles\n",
        "                )\n",
        "\n",
        "            if not articles:\n",
        "\n",
        "                st.warning(\n",
        "                    \"No recent articles found.\"\n",
        "                )\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.success(\n",
        "                    f\"Found {len(articles)} articles.\"\n",
        "                )\n",
        "\n",
        "                for article in articles:\n",
        "\n",
        "                    with st.expander(\n",
        "                        article.get(\n",
        "                            \"title\",\n",
        "                            \"Untitled\",\n",
        "                        )\n",
        "                    ):\n",
        "\n",
        "                        st.write(\n",
        "                            article.get(\n",
        "                                \"description\",\n",
        "                                \"\",\n",
        "                            )\n",
        "                        )\n",
        "\n",
        "                        st.caption(\n",
        "                            f\"{article.get('source', '')} \"\n",
        "                            f\"| \"\n",
        "                            f\"{article.get('category', '')}\"\n",
        "                        )\n",
        "\n",
        "                        st.link_button(\n",
        "                            \"Read Article\",\n",
        "                            article.get(\n",
        "                                \"url\",\n",
        "                                \"#\",\n",
        "                            ),\n",
        "                        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        st.warning(\n",
        "            f\"News preview unavailable: {exc}\"\n",
        "        )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# STEM TIP\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"💡 STEM Tip\":\n",
        "\n",
        "    st.title(\n",
        "        \"💡 Daily STEM Tip\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Generate a robotics/electronics experiment \"\n",
        "        \"for students.\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 Generate Today's STEM Tip\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        result = run_agent(\n",
        "            \"stem_tip\",\n",
        "            agents,\n",
        "        )\n",
        "\n",
        "        if isinstance(\n",
        "            result,\n",
        "            str,\n",
        "        ):\n",
        "\n",
        "            st.markdown(\n",
        "                \"### Today's Tip\"\n",
        "            )\n",
        "\n",
        "            st.markdown(\n",
        "                result\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# PROJECT IDEAS\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"🔧 Project Ideas\":\n",
        "\n",
        "    st.title(\n",
        "        \"🔧 Project Idea Agent\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Generate Arduino, ESP32, IoT and robotics \"\n",
        "        \"project ideas.\"\n",
        "    )\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        platform = st.selectbox(\n",
        "            \"Platform\",\n",
        "            [\n",
        "                \"Arduino\",\n",
        "                \"ESP32\",\n",
        "                \"ESP8266\",\n",
        "                \"Raspberry Pi\",\n",
        "                \"Robotics\",\n",
        "                \"IoT\",\n",
        "                \"AI + Robotics\",\n",
        "            ],\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        level = st.selectbox(\n",
        "            \"Difficulty\",\n",
        "            [\n",
        "                \"Beginner\",\n",
        "                \"Intermediate\",\n",
        "                \"Advanced\",\n",
        "            ],\n",
        "        )\n",
        "\n",
        "    st.caption(\n",
        "        f\"Selected: {platform} / {level}\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"🤖 Generate Project Idea\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        result = run_agent(\n",
        "            \"project\",\n",
        "            agents,\n",
        "        )\n",
        "\n",
        "        if isinstance(\n",
        "            result,\n",
        "            str,\n",
        "        ):\n",
        "\n",
        "            st.markdown(\n",
        "                result\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# CLASS UPDATES\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"🏫 Class Updates\":\n",
        "\n",
        "    st.title(\n",
        "        \"🏫 STEM Class Update Agent\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Generate a concise grade-wise class/session update.\"\n",
        "    )\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        grade = st.text_input(\n",
        "            \"Grade\",\n",
        "            placeholder=\"Example: Grade 5A\",\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        topic = st.text_input(\n",
        "            \"Topic\",\n",
        "            placeholder=\"Example: Transistor as a switch\",\n",
        "        )\n",
        "\n",
        "    session_data = st.text_area(\n",
        "        \"Session details\",\n",
        "        placeholder=(\n",
        "            \"Enter what students learned, activities, \"\n",
        "            \"experiments, observations and outcomes...\"\n",
        "        ),\n",
        "        height=180,\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"📝 Generate Class Update\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        # Store temporary input so the existing\n",
        "        # class agent can be adapted later.\n",
        "        st.session_state[\n",
        "            \"class_grade\"\n",
        "        ] = grade\n",
        "\n",
        "        st.session_state[\n",
        "            \"class_topic\"\n",
        "        ] = topic\n",
        "\n",
        "        st.session_state[\n",
        "            \"class_data\"\n",
        "        ] = session_data\n",
        "\n",
        "        result = run_agent(\n",
        "            \"class\",\n",
        "            agents,\n",
        "        )\n",
        "\n",
        "        if isinstance(\n",
        "            result,\n",
        "            str,\n",
        "        ):\n",
        "\n",
        "            st.markdown(\n",
        "                \"### Generated Update\"\n",
        "            )\n",
        "\n",
        "            st.markdown(\n",
        "                result\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# COMPETITION\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"🏆 Competition\":\n",
        "\n",
        "    st.title(\n",
        "        \"🏆 Competition & GitHub Monitor\"\n",
        "    )\n",
        "\n",
        "    repository = os.getenv(\n",
        "        \"GITHUB_REPOSITORY\",\n",
        "        \"Not configured\",\n",
        "    )\n",
        "\n",
        "    st.info(\n",
        "        f\"Repository: `{repository}`\"\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.github import (\n",
        "            get_project_status,\n",
        "        )\n",
        "\n",
        "        if st.button(\n",
        "            \"🔍 Check GitHub\",\n",
        "            type=\"primary\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            with st.spinner(\n",
        "                \"Checking GitHub...\"\n",
        "            ):\n",
        "\n",
        "                status = get_project_status(\n",
        "                    repository\n",
        "                )\n",
        "\n",
        "            st.success(\n",
        "                \"GitHub status retrieved.\"\n",
        "            )\n",
        "\n",
        "            c1, c2, c3, c4 = st.columns(4)\n",
        "\n",
        "            with c1:\n",
        "\n",
        "                st.metric(\n",
        "                    \"Open Issues\",\n",
        "                    status.get(\n",
        "                        \"open_issues\",\n",
        "                        0,\n",
        "                    ),\n",
        "                )\n",
        "\n",
        "            with c2:\n",
        "\n",
        "                st.metric(\n",
        "                    \"Successful Workflows\",\n",
        "                    status.get(\n",
        "                        \"successful_workflows\",\n",
        "                        0,\n",
        "                    ),\n",
        "                )\n",
        "\n",
        "            with c3:\n",
        "\n",
        "                st.metric(\n",
        "                    \"Failed Workflows\",\n",
        "                    status.get(\n",
        "                        \"failed_workflows\",\n",
        "                        0,\n",
        "                    ),\n",
        "                )\n",
        "\n",
        "            with c4:\n",
        "\n",
        "                commit = status.get(\n",
        "                    \"latest_commit\",\n",
        "                    {},\n",
        "                )\n",
        "\n",
        "                st.metric(\n",
        "                    \"Latest Commit\",\n",
        "                    commit.get(\n",
        "                        \"short_sha\",\n",
        "                        \"-\",\n",
        "                    ),\n",
        "                )\n",
        "\n",
        "            st.markdown(\n",
        "                \"### Latest Commit\"\n",
        "            )\n",
        "\n",
        "            st.write(\n",
        "                commit.get(\n",
        "                    \"message\",\n",
        "                    \"No commit information.\",\n",
        "                )\n",
        "            )\n",
        "\n",
        "            st.caption(\n",
        "                commit.get(\n",
        "                    \"date\",\n",
        "                    \"\",\n",
        "                )\n",
        "            )\n",
        "\n",
        "        st.divider()\n",
        "\n",
        "        if st.button(\n",
        "            \"🏆 Run Competition Agent\",\n",
        "            use_container_width=True,\n",
        "        ):\n",
        "\n",
        "            run_agent(\n",
        "                \"competition\",\n",
        "                agents,\n",
        "            )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        st.error(\n",
        "            f\"GitHub service unavailable: {exc}\"\n",
        "        )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# WEEKLY REPORT\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"📊 Weekly Report\":\n",
        "\n",
        "    st.title(\n",
        "        \"📊 Weekly Progress Report\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Generate an AI-powered weekly STEM/project report.\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"📊 Generate Weekly Report\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        result = run_agent(\n",
        "            \"weekly\",\n",
        "            agents,\n",
        "        )\n",
        "\n",
        "        if isinstance(\n",
        "            result,\n",
        "            str,\n",
        "        ):\n",
        "\n",
        "            st.markdown(\n",
        "                \"### Weekly Report\"\n",
        "            )\n",
        "\n",
        "            st.markdown(\n",
        "                result\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# GMAIL\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"📧 Gmail\":\n",
        "\n",
        "    st.title(\n",
        "        \"📧 Gmail Service\"\n",
        "    )\n",
        "\n",
        "    gmail_address = os.getenv(\n",
        "        \"GMAIL_ADDRESS\",\n",
        "        \"\",\n",
        "    )\n",
        "\n",
        "    gmail_to = os.getenv(\n",
        "        \"GMAIL_TO\",\n",
        "        \"\",\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"Sender: `{gmail_address or 'Not configured'}`\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"Default recipient: `{gmail_to or 'Not configured'}`\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    subject = st.text_input(\n",
        "        \"Subject\",\n",
        "        value=\"AI STEM Automation Test\",\n",
        "    )\n",
        "\n",
        "    message = st.text_area(\n",
        "        \"Message\",\n",
        "        value=(\n",
        "            \"This is a test message from \"\n",
        "            \"the AI STEM Automation Hub.\"\n",
        "        ),\n",
        "        height=180,\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"📧 Send Test Email\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        try:\n",
        "\n",
        "            from services.gmail import (\n",
        "                send_email,\n",
        "            )\n",
        "\n",
        "            success = send_email(\n",
        "                subject=subject,\n",
        "                text_body=message,\n",
        "                email_type=\"dashboard_test\",\n",
        "            )\n",
        "\n",
        "            if success:\n",
        "\n",
        "                st.success(\n",
        "                    \"Email sent successfully.\"\n",
        "                )\n",
        "\n",
        "        except Exception as exc:\n",
        "\n",
        "            st.error(\n",
        "                f\"Email failed: {exc}\"\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# AUTOMATION\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"⚙️ Automation\":\n",
        "\n",
        "    st.title(\n",
        "        \"⚙️ Automation Control\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"View and manually control your scheduled agents.\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.markdown(\n",
        "        \"### 📅 Schedule\"\n",
        "    )\n",
        "\n",
        "    schedule = [\n",
        "        (\n",
        "            \"📰 AI / Robotics News\",\n",
        "            os.getenv(\n",
        "                \"NEWS_HOUR\",\n",
        "                \"8\",\n",
        "            ),\n",
        "            os.getenv(\n",
        "                \"NEWS_MINUTE\",\n",
        "                \"0\",\n",
        "            ),\n",
        "        ),\n",
        "        (\n",
        "            \"💡 STEM Tip\",\n",
        "            os.getenv(\n",
        "                \"STEM_TIP_HOUR\",\n",
        "                \"9\",\n",
        "            ),\n",
        "            os.getenv(\n",
        "                \"STEM_TIP_MINUTE\",\n",
        "                \"0\",\n",
        "            ),\n",
        "        ),\n",
        "        (\n",
        "            \"🔧 Project Idea\",\n",
        "            os.getenv(\n",
        "                \"PROJECT_HOUR\",\n",
        "                \"10\",\n",
        "            ),\n",
        "            os.getenv(\n",
        "                \"PROJECT_MINUTE\",\n",
        "                \"0\",\n",
        "            ),\n",
        "        ),\n",
        "        (\n",
        "            \"🏫 Class Update\",\n",
        "            os.getenv(\n",
        "                \"CLASS_UPDATE_HOUR\",\n",
        "                \"16\",\n",
        "            ),\n",
        "            os.getenv(\n",
        "                \"CLASS_UPDATE_MINUTE\",\n",
        "                \"30\",\n",
        "            ),\n",
        "        ),\n",
        "        (\n",
        "            \"🏆 Competition\",\n",
        "            os.getenv(\n",
        "                \"COMPETITION_HOUR\",\n",
        "                \"18\",\n",
        "            ),\n",
        "            os.getenv(\n",
        "                \"COMPETITION_MINUTE\",\n",
        "                \"0\",\n",
        "            ),\n",
        "        ),\n",
        "        (\n",
        "            \"📊 Weekly Report\",\n",
        "            (\n",
        "                \"Friday \"\n",
        "                + os.getenv(\n",
        "                    \"WEEKLY_REPORT_HOUR\",\n",
        "                    \"17\",\n",
        "                )\n",
        "                + \":\"\n",
        "                + os.getenv(\n",
        "                    \"WEEKLY_REPORT_MINUTE\",\n",
        "                    \"00\",\n",
        "                )\n",
        "            ),\n",
        "            \"\",\n",
        "        ),\n",
        "    ]\n",
        "\n",
        "    for name, hour, minute in schedule:\n",
        "\n",
        "        if minute:\n",
        "\n",
        "            time_text = (\n",
        "                f\"{int(hour):02d}:\"\n",
        "                f\"{int(minute):02d}\"\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            time_text = str(hour)\n",
        "\n",
        "        st.write(\n",
        "            f\"**{name}** — \"\n",
        "            f\"{time_text} \"\n",
        "            f\"({os.getenv('AUTOMATION_TIMEZONE', 'Asia/Kolkata')})\"\n",
        "        )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.markdown(\n",
        "        \"### ▶ Manual Execution\"\n",
        "    )\n",
        "\n",
        "    action = st.selectbox(\n",
        "        \"Select agent\",\n",
        "        [\n",
        "            \"news\",\n",
        "            \"stem_tip\",\n",
        "            \"project\",\n",
        "            \"class\",\n",
        "            \"competition\",\n",
        "            \"weekly\",\n",
        "        ],\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"▶ Run Selected Agent\",\n",
        "        type=\"primary\",\n",
        "        use_container_width=True,\n",
        "    ):\n",
        "\n",
        "        run_agent(\n",
        "            action,\n",
        "            agents,\n",
        "        )\n",
        "\n",
        "    st.warning(\n",
        "        \"The Streamlit interface can trigger jobs manually. \"\n",
        "        \"For automatic background execution, keep \"\n",
        "        \"`python services/jobs.py` running separately.\"\n",
        "    )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# SYSTEM HEALTH\n",
        "# ============================================================\n",
        "\n",
        "elif page == \"🔍 System Health\":\n",
        "\n",
        "    st.title(\n",
        "        \"🔍 System Health\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Check configuration and service availability.\"\n",
        "    )\n",
        "\n",
        "    status = service_status()\n",
        "\n",
        "    for name, value in status.items():\n",
        "\n",
        "        col1, col2 = st.columns(\n",
        "            [3, 1]\n",
        "        )\n",
        "\n",
        "        with col1:\n",
        "\n",
        "            st.write(\n",
        "                f\"**{name}**\"\n",
        "            )\n",
        "\n",
        "        with col2:\n",
        "\n",
        "            st.write(\n",
        "                status_badge(value)\n",
        "            )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.markdown(\n",
        "        \"### 🔐 Configuration\"\n",
        "    )\n",
        "\n",
        "    config_items = [\n",
        "        \"GEMINI_API_KEY\",\n",
        "        \"GMAIL_ADDRESS\",\n",
        "        \"GMAIL_APP_PASSWORD\",\n",
        "        \"GMAIL_TO\",\n",
        "        \"GITHUB_TOKEN\",\n",
        "        \"GITHUB_REPOSITORY\",\n",
        "    ]\n",
        "\n",
        "    for key in config_items:\n",
        "\n",
        "        value = os.getenv(\n",
        "            key\n",
        "        )\n",
        "\n",
        "        if value:\n",
        "\n",
        "            if (\n",
        "                \"PASSWORD\" in key\n",
        "                or \"TOKEN\" in key\n",
        "                or \"API_KEY\" in key\n",
        "            ):\n",
        "\n",
        "                display = \"********\"\n",
        "\n",
        "            else:\n",
        "\n",
        "                display = value\n",
        "\n",
        "            st.write(\n",
        "                f\"**{key}:** `{display}`\"\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.write(\n",
        "                f\"**{key}:** \"\n",
        "                \"❌ Not configured\"\n",
        "            )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.markdown(\n",
        "        \"### 🧩 Agent Loading\"\n",
        "    )\n",
        "\n",
        "    for name, agent in agents.items():\n",
        "\n",
        "        if isinstance(\n",
        "            agent,\n",
        "            dict,\n",
        "        ):\n",
        "\n",
        "            st.error(\n",
        "                f\"{name}: \"\n",
        "                f\"{agent.get('error', 'Unknown error')}\"\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.success(\n",
        "                f\"{name}: Ready\"\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# FOOTER\n",
        "# ============================================================\n",
        "\n",
        "st.divider()\n",
        "\n",
        "st.caption(\n",
        "    \"AI STEM Automation Hub • \"\n",
        "    \"Gemini + GitHub + Gmail + Web Search + APScheduler\"\n",
        ")\n",
        "```\n"
      ],
      "metadata": {
        "id": "0wr3lRn32QDS"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "name": "Welcome To Colab",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
