{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOixzkBjjUuuomFgyPriiHX",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/class_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "agents/class_agent.py\n",
        "\n",
        "STEM Class Update Agent\n",
        "\n",
        "Responsibilities:\n",
        "- Accept daily STEM class/session data\n",
        "- Organize sessions grade-wise\n",
        "- Generate concise professional updates using Gemini\n",
        "- Store updates in SQLite\n",
        "- Generate an email-ready report\n",
        "- Send the report using Gmail SMTP\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import html\n",
        "import logging\n",
        "from dataclasses import dataclass\n",
        "from datetime import datetime\n",
        "from typing import Any, Optional\n",
        "\n",
        "import database\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.ClassAgent\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATA MODEL\n",
        "# =========================================================\n",
        "\n",
        "@dataclass\n",
        "class ClassSession:\n",
        "    \"\"\"Represents one STEM class session.\"\"\"\n",
        "\n",
        "    grade: str\n",
        "    section: str\n",
        "    topic: str\n",
        "    activity: str\n",
        "    skills: str = \"\"\n",
        "    notes: str = \"\"\n",
        "    session_date: str = \"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAMPLE / DEFAULT SESSION DATA\n",
        "# =========================================================\n",
        "\n",
        "# Replace these with your actual daily sessions.\n",
        "#\n",
        "# Example:\n",
        "#\n",
        "# DAILY_SESSIONS = [\n",
        "#     ClassSession(\n",
        "#         grade=\"5\",\n",
        "#         section=\"A\",\n",
        "#         topic=\"Transistor as a Switch\",\n",
        "#         activity=\"Built an LED switching circuit\",\n",
        "#         skills=\"Electronics, circuit building\",\n",
        "#     ),\n",
        "# ]\n",
        "\n",
        "DAILY_SESSIONS: list[ClassSession] = []\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPERS\n",
        "# =========================================================\n",
        "\n",
        "def today() -> str:\n",
        "    \"\"\"Return today's date.\"\"\"\n",
        "\n",
        "    return datetime.now().strftime(\n",
        "        \"%Y-%m-%d\"\n",
        "    )\n",
        "\n",
        "\n",
        "def clean_text(value: Any) -> str:\n",
        "    \"\"\"Clean text input.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return \"\"\n",
        "\n",
        "    return \" \".join(\n",
        "        str(value).strip().split()\n",
        "    )\n",
        "\n",
        "\n",
        "def safe_html(value: str) -> str:\n",
        "    \"\"\"Escape text for HTML email.\"\"\"\n",
        "\n",
        "    return html.escape(\n",
        "        value or \"\",\n",
        "        quote=True,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ADD CLASS SESSION\n",
        "# =========================================================\n",
        "\n",
        "def add_session(\n",
        "    grade: str,\n",
        "    section: str,\n",
        "    topic: str,\n",
        "    activity: str,\n",
        "    skills: str = \"\",\n",
        "    notes: str = \"\",\n",
        "    session_date: Optional[str] = None,\n",
        ") -> ClassSession:\n",
        "    \"\"\"\n",
        "    Create a ClassSession object.\n",
        "\n",
        "    Example:\n",
        "\n",
        "        add_session(\n",
        "            \"5\",\n",
        "            \"A\",\n",
        "            \"Transistor as a switch\",\n",
        "            \"Built an LED switching circuit\",\n",
        "        )\n",
        "    \"\"\"\n",
        "\n",
        "    if session_date is None:\n",
        "        session_date = today()\n",
        "\n",
        "    session = ClassSession(\n",
        "        grade=clean_text(grade),\n",
        "        section=clean_text(section),\n",
        "        topic=clean_text(topic),\n",
        "        activity=clean_text(activity),\n",
        "        skills=clean_text(skills),\n",
        "        notes=clean_text(notes),\n",
        "        session_date=session_date,\n",
        "    )\n",
        "\n",
        "    return session\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# VALIDATION\n",
        "# =========================================================\n",
        "\n",
        "def validate_session(\n",
        "    session: ClassSession,\n",
        ") -> bool:\n",
        "    \"\"\"Validate a class session.\"\"\"\n",
        "\n",
        "    if not session.grade:\n",
        "        return False\n",
        "\n",
        "    if not session.topic:\n",
        "        return False\n",
        "\n",
        "    if not session.activity:\n",
        "        return False\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "def validate_sessions(\n",
        "    sessions: list[ClassSession],\n",
        ") -> list[ClassSession]:\n",
        "    \"\"\"Remove invalid sessions.\"\"\"\n",
        "\n",
        "    valid = []\n",
        "\n",
        "    for session in sessions:\n",
        "\n",
        "        if validate_session(session):\n",
        "            valid.append(session)\n",
        "\n",
        "        else:\n",
        "            logger.warning(\n",
        "                \"Skipping incomplete session: %s\",\n",
        "                session,\n",
        "            )\n",
        "\n",
        "    return valid\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GROUP BY GRADE\n",
        "# =========================================================\n",
        "\n",
        "def group_by_grade(\n",
        "    sessions: list[ClassSession],\n",
        ") -> dict[str, list[ClassSession]]:\n",
        "    \"\"\"Group sessions by grade.\"\"\"\n",
        "\n",
        "    grouped: dict[\n",
        "        str,\n",
        "        list[ClassSession]\n",
        "    ] = {}\n",
        "\n",
        "    for session in sessions:\n",
        "\n",
        "        grade_key = (\n",
        "            f\"Grade {session.grade}\"\n",
        "        )\n",
        "\n",
        "        grouped.setdefault(\n",
        "            grade_key,\n",
        "            [],\n",
        "        ).append(session)\n",
        "\n",
        "    return grouped\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAVE SESSIONS\n",
        "# =========================================================\n",
        "\n",
        "def save_sessions(\n",
        "    sessions: list[ClassSession],\n",
        ") -> None:\n",
        "    \"\"\"Save class sessions to SQLite.\"\"\"\n",
        "\n",
        "    for session in sessions:\n",
        "\n",
        "        database.add_class_update(\n",
        "            grade=session.grade,\n",
        "            section=session.section,\n",
        "            topic=session.topic,\n",
        "            activity=session.activity,\n",
        "            skills=session.skills,\n",
        "            notes=session.notes,\n",
        "            session_date=session.session_date,\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI CLASS REPORT\n",
        "# =========================================================\n",
        "\n",
        "def generate_ai_report(\n",
        "    sessions: list[ClassSession],\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Generate a concise professional class report\n",
        "    using Gemini.\n",
        "\n",
        "    Expected interface in services/gemini.py:\n",
        "\n",
        "        generate_class_report(data)\n",
        "    \"\"\"\n",
        "\n",
        "    if not sessions:\n",
        "        return \"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gemini import (\n",
        "            generate_class_report,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gemini.py before \"\n",
        "            \"running the class agent.\"\n",
        "        ) from exc\n",
        "\n",
        "    data = []\n",
        "\n",
        "    for session in sessions:\n",
        "\n",
        "        data.append(\n",
        "            {\n",
        "                \"grade\": session.grade,\n",
        "                \"section\": session.section,\n",
        "                \"topic\": session.topic,\n",
        "                \"activity\": session.activity,\n",
        "                \"skills\": session.skills,\n",
        "                \"notes\": session.notes,\n",
        "                \"date\": session.session_date,\n",
        "            }\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"Sending %d class sessions to Gemini.\",\n",
        "        len(data),\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        report = generate_class_report(\n",
        "            data\n",
        "        )\n",
        "\n",
        "        return clean_text(\n",
        "            report\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gemini class report failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return generate_fallback_report(\n",
        "            sessions\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# FALLBACK REPORT\n",
        "# =========================================================\n",
        "\n",
        "def generate_fallback_report(\n",
        "    sessions: list[ClassSession],\n",
        ") -> str:\n",
        "    \"\"\"Generate a report without Gemini.\"\"\"\n",
        "\n",
        "    grouped = group_by_grade(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    lines = [\n",
        "        \"STEM CLASS SESSION UPDATE\",\n",
        "        \"\",\n",
        "    ]\n",
        "\n",
        "    for grade, grade_sessions in grouped.items():\n",
        "\n",
        "        lines.append(\n",
        "            f\"{grade}\"\n",
        "        )\n",
        "\n",
        "        for session in grade_sessions:\n",
        "\n",
        "            section = (\n",
        "                f\"{session.section}\"\n",
        "                if session.section\n",
        "                else \"\"\n",
        "            )\n",
        "\n",
        "            section_text = (\n",
        "                f\"{grade}{section}\"\n",
        "            )\n",
        "\n",
        "            lines.append(\n",
        "                f\"- {section_text}: \"\n",
        "                f\"{session.topic}. \"\n",
        "                f\"{session.activity}.\"\n",
        "            )\n",
        "\n",
        "        lines.append(\"\")\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_html_report(\n",
        "    sessions: list[ClassSession],\n",
        "    ai_summary: str,\n",
        ") -> str:\n",
        "    \"\"\"Generate HTML email.\"\"\"\n",
        "\n",
        "    date_display = datetime.now().strftime(\n",
        "        \"%d %B %Y\"\n",
        "    )\n",
        "\n",
        "    grouped = group_by_grade(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    grade_blocks = []\n",
        "\n",
        "    for grade, grade_sessions in grouped.items():\n",
        "\n",
        "        session_rows = []\n",
        "\n",
        "        for session in grade_sessions:\n",
        "\n",
        "            section = safe_html(\n",
        "                session.section\n",
        "            )\n",
        "\n",
        "            topic = safe_html(\n",
        "                session.topic\n",
        "            )\n",
        "\n",
        "            activity = safe_html(\n",
        "                session.activity\n",
        "            )\n",
        "\n",
        "            skills = safe_html(\n",
        "                session.skills\n",
        "            )\n",
        "\n",
        "            section_label = (\n",
        "                f\"{grade} - Section {section}\"\n",
        "                if section\n",
        "                else grade\n",
        "            )\n",
        "\n",
        "            session_rows.append(\n",
        "                f\"\"\"\n",
        "                <div style=\"\n",
        "                    padding:15px;\n",
        "                    margin:10px 0;\n",
        "                    border-left:4px solid #333;\n",
        "                    background:#f8f9fa;\n",
        "                \">\n",
        "\n",
        "                    <strong>\n",
        "                        {safe_html(section_label)}\n",
        "                    </strong>\n",
        "\n",
        "                    <div style=\"\n",
        "                        margin-top:6px;\n",
        "                        font-size:16px;\n",
        "                    \">\n",
        "                        <strong>Topic:</strong>\n",
        "                        {topic}\n",
        "                    </div>\n",
        "\n",
        "                    <div style=\"\n",
        "                        margin-top:6px;\n",
        "                        line-height:1.5;\n",
        "                    \">\n",
        "                        <strong>Activity:</strong>\n",
        "                        {activity}\n",
        "                    </div>\n",
        "\n",
        "                    {\n",
        "                        f'''\n",
        "                        <div style=\"\n",
        "                            margin-top:6px;\n",
        "                            color:#555;\n",
        "                        \">\n",
        "                            <strong>Skills:</strong>\n",
        "                            {skills}\n",
        "                        </div>\n",
        "                        '''\n",
        "                        if skills\n",
        "                        else \"\"\n",
        "                    }\n",
        "\n",
        "                </div>\n",
        "                \"\"\"\n",
        "            )\n",
        "\n",
        "        grade_blocks.append(\n",
        "            f\"\"\"\n",
        "            <section style=\"\n",
        "                margin-bottom:25px;\n",
        "            \">\n",
        "\n",
        "                <h2 style=\"\n",
        "                    font-size:20px;\n",
        "                \">\n",
        "                    {safe_html(grade)}\n",
        "                </h2>\n",
        "\n",
        "                {''.join(session_rows)}\n",
        "\n",
        "            </section>\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "    summary_html = safe_html(\n",
        "        ai_summary\n",
        "    ).replace(\n",
        "        \"\\n\",\n",
        "        \"<br>\",\n",
        "    )\n",
        "\n",
        "    return f\"\"\"\n",
        "    <!DOCTYPE html>\n",
        "\n",
        "    <html>\n",
        "\n",
        "    <head>\n",
        "        <meta charset=\"UTF-8\">\n",
        "        <title>STEM Class Update</title>\n",
        "    </head>\n",
        "\n",
        "    <body style=\"\n",
        "        margin:0;\n",
        "        padding:0;\n",
        "        background:#f4f6f8;\n",
        "        font-family:Arial,Helvetica,sans-serif;\n",
        "    \">\n",
        "\n",
        "        <div style=\"\n",
        "            max-width:760px;\n",
        "            margin:30px auto;\n",
        "            background:white;\n",
        "            padding:30px;\n",
        "            border-radius:12px;\n",
        "        \">\n",
        "\n",
        "            <h1>\n",
        "                🏫 STEM Class Update\n",
        "            </h1>\n",
        "\n",
        "            <p style=\"color:#666;\">\n",
        "                {date_display}\n",
        "            </p>\n",
        "\n",
        "            <hr>\n",
        "\n",
        "            <h2>\n",
        "                📋 AI Summary\n",
        "            </h2>\n",
        "\n",
        "            <div style=\"\n",
        "                padding:15px;\n",
        "                background:#f8f9fa;\n",
        "                line-height:1.6;\n",
        "            \">\n",
        "                {summary_html}\n",
        "            </div>\n",
        "\n",
        "            <h2 style=\"\n",
        "                margin-top:30px;\n",
        "            \">\n",
        "                📚 Grade-wise Sessions\n",
        "            </h2>\n",
        "\n",
        "            {''.join(grade_blocks)}\n",
        "\n",
        "            <hr>\n",
        "\n",
        "            <p style=\"\n",
        "                color:#777;\n",
        "                font-size:13px;\n",
        "            \">\n",
        "                Generated by\n",
        "                <strong>AI STEM Automation Hub</strong>.\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "\n",
        "    </body>\n",
        "\n",
        "    </html>\n",
        "    \"\"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEXT EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_text_report(\n",
        "    sessions: list[ClassSession],\n",
        "    ai_summary: str,\n",
        ") -> str:\n",
        "    \"\"\"Generate plain-text fallback email.\"\"\"\n",
        "\n",
        "    lines = [\n",
        "        \"STEM CLASS UPDATE\",\n",
        "        datetime.now().strftime(\n",
        "            \"%d %B %Y\"\n",
        "        ),\n",
        "        \"\",\n",
        "        \"AI SUMMARY\",\n",
        "        \"==========\",\n",
        "        ai_summary,\n",
        "        \"\",\n",
        "        \"GRADE-WISE SESSIONS\",\n",
        "        \"===================\",\n",
        "        \"\",\n",
        "    ]\n",
        "\n",
        "    grouped = group_by_grade(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    for grade, grade_sessions in grouped.items():\n",
        "\n",
        "        lines.append(\n",
        "            grade\n",
        "        )\n",
        "\n",
        "        for session in grade_sessions:\n",
        "\n",
        "            section = (\n",
        "                f\" - Section {session.section}\"\n",
        "                if session.section\n",
        "                else \"\"\n",
        "            )\n",
        "\n",
        "            lines.extend(\n",
        "                [\n",
        "                    f\"Topic: {session.topic}\",\n",
        "                    f\"Activity: {session.activity}\",\n",
        "                ]\n",
        "            )\n",
        "\n",
        "            if session.skills:\n",
        "\n",
        "                lines.append(\n",
        "                    f\"Skills: {session.skills}\"\n",
        "                )\n",
        "\n",
        "            lines.append(\"\")\n",
        "\n",
        "        lines.append(\"\")\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SEND EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_class_email(\n",
        "    sessions: list[ClassSession],\n",
        "    ai_summary: str,\n",
        ") -> bool:\n",
        "    \"\"\"Send class update through Gmail service.\"\"\"\n",
        "\n",
        "    if not sessions:\n",
        "\n",
        "        logger.warning(\n",
        "            \"No class sessions available.\"\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gmail import (\n",
        "            send_email,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gmail.py before \"\n",
        "            \"sending class emails.\"\n",
        "        ) from exc\n",
        "\n",
        "    subject = (\n",
        "        \"🏫 STEM Class Update - \"\n",
        "        + datetime.now().strftime(\n",
        "            \"%d %b %Y\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    html_body = generate_html_report(\n",
        "        sessions,\n",
        "        ai_summary,\n",
        "    )\n",
        "\n",
        "    text_body = generate_text_report(\n",
        "        sessions,\n",
        "        ai_summary,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        send_email(\n",
        "            subject=subject,\n",
        "            html_body=html_body,\n",
        "            text_body=text_body,\n",
        "            email_type=\"class_update\",\n",
        "        )\n",
        "\n",
        "        logger.info(\n",
        "            \"STEM class update email sent.\"\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Failed to send class update: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RUN CLASS AGENT\n",
        "# =========================================================\n",
        "\n",
        "def run_class_agent(\n",
        "    sessions: Optional[\n",
        "        list[ClassSession]\n",
        "    ] = None,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Run the STEM Class Update Agent.\n",
        "\n",
        "    If sessions are not provided, DAILY_SESSIONS\n",
        "    is used.\n",
        "    \"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting STEM Class Update Agent.\"\n",
        "    )\n",
        "\n",
        "    if sessions is None:\n",
        "\n",
        "        sessions = DAILY_SESSIONS\n",
        "\n",
        "    sessions = validate_sessions(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    if not sessions:\n",
        "\n",
        "        logger.warning(\n",
        "            \"No valid class sessions found.\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"success\": False,\n",
        "            \"sessions\": 0,\n",
        "            \"email_sent\": False,\n",
        "            \"message\": (\n",
        "                \"No class sessions available.\"\n",
        "            ),\n",
        "        }\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Save raw sessions\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    save_sessions(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Generate AI summary\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    ai_summary = generate_ai_report(\n",
        "        sessions\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Send email\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    email_sent = send_class_email(\n",
        "        sessions,\n",
        "        ai_summary,\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Class agent completed.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"success\": True,\n",
        "        \"sessions\": len(sessions),\n",
        "        \"email_sent\": email_sent,\n",
        "        \"summary\": ai_summary,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    # Example test data.\n",
        "    #\n",
        "    # Replace this with your actual sessions.\n",
        "\n",
        "    test_sessions = [\n",
        "\n",
        "        add_session(\n",
        "            grade=\"5\",\n",
        "            section=\"A\",\n",
        "            topic=\"Transistor as a Switch\",\n",
        "            activity=(\n",
        "                \"Students built an LED \"\n",
        "                \"switching circuit.\"\n",
        "            ),\n",
        "            skills=(\n",
        "                \"Electronics, circuit building \"\n",
        "                \"and troubleshooting\"\n",
        "            ),\n",
        "        ),\n",
        "\n",
        "        add_session(\n",
        "            grade=\"4\",\n",
        "            section=\"C\",\n",
        "            topic=\"Basic Electronics\",\n",
        "            activity=(\n",
        "                \"Students explored the function \"\n",
        "                \"of a transistor in a simple circuit.\"\n",
        "            ),\n",
        "            skills=(\n",
        "                \"Component identification \"\n",
        "                \"and circuit understanding\"\n",
        "            ),\n",
        "        ),\n",
        "\n",
        "        add_session(\n",
        "            grade=\"3\",\n",
        "            section=\"B\",\n",
        "            topic=\"Transistor\",\n",
        "            activity=(\n",
        "                \"Students learned how a transistor \"\n",
        "                \"can be used as an electronic switch.\"\n",
        "            ),\n",
        "            skills=(\n",
        "                \"Basic electronics\"\n",
        "            ),\n",
        "        ),\n",
        "    ]\n",
        "\n",
        "    result = run_class_agent(\n",
        "        test_sessions\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"CLASS AGENT RESULT\")\n",
        "    print(\"=\" * 60)\n",
        "    print(\n",
        "        f\"Success    : \"\n",
        "        f\"{result.get('success')}\"\n",
        "    )\n",
        "    print(\n",
        "        f\"Sessions   : \"\n",
        "        f\"{result.get('sessions', 0)}\"\n",
        "    )\n",
        "    print(\n",
        "        f\"Email sent : \"\n",
        "        f\"{result.get('email_sent', False)}\"\n",
        "    )\n",
        "    print()\n",
        "    print(\n",
        "        result.get(\n",
        "            \"summary\",\n",
        "            \"\",\n",
        "        )\n",
        "    )\n",
        "    print(\"=\" * 60)"
      ],
      "metadata": {
        "id": "05unRGQNuU_z"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}