{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMUey/Ux9Xb0HAMTyHzoZER",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/competition_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "agents/competition_agent.py\n",
        "\n",
        "Competition / AI Project Update Agent\n",
        "\n",
        "Responsibilities:\n",
        "- Track AI/ML/robotics competition projects\n",
        "- Read project progress from SQLite\n",
        "- Generate an AI progress summary\n",
        "- Detect blockers and next actions\n",
        "- Store competition updates\n",
        "- Send progress updates through Gmail SMTP\n",
        "- Prevent unnecessary duplicate notifications\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import html\n",
        "import json\n",
        "import logging\n",
        "from datetime import datetime\n",
        "from typing import Any, Optional\n",
        "\n",
        "import database\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.CompetitionAgent\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DEFAULT CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "DEFAULT_PROJECT_NAME = (\n",
        "    \"Kaggriculture AI Agent\"\n",
        ")\n",
        "\n",
        "DEFAULT_PROJECT_TYPE = (\n",
        "    \"AI Competition\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPERS\n",
        "# =========================================================\n",
        "\n",
        "def clean_text(\n",
        "    value: Any,\n",
        ") -> str:\n",
        "    \"\"\"Clean a value returned by the database or AI.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return \"\"\n",
        "\n",
        "    return \" \".join(\n",
        "        str(value).strip().split()\n",
        "    )\n",
        "\n",
        "\n",
        "def safe_html(\n",
        "    value: str,\n",
        ") -> str:\n",
        "    \"\"\"Escape text for HTML email.\"\"\"\n",
        "\n",
        "    return html.escape(\n",
        "        value or \"\",\n",
        "        quote=True,\n",
        "    )\n",
        "\n",
        "\n",
        "def format_list(\n",
        "    value: Any,\n",
        ") -> list[str]:\n",
        "    \"\"\"Convert a value into a clean string list.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return []\n",
        "\n",
        "    if isinstance(value, str):\n",
        "\n",
        "        if not value.strip():\n",
        "            return []\n",
        "\n",
        "        # Try JSON first.\n",
        "        try:\n",
        "\n",
        "            parsed = json.loads(\n",
        "                value\n",
        "            )\n",
        "\n",
        "            if isinstance(\n",
        "                parsed,\n",
        "                list,\n",
        "            ):\n",
        "\n",
        "                return [\n",
        "                    clean_text(item)\n",
        "                    for item in parsed\n",
        "                    if clean_text(item)\n",
        "                ]\n",
        "\n",
        "        except (\n",
        "            json.JSONDecodeError,\n",
        "            TypeError,\n",
        "        ):\n",
        "            pass\n",
        "\n",
        "        # Fall back to comma-separated.\n",
        "        return [\n",
        "            clean_text(item)\n",
        "            for item in value.split(\",\")\n",
        "            if clean_text(item)\n",
        "        ]\n",
        "\n",
        "    if isinstance(value, list):\n",
        "\n",
        "        return [\n",
        "            clean_text(item)\n",
        "            for item in value\n",
        "            if clean_text(item)\n",
        "        ]\n",
        "\n",
        "    return []\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PROJECT STATUS\n",
        "# =========================================================\n",
        "\n",
        "def get_project_status(\n",
        "    project_name: str = DEFAULT_PROJECT_NAME,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Get the latest competition project status.\n",
        "\n",
        "    Expected database.py function:\n",
        "\n",
        "        get_competition_project(project_name)\n",
        "\n",
        "    The database should contain the latest known\n",
        "    project information.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        project = (\n",
        "            database.get_competition_project(\n",
        "                project_name\n",
        "            )\n",
        "        )\n",
        "\n",
        "    except AttributeError:\n",
        "\n",
        "        logger.warning(\n",
        "            \"database.py does not yet provide \"\n",
        "            \"get_competition_project().\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"name\": project_name,\n",
        "            \"type\": DEFAULT_PROJECT_TYPE,\n",
        "            \"status\": \"Unknown\",\n",
        "            \"version\": \"\",\n",
        "            \"score\": \"\",\n",
        "            \"rank\": \"\",\n",
        "            \"episodes\": \"\",\n",
        "            \"wins\": \"\",\n",
        "            \"losses\": \"\",\n",
        "            \"win_rate\": \"\",\n",
        "            \"notes\": \"\",\n",
        "            \"blockers\": [],\n",
        "            \"next_actions\": [],\n",
        "        }\n",
        "\n",
        "    if not project:\n",
        "\n",
        "        return {\n",
        "            \"name\": project_name,\n",
        "            \"type\": DEFAULT_PROJECT_TYPE,\n",
        "            \"status\": \"No data\",\n",
        "            \"version\": \"\",\n",
        "            \"score\": \"\",\n",
        "            \"rank\": \"\",\n",
        "            \"episodes\": \"\",\n",
        "            \"wins\": \"\",\n",
        "            \"losses\": \"\",\n",
        "            \"win_rate\": \"\",\n",
        "            \"notes\": \"\",\n",
        "            \"blockers\": [],\n",
        "            \"next_actions\": [],\n",
        "        }\n",
        "\n",
        "    return dict(project)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NORMALIZE STATUS\n",
        "# =========================================================\n",
        "\n",
        "def normalize_status(\n",
        "    project: dict[str, Any],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"Normalize competition project data.\"\"\"\n",
        "\n",
        "    return {\n",
        "        \"name\": clean_text(\n",
        "            project.get(\n",
        "                \"name\",\n",
        "                DEFAULT_PROJECT_NAME,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"type\": clean_text(\n",
        "            project.get(\n",
        "                \"type\",\n",
        "                DEFAULT_PROJECT_TYPE,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"status\": clean_text(\n",
        "            project.get(\n",
        "                \"status\",\n",
        "                \"Unknown\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"version\": clean_text(\n",
        "            project.get(\n",
        "                \"version\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"score\": clean_text(\n",
        "            project.get(\n",
        "                \"score\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"rank\": clean_text(\n",
        "            project.get(\n",
        "                \"rank\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"episodes\": clean_text(\n",
        "            project.get(\n",
        "                \"episodes\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"wins\": clean_text(\n",
        "            project.get(\n",
        "                \"wins\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"losses\": clean_text(\n",
        "            project.get(\n",
        "                \"losses\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"win_rate\": clean_text(\n",
        "            project.get(\n",
        "                \"win_rate\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"notes\": clean_text(\n",
        "            project.get(\n",
        "                \"notes\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"blockers\": format_list(\n",
        "            project.get(\n",
        "                \"blockers\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"next_actions\": format_list(\n",
        "            project.get(\n",
        "                \"next_actions\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"repository\": clean_text(\n",
        "            project.get(\n",
        "                \"repository\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"submission_status\": clean_text(\n",
        "            project.get(\n",
        "                \"submission_status\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI ANALYSIS\n",
        "# =========================================================\n",
        "\n",
        "def generate_ai_update(\n",
        "    project: dict[str, Any],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate an AI competition update.\n",
        "\n",
        "    Expected services/gemini.py function:\n",
        "\n",
        "        generate_competition_update(...)\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gemini import (\n",
        "            generate_competition_update,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gemini.py before \"\n",
        "            \"running the competition agent.\"\n",
        "        ) from exc\n",
        "\n",
        "    logger.info(\n",
        "        \"Generating AI competition analysis.\"\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        result = (\n",
        "            generate_competition_update(\n",
        "                project=project\n",
        "            )\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gemini competition analysis failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return generate_fallback_update(\n",
        "            project\n",
        "        )\n",
        "\n",
        "    if isinstance(result, str):\n",
        "\n",
        "        try:\n",
        "\n",
        "            result = json.loads(\n",
        "                result\n",
        "            )\n",
        "\n",
        "        except json.JSONDecodeError:\n",
        "\n",
        "            result = {\n",
        "                \"summary\": result,\n",
        "                \"achievement\": \"\",\n",
        "                \"risk\": \"\",\n",
        "                \"recommendation\": \"\",\n",
        "                \"next_actions\": [],\n",
        "            }\n",
        "\n",
        "    if not isinstance(\n",
        "        result,\n",
        "        dict,\n",
        "    ):\n",
        "\n",
        "        return generate_fallback_update(\n",
        "            project\n",
        "        )\n",
        "\n",
        "    return {\n",
        "        \"summary\": clean_text(\n",
        "            result.get(\n",
        "                \"summary\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"achievement\": clean_text(\n",
        "            result.get(\n",
        "                \"achievement\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"risk\": clean_text(\n",
        "            result.get(\n",
        "                \"risk\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"recommendation\": clean_text(\n",
        "            result.get(\n",
        "                \"recommendation\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"next_actions\": format_list(\n",
        "            result.get(\n",
        "                \"next_actions\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# FALLBACK ANALYSIS\n",
        "# =========================================================\n",
        "\n",
        "def generate_fallback_update(\n",
        "    project: dict[str, Any],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"Generate an update without Gemini.\"\"\"\n",
        "\n",
        "    status = project[\n",
        "        \"status\"\n",
        "    ]\n",
        "\n",
        "    achievement = \"\"\n",
        "\n",
        "    if project[\"score\"]:\n",
        "\n",
        "        achievement = (\n",
        "            f\"Current score: \"\n",
        "            f\"{project['score']}.\"\n",
        "        )\n",
        "\n",
        "    if project[\"version\"]:\n",
        "\n",
        "        achievement += (\n",
        "            f\" Current version: \"\n",
        "            f\"{project['version']}.\"\n",
        "        )\n",
        "\n",
        "    risk = \"\"\n",
        "\n",
        "    if project[\"blockers\"]:\n",
        "\n",
        "        risk = \"; \".join(\n",
        "            project[\"blockers\"]\n",
        "        )\n",
        "\n",
        "    elif status.lower() in {\n",
        "        \"failed\",\n",
        "        \"error\",\n",
        "        \"blocked\",\n",
        "    }:\n",
        "\n",
        "        risk = (\n",
        "            \"The project currently \"\n",
        "            \"requires attention.\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        risk = (\n",
        "            \"No major blocker was recorded.\"\n",
        "        )\n",
        "\n",
        "    next_actions = project[\n",
        "        \"next_actions\"\n",
        "    ]\n",
        "\n",
        "    if not next_actions:\n",
        "\n",
        "        next_actions = [\n",
        "            \"Run another evaluation.\",\n",
        "            \"Review the latest score.\",\n",
        "            \"Record the result.\",\n",
        "        ]\n",
        "\n",
        "    summary = (\n",
        "        f\"{project['name']} is currently \"\n",
        "        f\"{status.lower()}.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"summary\": summary,\n",
        "        \"achievement\": achievement,\n",
        "        \"risk\": risk,\n",
        "        \"recommendation\": (\n",
        "            \"Continue iterative testing \"\n",
        "            \"and compare the latest result \"\n",
        "            \"against the previous version.\"\n",
        "        ),\n",
        "        \"next_actions\": next_actions,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAVE UPDATE\n",
        "# =========================================================\n",
        "\n",
        "def save_competition_update(\n",
        "    project: dict[str, Any],\n",
        "    analysis: dict[str, Any],\n",
        ") -> int:\n",
        "    \"\"\"Save competition update to SQLite.\"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        return database.add_competition_update(\n",
        "            project_name=project[\"name\"],\n",
        "            version=project[\"version\"],\n",
        "            status=project[\"status\"],\n",
        "            score=project[\"score\"],\n",
        "            rank=project[\"rank\"],\n",
        "            summary=analysis[\"summary\"],\n",
        "            recommendation=(\n",
        "                analysis[\"recommendation\"]\n",
        "            ),\n",
        "        )\n",
        "\n",
        "    except AttributeError:\n",
        "\n",
        "        logger.warning(\n",
        "            \"database.py does not yet provide \"\n",
        "            \"add_competition_update().\"\n",
        "        )\n",
        "\n",
        "        return 0\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_html_email(\n",
        "    project: dict[str, Any],\n",
        "    analysis: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate HTML competition update.\"\"\"\n",
        "\n",
        "    timestamp = datetime.now().strftime(\n",
        "        \"%d %B %Y, %I:%M %p\"\n",
        "    )\n",
        "\n",
        "    blockers_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li>\n",
        "            {safe_html(blocker)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for blocker in project[\n",
        "            \"blockers\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    next_actions = analysis[\n",
        "        \"next_actions\"\n",
        "    ]\n",
        "\n",
        "    actions_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li style=\"\n",
        "            margin-bottom:8px;\n",
        "        \">\n",
        "            {safe_html(action)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for action in next_actions\n",
        "    )\n",
        "\n",
        "    blockers_section = \"\"\n",
        "\n",
        "    if project[\"blockers\"]:\n",
        "\n",
        "        blockers_section = f\"\"\"\n",
        "        <h3>\n",
        "            ⚠️ Blockers\n",
        "        </h3>\n",
        "\n",
        "        <ul>\n",
        "            {blockers_html}\n",
        "        </ul>\n",
        "        \"\"\"\n",
        "\n",
        "    repository_section = \"\"\n",
        "\n",
        "    if project[\"repository\"]:\n",
        "\n",
        "        repository_section = f\"\"\"\n",
        "        <p>\n",
        "            <strong>\n",
        "                Repository:\n",
        "            </strong>\n",
        "\n",
        "            {safe_html(\n",
        "                project[\"repository\"]\n",
        "            )}\n",
        "        </p>\n",
        "        \"\"\"\n",
        "\n",
        "    return f\"\"\"\n",
        "    <!DOCTYPE html>\n",
        "\n",
        "    <html>\n",
        "\n",
        "    <head>\n",
        "        <meta charset=\"UTF-8\">\n",
        "\n",
        "        <title>\n",
        "            AI Competition Update\n",
        "        </title>\n",
        "    </head>\n",
        "\n",
        "    <body style=\"\n",
        "        margin:0;\n",
        "        padding:0;\n",
        "        background:#f4f6f8;\n",
        "        font-family:Arial,Helvetica,sans-serif;\n",
        "    \">\n",
        "\n",
        "        <div style=\"\n",
        "            max-width:780px;\n",
        "            margin:30px auto;\n",
        "            padding:30px;\n",
        "            background:#ffffff;\n",
        "            border-radius:12px;\n",
        "        \">\n",
        "\n",
        "            <h1>\n",
        "                🏆 AI Competition Update\n",
        "            </h1>\n",
        "\n",
        "            <p style=\"\n",
        "                color:#666;\n",
        "            \">\n",
        "                {safe_html(timestamp)}\n",
        "            </p>\n",
        "\n",
        "            <hr>\n",
        "\n",
        "            <h2>\n",
        "                {safe_html(project[\"name\"])}\n",
        "            </h2>\n",
        "\n",
        "            <p>\n",
        "                <strong>\n",
        "                    Type:\n",
        "                </strong>\n",
        "\n",
        "                {safe_html(project[\"type\"])}\n",
        "            </p>\n",
        "\n",
        "            <p>\n",
        "                <strong>\n",
        "                    Status:\n",
        "                </strong>\n",
        "\n",
        "                {safe_html(project[\"status\"])}\n",
        "            </p>\n",
        "\n",
        "            {repository_section}\n",
        "\n",
        "            <div style=\"\n",
        "                display:flex;\n",
        "                flex-wrap:wrap;\n",
        "                gap:12px;\n",
        "                margin:25px 0;\n",
        "            \">\n",
        "\n",
        "                <div style=\"\n",
        "                    padding:15px;\n",
        "                    background:#f8f9fa;\n",
        "                    border-radius:8px;\n",
        "                    min-width:100px;\n",
        "                \">\n",
        "\n",
        "                    <strong>\n",
        "                        {safe_html(\n",
        "                            project[\"version\"]\n",
        "                            or \"-\"\n",
        "                        )}\n",
        "                    </strong>\n",
        "\n",
        "                    <br>\n",
        "\n",
        "                    Version\n",
        "\n",
        "                </div>\n",
        "\n",
        "                <div style=\"\n",
        "                    padding:15px;\n",
        "                    background:#f8f9fa;\n",
        "                    border-radius:8px;\n",
        "                    min-width:100px;\n",
        "                \">\n",
        "\n",
        "                    <strong>\n",
        "                        {safe_html(\n",
        "                            project[\"score\"]\n",
        "                            or \"-\"\n",
        "                        )}\n",
        "                    </strong>\n",
        "\n",
        "                    <br>\n",
        "\n",
        "                    Score\n",
        "\n",
        "                </div>\n",
        "\n",
        "                <div style=\"\n",
        "                    padding:15px;\n",
        "                    background:#f8f9fa;\n",
        "                    border-radius:8px;\n",
        "                    min-width:100px;\n",
        "                \">\n",
        "\n",
        "                    <strong>\n",
        "                        {safe_html(\n",
        "                            project[\"rank\"]\n",
        "                            or \"-\"\n",
        "                        )}\n",
        "                    </strong>\n",
        "\n",
        "                    <br>\n",
        "\n",
        "                    Rank\n",
        "\n",
        "                </div>\n",
        "\n",
        "                <div style=\"\n",
        "                    padding:15px;\n",
        "                    background:#f8f9fa;\n",
        "                    border-radius:8px;\n",
        "                    min-width:100px;\n",
        "                \">\n",
        "\n",
        "                    <strong>\n",
        "                        {safe_html(\n",
        "                            project[\"win_rate\"]\n",
        "                            or \"-\"\n",
        "                        )}\n",
        "                    </strong>\n",
        "\n",
        "                    <br>\n",
        "\n",
        "                    Win Rate\n",
        "\n",
        "                </div>\n",
        "\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                🤖 AI Summary\n",
        "            </h3>\n",
        "\n",
        "            <div style=\"\n",
        "                padding:18px;\n",
        "                background:#f8f9fa;\n",
        "                border-radius:8px;\n",
        "                line-height:1.7;\n",
        "            \">\n",
        "\n",
        "                {safe_html(\n",
        "                    analysis[\"summary\"]\n",
        "                )}\n",
        "\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                📈 Achievement\n",
        "            </h3>\n",
        "\n",
        "            <p style=\"\n",
        "                line-height:1.6;\n",
        "            \">\n",
        "\n",
        "                {safe_html(\n",
        "                    analysis[\"achievement\"]\n",
        "                    or \"No specific achievement recorded.\"\n",
        "                )}\n",
        "\n",
        "            </p>\n",
        "\n",
        "            <h3>\n",
        "                ⚠️ Risk / Issue\n",
        "            </h3>\n",
        "\n",
        "            <p style=\"\n",
        "                line-height:1.6;\n",
        "            \">\n",
        "\n",
        "                {safe_html(\n",
        "                    analysis[\"risk\"]\n",
        "                    or \"No major risk identified.\"\n",
        "                )}\n",
        "\n",
        "            </p>\n",
        "\n",
        "            {blockers_section}\n",
        "\n",
        "            <h3>\n",
        "                💡 AI Recommendation\n",
        "            </h3>\n",
        "\n",
        "            <div style=\"\n",
        "                padding:18px;\n",
        "                background:#f8f9fa;\n",
        "                border-left:4px solid #555;\n",
        "                line-height:1.7;\n",
        "            \">\n",
        "\n",
        "                {safe_html(\n",
        "                    analysis[\"recommendation\"]\n",
        "                )}\n",
        "\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                🚀 Next Actions\n",
        "            </h3>\n",
        "\n",
        "            <ol>\n",
        "                {actions_html}\n",
        "            </ol>\n",
        "\n",
        "            <hr style=\"\n",
        "                margin-top:30px;\n",
        "            \">\n",
        "\n",
        "            <p style=\"\n",
        "                color:#777;\n",
        "                font-size:13px;\n",
        "            \">\n",
        "                Generated automatically by\n",
        "                <strong>\n",
        "                    AI STEM Automation Hub\n",
        "                </strong>.\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "\n",
        "    </body>\n",
        "\n",
        "    </html>\n",
        "    \"\"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEXT EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_text_email(\n",
        "    project: dict[str, Any],\n",
        "    analysis: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate plain-text update.\"\"\"\n",
        "\n",
        "    lines = [\n",
        "\n",
        "        \"🏆 AI COMPETITION UPDATE\",\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        f\"Project: {project['name']}\",\n",
        "\n",
        "        f\"Type: {project['type']}\",\n",
        "\n",
        "        f\"Status: {project['status']}\",\n",
        "\n",
        "        f\"Version: {project['version'] or '-'}\",\n",
        "\n",
        "        f\"Score: {project['score'] or '-'}\",\n",
        "\n",
        "        f\"Rank: {project['rank'] or '-'}\",\n",
        "\n",
        "        f\"Win Rate: {project['win_rate'] or '-'}\",\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"AI SUMMARY\",\n",
        "\n",
        "        \"==========\",\n",
        "\n",
        "        analysis[\"summary\"],\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"ACHIEVEMENT\",\n",
        "\n",
        "        \"===========\",\n",
        "\n",
        "        (\n",
        "            analysis[\"achievement\"]\n",
        "            or \"No specific achievement recorded.\"\n",
        "        ),\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"RISK / ISSUE\",\n",
        "\n",
        "        \"===========\",\n",
        "\n",
        "        (\n",
        "            analysis[\"risk\"]\n",
        "            or \"No major risk identified.\"\n",
        "        ),\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"AI RECOMMENDATION\",\n",
        "\n",
        "        \"=================\",\n",
        "\n",
        "        analysis[\"recommendation\"],\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"NEXT ACTIONS\",\n",
        "\n",
        "        \"============\",\n",
        "\n",
        "    ]\n",
        "\n",
        "    for index, action in enumerate(\n",
        "        analysis[\"next_actions\"],\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        lines.append(\n",
        "            f\"{index}. {action}\"\n",
        "        )\n",
        "\n",
        "    if project[\"blockers\"]:\n",
        "\n",
        "        lines.extend(\n",
        "            [\n",
        "                \"\",\n",
        "                \"BLOCKERS\",\n",
        "                \"========\",\n",
        "            ]\n",
        "        )\n",
        "\n",
        "        for blocker in project[\n",
        "            \"blockers\"\n",
        "        ]:\n",
        "\n",
        "            lines.append(\n",
        "                f\"- {blocker}\"\n",
        "            )\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SEND EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_competition_email(\n",
        "    project: dict[str, Any],\n",
        "    analysis: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"Send competition update using Gmail SMTP.\"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gmail import (\n",
        "            send_email,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gmail.py before \"\n",
        "            \"sending competition updates.\"\n",
        "        ) from exc\n",
        "\n",
        "    subject = (\n",
        "        \"🏆 AI Competition Update - \"\n",
        "        f\"{project['name']}\"\n",
        "    )\n",
        "\n",
        "    html_body = generate_html_email(\n",
        "        project,\n",
        "        analysis,\n",
        "    )\n",
        "\n",
        "    text_body = generate_text_email(\n",
        "        project,\n",
        "        analysis,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        send_email(\n",
        "            subject=subject,\n",
        "            html_body=html_body,\n",
        "            text_body=text_body,\n",
        "            email_type=\"competition_update\",\n",
        "        )\n",
        "\n",
        "        logger.info(\n",
        "            \"Competition update email sent.\"\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Competition email failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DUPLICATE CHECK\n",
        "# =========================================================\n",
        "\n",
        "def update_already_sent(\n",
        "    project: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"\n",
        "    Prevent sending the exact same update twice.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        return database.competition_update_exists(\n",
        "            project_name=project[\"name\"],\n",
        "            version=project[\"version\"],\n",
        "            score=project[\"score\"],\n",
        "            status=project[\"status\"],\n",
        "        )\n",
        "\n",
        "    except AttributeError:\n",
        "\n",
        "        logger.warning(\n",
        "            \"competition_update_exists() \"\n",
        "            \"not implemented in database.py.\"\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RUN AGENT\n",
        "# =========================================================\n",
        "\n",
        "def run_competition_agent(\n",
        "    project_name: str = DEFAULT_PROJECT_NAME,\n",
        "    force: bool = False,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"Run the Competition Update Agent.\"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting Competition Update Agent.\"\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 1. Get latest project status\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    project = get_project_status(\n",
        "        project_name\n",
        "    )\n",
        "\n",
        "    project = normalize_status(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 2. Check duplicate\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if (\n",
        "        not force\n",
        "        and update_already_sent(\n",
        "            project\n",
        "        )\n",
        "    ):\n",
        "\n",
        "        logger.info(\n",
        "            \"No new competition update.\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"success\": False,\n",
        "            \"email_sent\": False,\n",
        "            \"message\": (\n",
        "                \"No new project status \"\n",
        "                \"to report.\"\n",
        "            ),\n",
        "            \"project\": project,\n",
        "        }\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 3. Generate AI analysis\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    analysis = generate_ai_update(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 4. Save\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    update_id = save_competition_update(\n",
        "        project,\n",
        "        analysis,\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 5. Send email\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    email_sent = send_competition_email(\n",
        "        project,\n",
        "        analysis,\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 6. Mark email sent\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if email_sent:\n",
        "\n",
        "        try:\n",
        "\n",
        "            database.mark_competition_update_sent(\n",
        "                update_id\n",
        "            )\n",
        "\n",
        "        except AttributeError:\n",
        "\n",
        "            logger.warning(\n",
        "                \"mark_competition_update_sent() \"\n",
        "                \"not implemented.\"\n",
        "            )\n",
        "\n",
        "    logger.info(\n",
        "        \"Competition Update Agent completed.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"success\": True,\n",
        "        \"update_id\": update_id,\n",
        "        \"email_sent\": email_sent,\n",
        "        \"project\": project,\n",
        "        \"analysis\": analysis,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    result = run_competition_agent()\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 65)\n",
        "    print(\"AI COMPETITION UPDATE\")\n",
        "    print(\"=\" * 65)\n",
        "\n",
        "    print(\n",
        "        f\"Success    : \"\n",
        "        f\"{result.get('success')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Email sent : \"\n",
        "        f\"{result.get('email_sent', False)}\"\n",
        "    )\n",
        "\n",
        "    project = result.get(\n",
        "        \"project\",\n",
        "        {},\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Project    : \"\n",
        "        f\"{project.get('name', '-')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Status     : \"\n",
        "        f\"{project.get('status', '-')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Version    : \"\n",
        "        f\"{project.get('version', '-')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Score      : \"\n",
        "        f\"{project.get('score', '-')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Rank       : \"\n",
        "        f\"{project.get('rank', '-')}\"\n",
        "    )\n",
        "\n",
        "    analysis = result.get(\n",
        "        \"analysis\",\n",
        "        {},\n",
        "    )\n",
        "\n",
        "    if analysis:\n",
        "\n",
        "        print()\n",
        "        print(\n",
        "            \"AI SUMMARY:\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            analysis.get(\n",
        "                \"summary\",\n",
        "                \"\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "        print()\n",
        "        print(\n",
        "            \"RECOMMENDATION:\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            analysis.get(\n",
        "                \"recommendation\",\n",
        "                \"\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "    print(\"=\" * 65)"
      ],
      "metadata": {
        "id": "uO3vWoXtwACx"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}