{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMQL+X+ZltYdCX40LLP+OC5",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/config.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "config.py\n",
        "\n",
        "Central configuration for:\n",
        "- Gemini API\n",
        "- Gmail SMTP\n",
        "- News collection\n",
        "- Agent scheduling\n",
        "- Project settings\n",
        "\"\"\"\n",
        "\n",
        "import os\n",
        "from pathlib import Path\n",
        "\n",
        "from dotenv import load_dotenv\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# BASE DIRECTORIES\n",
        "# =========================================================\n",
        "\n",
        "BASE_DIR = Path(__file__).resolve().parent\n",
        "\n",
        "DATA_DIR = BASE_DIR / \"data\"\n",
        "HISTORY_DIR = DATA_DIR / \"history\"\n",
        "TEMPLATES_DIR = BASE_DIR / \"templates\"\n",
        "LOG_DIR = BASE_DIR / \"logs\"\n",
        "\n",
        "\n",
        "# Create directories automatically\n",
        "DATA_DIR.mkdir(exist_ok=True)\n",
        "HISTORY_DIR.mkdir(exist_ok=True)\n",
        "TEMPLATES_DIR.mkdir(exist_ok=True)\n",
        "LOG_DIR.mkdir(exist_ok=True)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ENVIRONMENT VARIABLES\n",
        "# =========================================================\n",
        "\n",
        "ENV_FILE = BASE_DIR / \".env\"\n",
        "\n",
        "load_dotenv(ENV_FILE)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "GEMINI_API_KEY = os.getenv(\"GEMINI_API_KEY\", \"\")\n",
        "\n",
        "GEMINI_MODEL = os.getenv(\n",
        "    \"GEMINI_MODEL\",\n",
        "    \"gemini-2.5-flash\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GMAIL SMTP CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "GMAIL_ADDRESS = os.getenv(\n",
        "    \"GMAIL_ADDRESS\",\n",
        "    \"\"\n",
        ")\n",
        "\n",
        "GMAIL_APP_PASSWORD = os.getenv(\n",
        "    \"GMAIL_APP_PASSWORD\",\n",
        "    \"\"\n",
        ")\n",
        "\n",
        "RECIPIENT_EMAIL = os.getenv(\n",
        "    \"RECIPIENT_EMAIL\",\n",
        "    \"\"\n",
        ")\n",
        "\n",
        "SMTP_SERVER = \"smtp.gmail.com\"\n",
        "\n",
        "SMTP_PORT = 587\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# EMAIL SETTINGS\n",
        "# =========================================================\n",
        "\n",
        "EMAIL_SENDER_NAME = os.getenv(\n",
        "    \"EMAIL_SENDER_NAME\",\n",
        "    \"AI STEM Innovation\"\n",
        ")\n",
        "\n",
        "EMAIL_SUBJECT_PREFIX = os.getenv(\n",
        "    \"EMAIL_SUBJECT_PREFIX\",\n",
        "    \"AI STEM Automation\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NEWS CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "NEWS_LIMIT = int(\n",
        "    os.getenv(\"NEWS_LIMIT\", \"5\")\n",
        ")\n",
        "\n",
        "ROBOTICS_NEWS_LIMIT = int(\n",
        "    os.getenv(\"ROBOTICS_NEWS_LIMIT\", \"5\")\n",
        ")\n",
        "\n",
        "NEWS_LOOKBACK_HOURS = int(\n",
        "    os.getenv(\"NEWS_LOOKBACK_HOURS\", \"24\")\n",
        ")\n",
        "\n",
        "\n",
        "# News categories\n",
        "AI_NEWS_TOPICS = [\n",
        "    \"Artificial Intelligence\",\n",
        "    \"Generative AI\",\n",
        "    \"Machine Learning\",\n",
        "    \"Deep Learning\",\n",
        "    \"Computer Vision\",\n",
        "    \"Large Language Models\",\n",
        "    \"AI Agents\",\n",
        "]\n",
        "\n",
        "\n",
        "ROBOTICS_NEWS_TOPICS = [\n",
        "    \"Robotics\",\n",
        "    \"Humanoid Robots\",\n",
        "    \"Industrial Robotics\",\n",
        "    \"Service Robots\",\n",
        "    \"Autonomous Robots\",\n",
        "    \"Robot Vision\",\n",
        "    \"Drone Technology\",\n",
        "    \"ROS2\",\n",
        "]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# STEM CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "STEM_GRADES = [\n",
        "    3,\n",
        "    4,\n",
        "    5,\n",
        "    6,\n",
        "    7,\n",
        "    8,\n",
        "    9,\n",
        "    10,\n",
        "]\n",
        "\n",
        "\n",
        "STEM_DOMAINS = [\n",
        "    \"Electronics\",\n",
        "    \"Arduino\",\n",
        "    \"ESP32\",\n",
        "    \"Robotics\",\n",
        "    \"IoT\",\n",
        "    \"Artificial Intelligence\",\n",
        "    \"Machine Learning\",\n",
        "    \"Computer Vision\",\n",
        "    \"Drones\",\n",
        "    \"3D Printing\",\n",
        "    \"Programming\",\n",
        "    \"Sensors\",\n",
        "    \"Automation\",\n",
        "]\n",
        "\n",
        "\n",
        "PROJECT_DIFFICULTIES = [\n",
        "    \"Beginner\",\n",
        "    \"Intermediate\",\n",
        "    \"Advanced\",\n",
        "]\n",
        "\n",
        "\n",
        "PROJECT_BUDGET_MIN = 300\n",
        "\n",
        "PROJECT_BUDGET_MAX = 3000\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SCHEDULER\n",
        "# =========================================================\n",
        "\n",
        "TIMEZONE = os.getenv(\n",
        "    \"TIMEZONE\",\n",
        "    \"Asia/Kolkata\"\n",
        ")\n",
        "\n",
        "\n",
        "# Daily schedules\n",
        "NEWS_TIME = os.getenv(\n",
        "    \"NEWS_TIME\",\n",
        "    \"08:00\"\n",
        ")\n",
        "\n",
        "STEM_TIP_TIME = os.getenv(\n",
        "    \"STEM_TIP_TIME\",\n",
        "    \"08:30\"\n",
        ")\n",
        "\n",
        "PROJECT_TIME = os.getenv(\n",
        "    \"PROJECT_TIME\",\n",
        "    \"09:00\"\n",
        ")\n",
        "\n",
        "CLASS_UPDATE_TIME = os.getenv(\n",
        "    \"CLASS_UPDATE_TIME\",\n",
        "    \"17:00\"\n",
        ")\n",
        "\n",
        "WEEKLY_REPORT_TIME = os.getenv(\n",
        "    \"WEEKLY_REPORT_TIME\",\n",
        "    \"18:00\"\n",
        ")\n",
        "\n",
        "\n",
        "# Day for weekly report\n",
        "WEEKLY_REPORT_DAY = os.getenv(\n",
        "    \"WEEKLY_REPORT_DAY\",\n",
        "    \"saturday\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATABASE\n",
        "# =========================================================\n",
        "\n",
        "DATABASE_FILE = DATA_DIR / \"database.db\"\n",
        "\n",
        "NEWS_HISTORY_FILE = HISTORY_DIR / \"sent_news.json\"\n",
        "\n",
        "STEM_TIP_HISTORY_FILE = HISTORY_DIR / \"stem_tips.json\"\n",
        "\n",
        "PROJECT_HISTORY_FILE = HISTORY_DIR / \"projects.json\"\n",
        "\n",
        "CLASS_HISTORY_FILE = HISTORY_DIR / \"class_updates.json\"\n",
        "\n",
        "COMPETITION_HISTORY_FILE = HISTORY_DIR / \"competition_updates.json\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMPETITION CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "KAGGRICULTURE_REPOSITORY = os.getenv(\n",
        "    \"KAGGRICULTURE_REPOSITORY\",\n",
        "    \"\"\n",
        ")\n",
        "\n",
        "GITHUB_TOKEN = os.getenv(\n",
        "    \"GITHUB_TOKEN\",\n",
        "    \"\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# AI GENERATION SETTINGS\n",
        "# =========================================================\n",
        "\n",
        "AI_TEMPERATURE = float(\n",
        "    os.getenv(\"AI_TEMPERATURE\", \"0.4\")\n",
        ")\n",
        "\n",
        "MAX_OUTPUT_TOKENS = int(\n",
        "    os.getenv(\"MAX_OUTPUT_TOKENS\", \"2048\")\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# APPLICATION SETTINGS\n",
        "# =========================================================\n",
        "\n",
        "APP_NAME = \"AI STEM Automation Hub\"\n",
        "\n",
        "APP_VERSION = \"1.0.0\"\n",
        "\n",
        "DEBUG = os.getenv(\n",
        "    \"DEBUG\",\n",
        "    \"false\"\n",
        ").lower() == \"true\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# VALIDATION\n",
        "# =========================================================\n",
        "\n",
        "def validate_config():\n",
        "    \"\"\"\n",
        "    Check whether required configuration values exist.\n",
        "    \"\"\"\n",
        "\n",
        "    missing = []\n",
        "\n",
        "    if not GEMINI_API_KEY:\n",
        "        missing.append(\"GEMINI_API_KEY\")\n",
        "\n",
        "    if not GMAIL_ADDRESS:\n",
        "        missing.append(\"GMAIL_ADDRESS\")\n",
        "\n",
        "    if not GMAIL_APP_PASSWORD:\n",
        "        missing.append(\"GMAIL_APP_PASSWORD\")\n",
        "\n",
        "    if not RECIPIENT_EMAIL:\n",
        "        missing.append(\"RECIPIENT_EMAIL\")\n",
        "\n",
        "    if missing:\n",
        "        raise ValueError(\n",
        "            \"Missing required configuration: \"\n",
        "            + \", \".join(missing)\n",
        "        )\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONFIGURATION SUMMARY\n",
        "# =========================================================\n",
        "\n",
        "def show_config():\n",
        "    \"\"\"\n",
        "    Display safe configuration information.\n",
        "\n",
        "    Secrets are intentionally hidden.\n",
        "    \"\"\"\n",
        "\n",
        "    print(\"=\" * 60)\n",
        "    print(APP_NAME)\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    print(f\"Version       : {APP_VERSION}\")\n",
        "    print(f\"Gemini Model  : {GEMINI_MODEL}\")\n",
        "    print(f\"Email         : {GMAIL_ADDRESS or 'Not configured'}\")\n",
        "    print(f\"Recipient     : {RECIPIENT_EMAIL or 'Not configured'}\")\n",
        "    print(f\"SMTP Server   : {SMTP_SERVER}\")\n",
        "    print(f\"SMTP Port     : {SMTP_PORT}\")\n",
        "    print(f\"Timezone      : {TIMEZONE}\")\n",
        "\n",
        "    print()\n",
        "    print(\"Schedules\")\n",
        "    print(\"-\" * 60)\n",
        "    print(f\"AI News       : {NEWS_TIME}\")\n",
        "    print(f\"STEM Tip      : {STEM_TIP_TIME}\")\n",
        "    print(f\"Project       : {PROJECT_TIME}\")\n",
        "    print(f\"Class Update  : {CLASS_UPDATE_TIME}\")\n",
        "    print(f\"Weekly Report : {WEEKLY_REPORT_DAY} {WEEKLY_REPORT_TIME}\")\n",
        "\n",
        "    print()\n",
        "    print(\"News\")\n",
        "    print(\"-\" * 60)\n",
        "    print(f\"AI News Limit       : {NEWS_LIMIT}\")\n",
        "    print(f\"Robotics News Limit : {ROBOTICS_NEWS_LIMIT}\")\n",
        "    print(f\"Lookback Hours      : {NEWS_LOOKBACK_HOURS}\")\n",
        "\n",
        "    print()\n",
        "    print(\"STEM\")\n",
        "    print(\"-\" * 60)\n",
        "    print(f\"Grades       : {STEM_GRADES}\")\n",
        "    print(f\"Domains      : {len(STEM_DOMAINS)}\")\n",
        "    print(f\"Project Cost : ₹{PROJECT_BUDGET_MIN} - ₹{PROJECT_BUDGET_MAX}\")\n",
        "\n",
        "    print(\"=\" * 60)"
      ],
      "metadata": {
        "id": "8_1aJyi4o6FC"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}