{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMRzxc0AovJwHCFZa6moMS4",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/database.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "database.py\n",
        "\n",
        "SQLite database manager for:\n",
        "- AI/Robotics news\n",
        "- STEM class updates\n",
        "- Daily STEM tips\n",
        "- Project ideas\n",
        "- Weekly reports\n",
        "- Competition updates\n",
        "\"\"\"\n",
        "\n",
        "import sqlite3\n",
        "from datetime import datetime, timedelta\n",
        "from pathlib import Path\n",
        "from typing import Any, Optional\n",
        "\n",
        "from config import DATABASE_FILE\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATABASE CONNECTION\n",
        "# =========================================================\n",
        "\n",
        "def get_connection() -> sqlite3.Connection:\n",
        "    \"\"\"Create and return a SQLite database connection.\"\"\"\n",
        "\n",
        "    connection = sqlite3.connect(\n",
        "        str(DATABASE_FILE),\n",
        "        timeout=30,\n",
        "    )\n",
        "\n",
        "    connection.row_factory = sqlite3.Row\n",
        "\n",
        "    return connection\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# INITIALIZE DATABASE\n",
        "# =========================================================\n",
        "\n",
        "def initialize_database() -> None:\n",
        "    \"\"\"Create all required database tables.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.cursor()\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # News\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS news (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                title TEXT NOT NULL,\n",
        "                url TEXT UNIQUE,\n",
        "                source TEXT,\n",
        "                category TEXT,\n",
        "                summary TEXT,\n",
        "                published_at TEXT,\n",
        "                created_at TEXT NOT NULL\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # STEM Tips\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS stem_tips (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                title TEXT NOT NULL,\n",
        "                topic TEXT,\n",
        "                grade TEXT,\n",
        "                difficulty TEXT,\n",
        "                content TEXT NOT NULL,\n",
        "                created_at TEXT NOT NULL,\n",
        "                sent INTEGER DEFAULT 0\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # Project Ideas\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS projects (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                title TEXT NOT NULL,\n",
        "                domain TEXT,\n",
        "                grade TEXT,\n",
        "                difficulty TEXT,\n",
        "                budget TEXT,\n",
        "                components TEXT,\n",
        "                description TEXT,\n",
        "                circuit_concept TEXT,\n",
        "                code_outline TEXT,\n",
        "                created_at TEXT NOT NULL,\n",
        "                sent INTEGER DEFAULT 0\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # Class Updates\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS class_updates (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                grade TEXT NOT NULL,\n",
        "                section TEXT,\n",
        "                topic TEXT,\n",
        "                activity TEXT,\n",
        "                skills TEXT,\n",
        "                notes TEXT,\n",
        "                session_date TEXT NOT NULL,\n",
        "                created_at TEXT NOT NULL,\n",
        "                sent INTEGER DEFAULT 0\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # Weekly Reports\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS weekly_reports (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                week_start TEXT NOT NULL,\n",
        "                week_end TEXT NOT NULL,\n",
        "                summary TEXT NOT NULL,\n",
        "                created_at TEXT NOT NULL,\n",
        "                sent INTEGER DEFAULT 0\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # Competition Updates\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS competition_updates (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                competition TEXT NOT NULL,\n",
        "                version TEXT,\n",
        "                status TEXT,\n",
        "                score TEXT,\n",
        "                summary TEXT,\n",
        "                recommendation TEXT,\n",
        "                created_at TEXT NOT NULL,\n",
        "                sent INTEGER DEFAULT 0\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        # -------------------------------------------------\n",
        "        # Email Log\n",
        "        # -------------------------------------------------\n",
        "\n",
        "        cursor.execute(\n",
        "            \"\"\"\n",
        "            CREATE TABLE IF NOT EXISTS email_log (\n",
        "                id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
        "                email_type TEXT NOT NULL,\n",
        "                subject TEXT NOT NULL,\n",
        "                recipient TEXT NOT NULL,\n",
        "                sent_at TEXT NOT NULL,\n",
        "                status TEXT NOT NULL,\n",
        "                error TEXT\n",
        "            )\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPER\n",
        "# =========================================================\n",
        "\n",
        "def now() -> str:\n",
        "    \"\"\"Return current timestamp.\"\"\"\n",
        "\n",
        "    return datetime.now().isoformat(timespec=\"seconds\")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NEWS\n",
        "# =========================================================\n",
        "\n",
        "def news_exists(url: str) -> bool:\n",
        "    \"\"\"Check whether a news article URL already exists.\"\"\"\n",
        "\n",
        "    if not url:\n",
        "        return False\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        row = connection.execute(\n",
        "            \"SELECT id FROM news WHERE url = ? LIMIT 1\",\n",
        "            (url,),\n",
        "        ).fetchone()\n",
        "\n",
        "    return row is not None\n",
        "\n",
        "\n",
        "def news_title_exists(title: str) -> bool:\n",
        "    \"\"\"Check whether a news title already exists.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        row = connection.execute(\n",
        "            \"\"\"\n",
        "            SELECT id\n",
        "            FROM news\n",
        "            WHERE lower(title) = lower(?)\n",
        "            LIMIT 1\n",
        "            \"\"\",\n",
        "            (title,),\n",
        "        ).fetchone()\n",
        "\n",
        "    return row is not None\n",
        "\n",
        "\n",
        "def add_news(\n",
        "    title: str,\n",
        "    url: str = \"\",\n",
        "    source: str = \"\",\n",
        "    category: str = \"\",\n",
        "    summary: str = \"\",\n",
        "    published_at: str = \"\",\n",
        ") -> int:\n",
        "    \"\"\"Save a news article.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT OR IGNORE INTO news\n",
        "            (\n",
        "                title,\n",
        "                url,\n",
        "                source,\n",
        "                category,\n",
        "                summary,\n",
        "                published_at,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                title,\n",
        "                url,\n",
        "                source,\n",
        "                category,\n",
        "                summary,\n",
        "                published_at,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def get_recent_news(hours: int = 24) -> list[dict]:\n",
        "    \"\"\"Return recently stored news.\"\"\"\n",
        "\n",
        "    cutoff = (\n",
        "        datetime.now() - timedelta(hours=hours)\n",
        "    ).isoformat(timespec=\"seconds\")\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        rows = connection.execute(\n",
        "            \"\"\"\n",
        "            SELECT *\n",
        "            FROM news\n",
        "            WHERE created_at >= ?\n",
        "            ORDER BY created_at DESC\n",
        "            \"\"\",\n",
        "            (cutoff,),\n",
        "        ).fetchall()\n",
        "\n",
        "    return [dict(row) for row in rows]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# STEM TIPS\n",
        "# =========================================================\n",
        "\n",
        "def add_stem_tip(\n",
        "    title: str,\n",
        "    topic: str,\n",
        "    grade: str,\n",
        "    difficulty: str,\n",
        "    content: str,\n",
        ") -> int:\n",
        "    \"\"\"Save a STEM tip.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO stem_tips\n",
        "            (\n",
        "                title,\n",
        "                topic,\n",
        "                grade,\n",
        "                difficulty,\n",
        "                content,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                title,\n",
        "                topic,\n",
        "                grade,\n",
        "                difficulty,\n",
        "                content,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def stem_tip_exists(title: str) -> bool:\n",
        "    \"\"\"Check whether a STEM tip already exists.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        row = connection.execute(\n",
        "            \"\"\"\n",
        "            SELECT id\n",
        "            FROM stem_tips\n",
        "            WHERE lower(title) = lower(?)\n",
        "            LIMIT 1\n",
        "            \"\"\",\n",
        "            (title,),\n",
        "        ).fetchone()\n",
        "\n",
        "    return row is not None\n",
        "\n",
        "\n",
        "def mark_stem_tip_sent(tip_id: int) -> None:\n",
        "    \"\"\"Mark a STEM tip as sent.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        connection.execute(\n",
        "            \"\"\"\n",
        "            UPDATE stem_tips\n",
        "            SET sent = 1\n",
        "            WHERE id = ?\n",
        "            \"\"\",\n",
        "            (tip_id,),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PROJECTS\n",
        "# =========================================================\n",
        "\n",
        "def add_project(\n",
        "    title: str,\n",
        "    domain: str,\n",
        "    grade: str,\n",
        "    difficulty: str,\n",
        "    budget: str,\n",
        "    components: str,\n",
        "    description: str,\n",
        "    circuit_concept: str,\n",
        "    code_outline: str,\n",
        ") -> int:\n",
        "    \"\"\"Save a project idea.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO projects\n",
        "            (\n",
        "                title,\n",
        "                domain,\n",
        "                grade,\n",
        "                difficulty,\n",
        "                budget,\n",
        "                components,\n",
        "                description,\n",
        "                circuit_concept,\n",
        "                code_outline,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                title,\n",
        "                domain,\n",
        "                grade,\n",
        "                difficulty,\n",
        "                budget,\n",
        "                components,\n",
        "                description,\n",
        "                circuit_concept,\n",
        "                code_outline,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def project_exists(title: str) -> bool:\n",
        "    \"\"\"Check whether a project already exists.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        row = connection.execute(\n",
        "            \"\"\"\n",
        "            SELECT id\n",
        "            FROM projects\n",
        "            WHERE lower(title) = lower(?)\n",
        "            LIMIT 1\n",
        "            \"\"\",\n",
        "            (title,),\n",
        "        ).fetchone()\n",
        "\n",
        "    return row is not None\n",
        "\n",
        "\n",
        "def mark_project_sent(project_id: int) -> None:\n",
        "    \"\"\"Mark project as sent.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        connection.execute(\n",
        "            \"\"\"\n",
        "            UPDATE projects\n",
        "            SET sent = 1\n",
        "            WHERE id = ?\n",
        "            \"\"\",\n",
        "            (project_id,),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CLASS UPDATES\n",
        "# =========================================================\n",
        "\n",
        "def add_class_update(\n",
        "    grade: str,\n",
        "    section: str,\n",
        "    topic: str,\n",
        "    activity: str,\n",
        "    skills: str = \"\",\n",
        "    notes: str = \"\",\n",
        "    session_date: Optional[str] = None,\n",
        ") -> int:\n",
        "    \"\"\"Save a STEM class session.\"\"\"\n",
        "\n",
        "    if session_date is None:\n",
        "        session_date = datetime.now().strftime(\"%Y-%m-%d\")\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO class_updates\n",
        "            (\n",
        "                grade,\n",
        "                section,\n",
        "                topic,\n",
        "                activity,\n",
        "                skills,\n",
        "                notes,\n",
        "                session_date,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                grade,\n",
        "                section,\n",
        "                topic,\n",
        "                activity,\n",
        "                skills,\n",
        "                notes,\n",
        "                session_date,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def get_class_updates(\n",
        "    start_date: str,\n",
        "    end_date: str,\n",
        ") -> list[dict]:\n",
        "    \"\"\"Get class updates within a date range.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        rows = connection.execute(\n",
        "            \"\"\"\n",
        "            SELECT *\n",
        "            FROM class_updates\n",
        "            WHERE session_date BETWEEN ? AND ?\n",
        "            ORDER BY session_date ASC, grade ASC\n",
        "            \"\"\",\n",
        "            (start_date, end_date),\n",
        "        ).fetchall()\n",
        "\n",
        "    return [dict(row) for row in rows]\n",
        "\n",
        "\n",
        "def mark_class_update_sent(update_id: int) -> None:\n",
        "    \"\"\"Mark class update as sent.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        connection.execute(\n",
        "            \"\"\"\n",
        "            UPDATE class_updates\n",
        "            SET sent = 1\n",
        "            WHERE id = ?\n",
        "            \"\"\",\n",
        "            (update_id,),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# WEEKLY REPORTS\n",
        "# =========================================================\n",
        "\n",
        "def add_weekly_report(\n",
        "    week_start: str,\n",
        "    week_end: str,\n",
        "    summary: str,\n",
        ") -> int:\n",
        "    \"\"\"Save weekly report.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO weekly_reports\n",
        "            (\n",
        "                week_start,\n",
        "                week_end,\n",
        "                summary,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                week_start,\n",
        "                week_end,\n",
        "                summary,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def mark_weekly_report_sent(report_id: int) -> None:\n",
        "    \"\"\"Mark weekly report as sent.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        connection.execute(\n",
        "            \"\"\"\n",
        "            UPDATE weekly_reports\n",
        "            SET sent = 1\n",
        "            WHERE id = ?\n",
        "            \"\"\",\n",
        "            (report_id,),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMPETITION\n",
        "# =========================================================\n",
        "\n",
        "def add_competition_update(\n",
        "    competition: str,\n",
        "    version: str = \"\",\n",
        "    status: str = \"\",\n",
        "    score: str = \"\",\n",
        "    summary: str = \"\",\n",
        "    recommendation: str = \"\",\n",
        ") -> int:\n",
        "    \"\"\"Save competition progress.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO competition_updates\n",
        "            (\n",
        "                competition,\n",
        "                version,\n",
        "                status,\n",
        "                score,\n",
        "                summary,\n",
        "                recommendation,\n",
        "                created_at\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                competition,\n",
        "                version,\n",
        "                status,\n",
        "                score,\n",
        "                summary,\n",
        "                recommendation,\n",
        "                now(),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "def mark_competition_update_sent(update_id: int) -> None:\n",
        "    \"\"\"Mark competition update as sent.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        connection.execute(\n",
        "            \"\"\"\n",
        "            UPDATE competition_updates\n",
        "            SET sent = 1\n",
        "            WHERE id = ?\n",
        "            \"\"\",\n",
        "            (update_id,),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# EMAIL LOG\n",
        "# =========================================================\n",
        "\n",
        "def log_email(\n",
        "    email_type: str,\n",
        "    subject: str,\n",
        "    recipient: str,\n",
        "    status: str,\n",
        "    error: str = \"\",\n",
        ") -> int:\n",
        "    \"\"\"Store email delivery result.\"\"\"\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        cursor = connection.execute(\n",
        "            \"\"\"\n",
        "            INSERT INTO email_log\n",
        "            (\n",
        "                email_type,\n",
        "                subject,\n",
        "                recipient,\n",
        "                sent_at,\n",
        "                status,\n",
        "                error\n",
        "            )\n",
        "            VALUES (?, ?, ?, ?, ?, ?)\n",
        "            \"\"\",\n",
        "            (\n",
        "                email_type,\n",
        "                subject,\n",
        "                recipient,\n",
        "                now(),\n",
        "                status,\n",
        "                error,\n",
        "            ),\n",
        "        )\n",
        "\n",
        "        connection.commit()\n",
        "\n",
        "        return cursor.lastrowid\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# STATISTICS\n",
        "# =========================================================\n",
        "\n",
        "def get_statistics() -> dict[str, int]:\n",
        "    \"\"\"Return database statistics.\"\"\"\n",
        "\n",
        "    tables = [\n",
        "        \"news\",\n",
        "        \"stem_tips\",\n",
        "        \"projects\",\n",
        "        \"class_updates\",\n",
        "        \"weekly_reports\",\n",
        "        \"competition_updates\",\n",
        "        \"email_log\",\n",
        "    ]\n",
        "\n",
        "    statistics: dict[str, int] = {}\n",
        "\n",
        "    with get_connection() as connection:\n",
        "\n",
        "        for table in tables:\n",
        "\n",
        "            row = connection.execute(\n",
        "                f\"SELECT COUNT(*) AS count FROM {table}\"\n",
        "            ).fetchone()\n",
        "\n",
        "            statistics[table] = row[\"count\"]\n",
        "\n",
        "    return statistics\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATABASE STATUS\n",
        "# =========================================================\n",
        "\n",
        "def show_database_status() -> None:\n",
        "    \"\"\"Display database information.\"\"\"\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"AI STEM AUTOMATION DATABASE\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    print(f\"Database: {DATABASE_FILE}\")\n",
        "\n",
        "    if not Path(DATABASE_FILE).exists():\n",
        "        print(\"Status  : Database will be created.\")\n",
        "    else:\n",
        "        print(\"Status  : Database exists.\")\n",
        "\n",
        "    print()\n",
        "\n",
        "    try:\n",
        "        initialize_database()\n",
        "\n",
        "        statistics = get_statistics()\n",
        "\n",
        "        for name, count in statistics.items():\n",
        "            print(f\"{name:25} : {count}\")\n",
        "\n",
        "    except Exception as exc:\n",
        "        print(f\"Database error: {exc}\")\n",
        "\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# AUTOMATIC INITIALIZATION\n",
        "# =========================================================\n",
        "\n",
        "initialize_database()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEST / COMMAND LINE\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    show_database_status()"
      ],
      "metadata": {
        "id": "lxrEhxJ3tPYm"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}