{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPixu6T02eMkY+Z92rXCHii",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/gemini.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "services/gemini.py\n",
        "\n",
        "Central Gemini AI service used by:\n",
        "\n",
        "- news_agent.py\n",
        "- class_agent.py\n",
        "- stem_tip_agent.py\n",
        "- project_agent.py\n",
        "- weekly_report_agent.py\n",
        "- competition_agent.py\n",
        "\n",
        "Requires:\n",
        "    GEMINI_API_KEY=your_api_key\n",
        "\n",
        "Install:\n",
        "    pip install google-genai\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import json\n",
        "import logging\n",
        "import os\n",
        "import re\n",
        "from typing import Any, Optional\n",
        "\n",
        "from google import genai\n",
        "from google.genai import types\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.Gemini\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "API_KEY = os.getenv(\n",
        "    \"GEMINI_API_KEY\"\n",
        ")\n",
        "\n",
        "MODEL_NAME = os.getenv(\n",
        "    \"GEMINI_MODEL\",\n",
        "    \"gemini-2.5-flash\",\n",
        ")\n",
        "\n",
        "if not API_KEY:\n",
        "\n",
        "    raise RuntimeError(\n",
        "        \"GEMINI_API_KEY environment variable \"\n",
        "        \"is not configured.\"\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI CLIENT\n",
        "# =========================================================\n",
        "\n",
        "client = genai.Client(\n",
        "    api_key=API_KEY\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GENERIC GENERATION\n",
        "# =========================================================\n",
        "\n",
        "def generate_text(\n",
        "    prompt: str,\n",
        "    temperature: float = 0.7,\n",
        "    max_output_tokens: int = 4096,\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Generate text using Gemini.\n",
        "    \"\"\"\n",
        "\n",
        "    if not prompt.strip():\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Gemini prompt cannot be empty.\"\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"Calling Gemini model: %s\",\n",
        "        MODEL_NAME,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        response = client.models.generate_content(\n",
        "            model=MODEL_NAME,\n",
        "            contents=prompt,\n",
        "            config=types.GenerateContentConfig(\n",
        "                temperature=temperature,\n",
        "                max_output_tokens=(\n",
        "                    max_output_tokens\n",
        "                ),\n",
        "            ),\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gemini API request failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        raise\n",
        "\n",
        "    text = getattr(\n",
        "        response,\n",
        "        \"text\",\n",
        "        None,\n",
        "    )\n",
        "\n",
        "    if not text:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"Gemini returned an empty response.\"\n",
        "        )\n",
        "\n",
        "    return text.strip()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# JSON EXTRACTION\n",
        "# =========================================================\n",
        "\n",
        "def extract_json(\n",
        "    text: str,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Extract JSON object from Gemini output.\n",
        "\n",
        "    Handles:\n",
        "        {...}\n",
        "\n",
        "    and:\n",
        "\n",
        "        ```json\n",
        "        {...}\n",
        "        ```\n",
        "    \"\"\"\n",
        "\n",
        "    text = text.strip()\n",
        "\n",
        "    # Remove markdown code fences.\n",
        "    text = re.sub(\n",
        "        r\"^```json\\s*\",\n",
        "        \"\",\n",
        "        text,\n",
        "        flags=re.IGNORECASE,\n",
        "    )\n",
        "\n",
        "    text = re.sub(\n",
        "        r\"^```\\s*\",\n",
        "        \"\",\n",
        "        text,\n",
        "    )\n",
        "\n",
        "    text = re.sub(\n",
        "        r\"\\s*```$\",\n",
        "        \"\",\n",
        "        text,\n",
        "    )\n",
        "\n",
        "    text = text.strip()\n",
        "\n",
        "    # Direct JSON.\n",
        "    try:\n",
        "\n",
        "        result = json.loads(\n",
        "            text\n",
        "        )\n",
        "\n",
        "        if isinstance(\n",
        "            result,\n",
        "            dict,\n",
        "        ):\n",
        "\n",
        "            return result\n",
        "\n",
        "    except json.JSONDecodeError:\n",
        "        pass\n",
        "\n",
        "    # Find first JSON object.\n",
        "    start = text.find(\"{\")\n",
        "    end = text.rfind(\"}\")\n",
        "\n",
        "    if (\n",
        "        start >= 0\n",
        "        and end > start\n",
        "    ):\n",
        "\n",
        "        candidate = text[\n",
        "            start:end + 1\n",
        "        ]\n",
        "\n",
        "        try:\n",
        "\n",
        "            result = json.loads(\n",
        "                candidate\n",
        "            )\n",
        "\n",
        "            if isinstance(\n",
        "                result,\n",
        "                dict,\n",
        "            ):\n",
        "\n",
        "                return result\n",
        "\n",
        "        except json.JSONDecodeError:\n",
        "            pass\n",
        "\n",
        "    raise ValueError(\n",
        "        \"Could not extract valid JSON \"\n",
        "        \"from Gemini response.\"\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# STRUCTURED GENERATION\n",
        "# =========================================================\n",
        "\n",
        "def generate_json(\n",
        "    prompt: str,\n",
        "    temperature: float = 0.7,\n",
        "    max_output_tokens: int = 4096,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate structured JSON using Gemini.\n",
        "    \"\"\"\n",
        "\n",
        "    response = client.models.generate_content(\n",
        "        model=MODEL_NAME,\n",
        "        contents=prompt,\n",
        "        config=types.GenerateContentConfig(\n",
        "            temperature=temperature,\n",
        "            max_output_tokens=max_output_tokens,\n",
        "            response_mime_type=\"application/json\",\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    text = getattr(\n",
        "        response,\n",
        "        \"text\",\n",
        "        None,\n",
        "    )\n",
        "\n",
        "    if not text:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"Gemini returned an empty JSON response.\"\n",
        "        )\n",
        "\n",
        "    return extract_json(\n",
        "        text\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DAILY STEM TIP\n",
        "# =========================================================\n",
        "\n",
        "def generate_stem_tip(\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        "    previous_titles: Optional[\n",
        "        list[str]\n",
        "    ] = None,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate one practical STEM activity.\n",
        "    \"\"\"\n",
        "\n",
        "    previous_titles = (\n",
        "        previous_titles or []\n",
        "    )\n",
        "\n",
        "    previous_text = \"\\n\".join(\n",
        "        f\"- {title}\"\n",
        "        for title in previous_titles\n",
        "    )\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are an expert STEM educator,\n",
        "electronics engineer and robotics trainer.\n",
        "\n",
        "Create ONE practical STEM activity.\n",
        "\n",
        "Target grade:\n",
        "{grade}\n",
        "\n",
        "Domain:\n",
        "{domain}\n",
        "\n",
        "Difficulty:\n",
        "{difficulty}\n",
        "\n",
        "Avoid these previously used titles:\n",
        "{previous_text}\n",
        "\n",
        "The activity should be:\n",
        "- practical\n",
        "- classroom-friendly\n",
        "- affordable\n",
        "- hands-on\n",
        "- technically correct\n",
        "- suitable for the target grade\n",
        "\n",
        "Return ONLY valid JSON.\n",
        "\n",
        "Required JSON structure:\n",
        "\n",
        "{{\n",
        "  \"title\": \"...\",\n",
        "  \"description\": \"...\",\n",
        "  \"grade\": \"{grade}\",\n",
        "  \"domain\": \"{domain}\",\n",
        "  \"difficulty\": \"{difficulty}\",\n",
        "  \"components\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"steps\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"concepts\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"challenge\": \"...\",\n",
        "  \"safety\": \"...\"\n",
        "}}\n",
        "\"\"\"\n",
        "\n",
        "    return generate_json(\n",
        "        prompt,\n",
        "        temperature=0.8,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DAILY PROJECT IDEA\n",
        "# =========================================================\n",
        "\n",
        "def generate_project_idea(\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        "    previous_projects: Optional[\n",
        "        list[str]\n",
        "    ] = None,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate one Arduino/ESP32/robotics project.\n",
        "    \"\"\"\n",
        "\n",
        "    previous_projects = (\n",
        "        previous_projects or []\n",
        "    )\n",
        "\n",
        "    previous_text = \"\\n\".join(\n",
        "        f\"- {title}\"\n",
        "        for title in previous_projects\n",
        "    )\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are an expert Arduino, ESP32,\n",
        "robotics, IoT and electronics engineer.\n",
        "\n",
        "Design ONE practical student project.\n",
        "\n",
        "Target grade:\n",
        "{grade}\n",
        "\n",
        "Domain:\n",
        "{domain}\n",
        "\n",
        "Difficulty:\n",
        "{difficulty}\n",
        "\n",
        "Previously used projects:\n",
        "{previous_text}\n",
        "\n",
        "The project must include:\n",
        "- realistic components\n",
        "- circuit concept\n",
        "- working principle\n",
        "- code outline\n",
        "- learning outcomes\n",
        "- possible extensions\n",
        "- approximate Indian budget\n",
        "\n",
        "Do not invent impossible hardware specifications.\n",
        "\n",
        "Return ONLY valid JSON.\n",
        "\n",
        "Required structure:\n",
        "\n",
        "{{\n",
        "  \"title\": \"...\",\n",
        "  \"description\": \"...\",\n",
        "  \"grade\": \"{grade}\",\n",
        "  \"domain\": \"{domain}\",\n",
        "  \"difficulty\": \"{difficulty}\",\n",
        "  \"budget\": \"₹...\",\n",
        "  \"components\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"circuit_concept\": \"...\",\n",
        "  \"working\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"code_outline\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"learning_outcomes\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"extensions\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"safety\": \"...\"\n",
        "}}\n",
        "\"\"\"\n",
        "\n",
        "    return generate_json(\n",
        "        prompt,\n",
        "        temperature=0.85,\n",
        "        max_output_tokens=5000,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CLASS SESSION REPORT\n",
        "# =========================================================\n",
        "\n",
        "def generate_class_report(\n",
        "    grade: str,\n",
        "    section: str,\n",
        "    topic: str,\n",
        "    activity: str,\n",
        "    notes: str = \"\",\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Convert raw classroom information into\n",
        "    a short professional session report.\n",
        "    \"\"\"\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are a STEM education coordinator.\n",
        "\n",
        "Create a concise professional class-session report.\n",
        "\n",
        "Grade:\n",
        "{grade}\n",
        "\n",
        "Section:\n",
        "{section}\n",
        "\n",
        "Topic:\n",
        "{topic}\n",
        "\n",
        "Activity:\n",
        "{activity}\n",
        "\n",
        "Teacher notes:\n",
        "{notes}\n",
        "\n",
        "The report should be suitable for:\n",
        "- school ERP\n",
        "- principal update\n",
        "- STEM activity records\n",
        "\n",
        "Return ONLY valid JSON:\n",
        "\n",
        "{{\n",
        "  \"summary\": \"...\",\n",
        "  \"learning_outcomes\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"skills\": [\n",
        "    \"...\"\n",
        "  ],\n",
        "  \"student_engagement\": \"...\",\n",
        "  \"next_step\": \"...\"\n",
        "}}\n",
        "\"\"\"\n",
        "\n",
        "    return generate_json(\n",
        "        prompt,\n",
        "        temperature=0.5,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# WEEKLY REPORT\n",
        "# =========================================================\n",
        "\n",
        "def generate_weekly_report(\n",
        "    week_start: str,\n",
        "    week_end: str,\n",
        "    data: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Generate professional weekly STEM report.\n",
        "    \"\"\"\n",
        "\n",
        "    data_json = json.dumps(\n",
        "        data,\n",
        "        ensure_ascii=False,\n",
        "        indent=2,\n",
        "    )\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are a senior STEM program coordinator.\n",
        "\n",
        "Create a professional weekly STEM progress report.\n",
        "\n",
        "Reporting period:\n",
        "{week_start} to {week_end}\n",
        "\n",
        "Raw STEM activity data:\n",
        "\n",
        "{data_json}\n",
        "\n",
        "Write a concise but meaningful report covering:\n",
        "\n",
        "1. Overall weekly progress\n",
        "2. Major STEM topics\n",
        "3. Grade-wise progress\n",
        "4. Skills developed\n",
        "5. Student engagement\n",
        "6. Practical/project work\n",
        "7. Challenges, if identifiable\n",
        "8. Recommended next steps\n",
        "\n",
        "Important:\n",
        "- Do not invent activities.\n",
        "- Do not invent student performance statistics.\n",
        "- Use only information present in the supplied data.\n",
        "- Keep the language professional.\n",
        "- Make it suitable for sharing with a school principal.\n",
        "\n",
        "Return plain text only.\n",
        "\"\"\"\n",
        "\n",
        "    return generate_text(\n",
        "        prompt,\n",
        "        temperature=0.45,\n",
        "        max_output_tokens=5000,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMPETITION UPDATE\n",
        "# =========================================================\n",
        "\n",
        "def generate_competition_update(\n",
        "    project: dict[str, Any],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Analyze an AI/robotics competition project.\n",
        "    \"\"\"\n",
        "\n",
        "    project_json = json.dumps(\n",
        "        project,\n",
        "        ensure_ascii=False,\n",
        "        indent=2,\n",
        "    )\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are an AI competition strategist.\n",
        "\n",
        "Analyze the following project status:\n",
        "\n",
        "{project_json}\n",
        "\n",
        "Create a concise technical progress update.\n",
        "\n",
        "Pay particular attention to:\n",
        "- score\n",
        "- rank\n",
        "- version\n",
        "- wins/losses\n",
        "- win rate\n",
        "- recent changes\n",
        "- blockers\n",
        "- economic efficiency\n",
        "- testing strategy\n",
        "- next optimization steps\n",
        "\n",
        "For a farming simulation such as Kaggriculture,\n",
        "consider:\n",
        "- cash flow\n",
        "- resource allocation\n",
        "- crop profitability\n",
        "- animal profitability\n",
        "- land investment\n",
        "- market timing\n",
        "- remaining simulation days\n",
        "- opportunity cost\n",
        "- exploration versus exploitation\n",
        "\n",
        "Do not invent metrics that are not supplied.\n",
        "\n",
        "Return ONLY valid JSON:\n",
        "\n",
        "{{\n",
        "  \"summary\": \"...\",\n",
        "  \"achievement\": \"...\",\n",
        "  \"risk\": \"...\",\n",
        "  \"recommendation\": \"...\",\n",
        "  \"next_actions\": [\n",
        "    \"...\"\n",
        "  ]\n",
        "}}\n",
        "\"\"\"\n",
        "\n",
        "    return generate_json(\n",
        "        prompt,\n",
        "        temperature=0.45,\n",
        "        max_output_tokens=4000,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NEWS SUMMARIZATION\n",
        "# =========================================================\n",
        "\n",
        "def summarize_news(\n",
        "    articles: list[dict[str, Any]],\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Summarize collected AI/Robotics news.\n",
        "\n",
        "    The news agent is responsible for collecting\n",
        "    current articles. Gemini only summarizes them.\n",
        "    \"\"\"\n",
        "\n",
        "    if not articles:\n",
        "\n",
        "        return []\n",
        "\n",
        "    articles_json = json.dumps(\n",
        "        articles,\n",
        "        ensure_ascii=False,\n",
        "        indent=2,\n",
        "    )\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "You are an AI and robotics technology journalist.\n",
        "\n",
        "Summarize the following current news articles.\n",
        "\n",
        "Articles:\n",
        "\n",
        "{articles_json}\n",
        "\n",
        "For each article:\n",
        "- preserve factual accuracy\n",
        "- explain why it matters\n",
        "- keep the summary short\n",
        "- do not invent facts\n",
        "- do not exaggerate\n",
        "\n",
        "Return ONLY valid JSON:\n",
        "\n",
        "{{\n",
        "  \"articles\": [\n",
        "    {{\n",
        "      \"title\": \"...\",\n",
        "      \"summary\": \"...\",\n",
        "      \"why_it_matters\": \"...\",\n",
        "      \"category\": \"AI/Robotics/Electronics/IoT/Other\"\n",
        "    }}\n",
        "  ]\n",
        "}}\n",
        "\"\"\"\n",
        "\n",
        "    result = generate_json(\n",
        "        prompt,\n",
        "        temperature=0.35,\n",
        "        max_output_tokens=6000,\n",
        "    )\n",
        "\n",
        "    articles_result = result.get(\n",
        "        \"articles\",\n",
        "        [],\n",
        "    )\n",
        "\n",
        "    if not isinstance(\n",
        "        articles_result,\n",
        "        list,\n",
        "    ):\n",
        "\n",
        "        return []\n",
        "\n",
        "    return articles_result\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GENERAL AI ASSISTANT\n",
        "# =========================================================\n",
        "\n",
        "def ask_gemini(\n",
        "    prompt: str,\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Public helper for future agents.\n",
        "    \"\"\"\n",
        "\n",
        "    return generate_text(\n",
        "        prompt\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HEALTH CHECK\n",
        "# =========================================================\n",
        "\n",
        "def test_connection() -> bool:\n",
        "    \"\"\"\n",
        "    Test Gemini API connection.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        response = generate_text(\n",
        "            \"Reply with exactly: GEMINI_OK\",\n",
        "            temperature=0,\n",
        "            max_output_tokens=20,\n",
        "        )\n",
        "\n",
        "        return (\n",
        "            \"GEMINI_OK\"\n",
        "            in response.upper()\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"Gemini health check failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        \"Testing Gemini connection...\"\n",
        "    )\n",
        "\n",
        "    if test_connection():\n",
        "\n",
        "        print(\n",
        "            \"✅ Gemini connection successful.\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        print(\n",
        "            \"❌ Gemini connection failed.\"\n",
        "        )"
      ],
      "metadata": {
        "id": "GpKAeE6KwT_R"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}