{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMEikG0xd8tISvM4xH/1AeF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/github.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "services/github.py\n",
        "\n",
        "GitHub monitoring service.\n",
        "\n",
        "Used by:\n",
        "- competition_agent.py\n",
        "- main.py\n",
        "- future project monitoring agents\n",
        "\n",
        "Features:\n",
        "- Get repository information\n",
        "- Get latest commits\n",
        "- Get latest releases\n",
        "- Get GitHub Actions workflow runs\n",
        "- Detect repository changes\n",
        "- Compare current state with previous state\n",
        "- Generate a compact project status dictionary\n",
        "\n",
        "Authentication:\n",
        "    Optional GITHUB_TOKEN\n",
        "\n",
        "Environment variables:\n",
        "\n",
        "    GITHUB_TOKEN=your_github_token\n",
        "\n",
        "Optional:\n",
        "\n",
        "    GITHUB_REPOSITORY=sackm123-cloud/Kaggriculture-competition\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import logging\n",
        "import os\n",
        "from datetime import datetime, timezone\n",
        "from typing import Any, Optional\n",
        "\n",
        "import requests\n",
        "from dotenv import load_dotenv\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# LOAD ENVIRONMENT\n",
        "# =========================================================\n",
        "\n",
        "load_dotenv()\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.GitHub\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "GITHUB_API = (\n",
        "    \"https://api.github.com\"\n",
        ")\n",
        "\n",
        "GITHUB_TOKEN = os.getenv(\n",
        "    \"GITHUB_TOKEN\"\n",
        ")\n",
        "\n",
        "DEFAULT_REPOSITORY = os.getenv(\n",
        "    \"GITHUB_REPOSITORY\",\n",
        "    \"sackm123-cloud/Kaggriculture-competition\",\n",
        ")\n",
        "\n",
        "REQUEST_TIMEOUT = int(\n",
        "    os.getenv(\n",
        "        \"GITHUB_TIMEOUT\",\n",
        "        \"20\",\n",
        "    )\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SESSION\n",
        "# =========================================================\n",
        "\n",
        "session = requests.Session()\n",
        "\n",
        "session.headers.update(\n",
        "    {\n",
        "        \"Accept\": (\n",
        "            \"application/vnd.github+json\"\n",
        "        ),\n",
        "        \"X-GitHub-Api-Version\": (\n",
        "            \"2022-11-28\"\n",
        "        ),\n",
        "        \"User-Agent\": (\n",
        "            \"AI-STEM-Automation\"\n",
        "        ),\n",
        "    }\n",
        ")\n",
        "\n",
        "if GITHUB_TOKEN:\n",
        "\n",
        "    session.headers.update(\n",
        "        {\n",
        "            \"Authorization\":\n",
        "                f\"Bearer {GITHUB_TOKEN}\"\n",
        "        }\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# REQUEST HELPER\n",
        "# =========================================================\n",
        "\n",
        "def github_get(\n",
        "    endpoint: str,\n",
        "    params: Optional[\n",
        "        dict[str, Any]\n",
        "    ] = None,\n",
        ") -> Any:\n",
        "    \"\"\"\n",
        "    Perform a GitHub API GET request.\n",
        "    \"\"\"\n",
        "\n",
        "    url = (\n",
        "        f\"{GITHUB_API}\"\n",
        "        f\"{endpoint}\"\n",
        "    )\n",
        "\n",
        "    logger.debug(\n",
        "        \"GitHub GET %s\",\n",
        "        url,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        response = session.get(\n",
        "            url,\n",
        "            params=params,\n",
        "            timeout=REQUEST_TIMEOUT,\n",
        "        )\n",
        "\n",
        "    except requests.RequestException as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"GitHub connection failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        raise RuntimeError(\n",
        "            f\"GitHub connection failed: {exc}\"\n",
        "        ) from exc\n",
        "\n",
        "    if response.status_code == 401:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"GitHub authentication failed. \"\n",
        "            \"Check GITHUB_TOKEN.\"\n",
        "        )\n",
        "\n",
        "    if response.status_code == 403:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"GitHub API rate limit or \"\n",
        "            \"permission error.\"\n",
        "        )\n",
        "\n",
        "    if response.status_code == 404:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"GitHub repository or resource \"\n",
        "            \"was not found.\"\n",
        "        )\n",
        "\n",
        "    if not response.ok:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"GitHub API error \"\n",
        "            f\"{response.status_code}: \"\n",
        "            f\"{response.text[:300]}\"\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        return response.json()\n",
        "\n",
        "    except ValueError as exc:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"GitHub returned invalid JSON.\"\n",
        "        ) from exc\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# REPOSITORY INFORMATION\n",
        "# =========================================================\n",
        "\n",
        "def get_repository(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Get repository information.\n",
        "\n",
        "    Example:\n",
        "        get_repository(\n",
        "            \"sackm123-cloud/Kaggriculture-competition\"\n",
        "        )\n",
        "    \"\"\"\n",
        "\n",
        "    repository = repository.strip()\n",
        "\n",
        "    if \"/\" not in repository:\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Repository must be in \"\n",
        "            \"'owner/repository' format.\"\n",
        "        )\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"name\": data.get(\n",
        "            \"name\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"full_name\": data.get(\n",
        "            \"full_name\",\n",
        "            repository,\n",
        "        ),\n",
        "\n",
        "        \"description\": data.get(\n",
        "            \"description\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"private\": data.get(\n",
        "            \"private\",\n",
        "            False,\n",
        "        ),\n",
        "\n",
        "        \"default_branch\": data.get(\n",
        "            \"default_branch\",\n",
        "            \"main\",\n",
        "        ),\n",
        "\n",
        "        \"stars\": data.get(\n",
        "            \"stargazers_count\",\n",
        "            0,\n",
        "        ),\n",
        "\n",
        "        \"forks\": data.get(\n",
        "            \"forks_count\",\n",
        "            0,\n",
        "        ),\n",
        "\n",
        "        \"open_issues\": data.get(\n",
        "            \"open_issues_count\",\n",
        "            0,\n",
        "        ),\n",
        "\n",
        "        \"language\": data.get(\n",
        "            \"language\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"size\": data.get(\n",
        "            \"size\",\n",
        "            0,\n",
        "        ),\n",
        "\n",
        "        \"created_at\": data.get(\n",
        "            \"created_at\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"updated_at\": data.get(\n",
        "            \"updated_at\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"pushed_at\": data.get(\n",
        "            \"pushed_at\",\n",
        "            \"\",\n",
        "        ),\n",
        "\n",
        "        \"html_url\": data.get(\n",
        "            \"html_url\",\n",
        "            \"\",\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMITS\n",
        "# =========================================================\n",
        "\n",
        "def get_commits(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    limit: int = 10,\n",
        "    branch: Optional[str] = None,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Get latest repository commits.\n",
        "    \"\"\"\n",
        "\n",
        "    limit = max(\n",
        "        1,\n",
        "        min(\n",
        "            limit,\n",
        "            100,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    params: dict[str, Any] = {\n",
        "        \"per_page\": limit,\n",
        "    }\n",
        "\n",
        "    if branch:\n",
        "\n",
        "        params[\"sha\"] = branch\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}/commits\",\n",
        "        params=params,\n",
        "    )\n",
        "\n",
        "    commits = []\n",
        "\n",
        "    for item in data:\n",
        "\n",
        "        commit = item.get(\n",
        "            \"commit\",\n",
        "            {},\n",
        "        )\n",
        "\n",
        "        author = commit.get(\n",
        "            \"author\",\n",
        "            {},\n",
        "        )\n",
        "\n",
        "        commits.append(\n",
        "            {\n",
        "                \"sha\": item.get(\n",
        "                    \"sha\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"short_sha\": (\n",
        "                    item.get(\n",
        "                        \"sha\",\n",
        "                        \"\",\n",
        "                    )[:7]\n",
        "                ),\n",
        "\n",
        "                \"message\": (\n",
        "                    commit.get(\n",
        "                        \"message\",\n",
        "                        \"\",\n",
        "                    ).split(\"\\n\")[0]\n",
        "                ),\n",
        "\n",
        "                \"author\": author.get(\n",
        "                    \"name\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"date\": author.get(\n",
        "                    \"date\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": item.get(\n",
        "                    \"html_url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return commits\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# LATEST COMMIT\n",
        "# =========================================================\n",
        "\n",
        "def get_latest_commit(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    branch: Optional[str] = None,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Get the latest commit.\n",
        "    \"\"\"\n",
        "\n",
        "    commits = get_commits(\n",
        "        repository=repository,\n",
        "        limit=1,\n",
        "        branch=branch,\n",
        "    )\n",
        "\n",
        "    if not commits:\n",
        "\n",
        "        return {}\n",
        "\n",
        "    return commits[0]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RELEASES\n",
        "# =========================================================\n",
        "\n",
        "def get_releases(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    limit: int = 5,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Get latest GitHub releases.\n",
        "    \"\"\"\n",
        "\n",
        "    limit = max(\n",
        "        1,\n",
        "        min(\n",
        "            limit,\n",
        "            30,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}/releases\",\n",
        "        params={\n",
        "            \"per_page\": limit,\n",
        "        },\n",
        "    )\n",
        "\n",
        "    releases = []\n",
        "\n",
        "    for release in data:\n",
        "\n",
        "        releases.append(\n",
        "            {\n",
        "                \"id\": release.get(\n",
        "                    \"id\"\n",
        "                ),\n",
        "\n",
        "                \"tag\": release.get(\n",
        "                    \"tag_name\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"name\": release.get(\n",
        "                    \"name\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"draft\": release.get(\n",
        "                    \"draft\",\n",
        "                    False,\n",
        "                ),\n",
        "\n",
        "                \"prerelease\": release.get(\n",
        "                    \"prerelease\",\n",
        "                    False,\n",
        "                ),\n",
        "\n",
        "                \"created_at\": release.get(\n",
        "                    \"created_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"published_at\": release.get(\n",
        "                    \"published_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": release.get(\n",
        "                    \"html_url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return releases\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# WORKFLOW RUNS\n",
        "# =========================================================\n",
        "\n",
        "def get_workflow_runs(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    limit: int = 10,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Get latest GitHub Actions workflow runs.\n",
        "    \"\"\"\n",
        "\n",
        "    limit = max(\n",
        "        1,\n",
        "        min(\n",
        "            limit,\n",
        "            100,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}/actions/runs\",\n",
        "        params={\n",
        "            \"per_page\": limit,\n",
        "        },\n",
        "    )\n",
        "\n",
        "    runs = data.get(\n",
        "        \"workflow_runs\",\n",
        "        [],\n",
        "    )\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for run in runs:\n",
        "\n",
        "        results.append(\n",
        "            {\n",
        "                \"id\": run.get(\n",
        "                    \"id\"\n",
        "                ),\n",
        "\n",
        "                \"name\": run.get(\n",
        "                    \"name\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"status\": run.get(\n",
        "                    \"status\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"conclusion\": run.get(\n",
        "                    \"conclusion\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"branch\": run.get(\n",
        "                    \"head_branch\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"commit\": (\n",
        "                    run.get(\n",
        "                        \"head_sha\",\n",
        "                        \"\",\n",
        "                    )[:7]\n",
        "                ),\n",
        "\n",
        "                \"created_at\": run.get(\n",
        "                    \"created_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"updated_at\": run.get(\n",
        "                    \"updated_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": run.get(\n",
        "                    \"html_url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ISSUES\n",
        "# =========================================================\n",
        "\n",
        "def get_open_issues(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    limit: int = 20,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Get open GitHub issues.\n",
        "    \"\"\"\n",
        "\n",
        "    limit = max(\n",
        "        1,\n",
        "        min(\n",
        "            limit,\n",
        "            100,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}/issues\",\n",
        "        params={\n",
        "            \"state\": \"open\",\n",
        "            \"per_page\": limit,\n",
        "        },\n",
        "    )\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for issue in data:\n",
        "\n",
        "        # Pull requests also appear in\n",
        "        # the GitHub issues endpoint.\n",
        "        if issue.get(\n",
        "            \"pull_request\"\n",
        "        ):\n",
        "\n",
        "            continue\n",
        "\n",
        "        results.append(\n",
        "            {\n",
        "                \"number\": issue.get(\n",
        "                    \"number\"\n",
        "                ),\n",
        "\n",
        "                \"title\": issue.get(\n",
        "                    \"title\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"state\": issue.get(\n",
        "                    \"state\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"created_at\": issue.get(\n",
        "                    \"created_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"updated_at\": issue.get(\n",
        "                    \"updated_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": issue.get(\n",
        "                    \"html_url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PULL REQUESTS\n",
        "# =========================================================\n",
        "\n",
        "def get_pull_requests(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        "    limit: int = 10,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Get recent pull requests.\n",
        "    \"\"\"\n",
        "\n",
        "    limit = max(\n",
        "        1,\n",
        "        min(\n",
        "            limit,\n",
        "            100,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    data = github_get(\n",
        "        f\"/repos/{repository}/pulls\",\n",
        "        params={\n",
        "            \"state\": \"all\",\n",
        "            \"sort\": \"updated\",\n",
        "            \"direction\": \"desc\",\n",
        "            \"per_page\": limit,\n",
        "        },\n",
        "    )\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for pull in data:\n",
        "\n",
        "        results.append(\n",
        "            {\n",
        "                \"number\": pull.get(\n",
        "                    \"number\"\n",
        "                ),\n",
        "\n",
        "                \"title\": pull.get(\n",
        "                    \"title\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"state\": pull.get(\n",
        "                    \"state\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"merged\": (\n",
        "                    pull.get(\n",
        "                        \"merged_at\"\n",
        "                    )\n",
        "                    is not None\n",
        "                ),\n",
        "\n",
        "                \"created_at\": pull.get(\n",
        "                    \"created_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"updated_at\": pull.get(\n",
        "                    \"updated_at\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": pull.get(\n",
        "                    \"html_url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMPETITION PROJECT STATUS\n",
        "# =========================================================\n",
        "\n",
        "def get_project_status(\n",
        "    repository: str = DEFAULT_REPOSITORY,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Build a compact status object suitable for Gemini.\n",
        "\n",
        "    This does NOT invent competition scores.\n",
        "    Scores should come from the competition platform\n",
        "    or your database.\n",
        "    \"\"\"\n",
        "\n",
        "    repository_info = (\n",
        "        get_repository(\n",
        "            repository\n",
        "        )\n",
        "    )\n",
        "\n",
        "    latest_commit = (\n",
        "        get_latest_commit(\n",
        "            repository\n",
        "        )\n",
        "    )\n",
        "\n",
        "    workflow_runs = (\n",
        "        get_workflow_runs(\n",
        "            repository,\n",
        "            limit=5,\n",
        "        )\n",
        "    )\n",
        "\n",
        "    issues = (\n",
        "        get_open_issues(\n",
        "            repository,\n",
        "            limit=10,\n",
        "        )\n",
        "    )\n",
        "\n",
        "    releases = (\n",
        "        get_releases(\n",
        "            repository,\n",
        "            limit=5,\n",
        "        )\n",
        "    )\n",
        "\n",
        "    successful_runs = sum(\n",
        "        1\n",
        "        for run in workflow_runs\n",
        "        if run.get(\n",
        "            \"conclusion\"\n",
        "        ) == \"success\"\n",
        "    )\n",
        "\n",
        "    failed_runs = sum(\n",
        "        1\n",
        "        for run in workflow_runs\n",
        "        if run.get(\n",
        "            \"conclusion\"\n",
        "        ) == \"failure\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"repository\": (\n",
        "            repository_info[\n",
        "                \"full_name\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"repository_url\": (\n",
        "            repository_info[\n",
        "                \"html_url\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"default_branch\": (\n",
        "            repository_info[\n",
        "                \"default_branch\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"language\": (\n",
        "            repository_info[\n",
        "                \"language\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"stars\": (\n",
        "            repository_info[\n",
        "                \"stars\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"open_issues\": (\n",
        "            repository_info[\n",
        "                \"open_issues\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"last_updated\": (\n",
        "            repository_info[\n",
        "                \"updated_at\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"last_push\": (\n",
        "            repository_info[\n",
        "                \"pushed_at\"\n",
        "            ]\n",
        "        ),\n",
        "\n",
        "        \"latest_commit\": latest_commit,\n",
        "\n",
        "        \"workflow_runs\": workflow_runs,\n",
        "\n",
        "        \"successful_workflows\": (\n",
        "            successful_runs\n",
        "        ),\n",
        "\n",
        "        \"failed_workflows\": (\n",
        "            failed_runs\n",
        "        ),\n",
        "\n",
        "        \"open_issues_list\": issues,\n",
        "\n",
        "        \"releases\": releases,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CHANGE DETECTION\n",
        "# =========================================================\n",
        "\n",
        "def has_repository_changed(\n",
        "    old_status: Optional[\n",
        "        dict[str, Any]\n",
        "    ],\n",
        "    new_status: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"\n",
        "    Determine whether important repository state\n",
        "    has changed.\n",
        "    \"\"\"\n",
        "\n",
        "    if not old_status:\n",
        "\n",
        "        return True\n",
        "\n",
        "    old_commit = (\n",
        "        old_status.get(\n",
        "            \"latest_commit\",\n",
        "            {},\n",
        "        )\n",
        "        or {}\n",
        "    )\n",
        "\n",
        "    new_commit = (\n",
        "        new_status.get(\n",
        "            \"latest_commit\",\n",
        "            {},\n",
        "        )\n",
        "        or {}\n",
        "    )\n",
        "\n",
        "    if (\n",
        "        old_commit.get(\"sha\")\n",
        "        != new_commit.get(\"sha\")\n",
        "    ):\n",
        "\n",
        "        return True\n",
        "\n",
        "    if (\n",
        "        old_status.get(\n",
        "            \"last_push\"\n",
        "        )\n",
        "        != new_status.get(\n",
        "            \"last_push\"\n",
        "        )\n",
        "    ):\n",
        "\n",
        "        return True\n",
        "\n",
        "    if (\n",
        "        old_status.get(\n",
        "            \"failed_workflows\"\n",
        "        )\n",
        "        != new_status.get(\n",
        "            \"failed_workflows\"\n",
        "        )\n",
        "    ):\n",
        "\n",
        "        return True\n",
        "\n",
        "    if (\n",
        "        old_status.get(\n",
        "            \"open_issues\"\n",
        "        )\n",
        "        != new_status.get(\n",
        "            \"open_issues\"\n",
        "        )\n",
        "    ):\n",
        "\n",
        "        return True\n",
        "\n",
        "    return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CHANGE SUMMARY\n",
        "# =========================================================\n",
        "\n",
        "def get_change_summary(\n",
        "    old_status: Optional[\n",
        "        dict[str, Any]\n",
        "    ],\n",
        "    new_status: dict[str, Any],\n",
        ") -> list[str]:\n",
        "    \"\"\"\n",
        "    Produce human-readable repository changes.\n",
        "    \"\"\"\n",
        "\n",
        "    changes = []\n",
        "\n",
        "    if not old_status:\n",
        "\n",
        "        return [\n",
        "            \"Initial repository snapshot.\"\n",
        "        ]\n",
        "\n",
        "    old_commit = (\n",
        "        old_status.get(\n",
        "            \"latest_commit\",\n",
        "            {},\n",
        "        )\n",
        "        or {}\n",
        "    )\n",
        "\n",
        "    new_commit = (\n",
        "        new_status.get(\n",
        "            \"latest_commit\",\n",
        "            {},\n",
        "        )\n",
        "        or {}\n",
        "    )\n",
        "\n",
        "    if (\n",
        "        old_commit.get(\"sha\")\n",
        "        != new_commit.get(\"sha\")\n",
        "    ):\n",
        "\n",
        "        message = new_commit.get(\n",
        "            \"message\",\n",
        "            \"\",\n",
        "        )\n",
        "\n",
        "        changes.append(\n",
        "            \"New commit: \"\n",
        "            f\"{message}\"\n",
        "        )\n",
        "\n",
        "    old_push = old_status.get(\n",
        "        \"last_push\"\n",
        "    )\n",
        "\n",
        "    new_push = new_status.get(\n",
        "        \"last_push\"\n",
        "    )\n",
        "\n",
        "    if old_push != new_push:\n",
        "\n",
        "        changes.append(\n",
        "            \"Repository was updated.\"\n",
        "        )\n",
        "\n",
        "    old_failures = old_status.get(\n",
        "        \"failed_workflows\",\n",
        "        0,\n",
        "    )\n",
        "\n",
        "    new_failures = new_status.get(\n",
        "        \"failed_workflows\",\n",
        "        0,\n",
        "    )\n",
        "\n",
        "    if old_failures != new_failures:\n",
        "\n",
        "        changes.append(\n",
        "            \"GitHub Actions workflow \"\n",
        "            \"failure count changed.\"\n",
        "        )\n",
        "\n",
        "    old_issues = old_status.get(\n",
        "        \"open_issues\",\n",
        "        0,\n",
        "    )\n",
        "\n",
        "    new_issues = new_status.get(\n",
        "        \"open_issues\",\n",
        "        0,\n",
        "    )\n",
        "\n",
        "    if old_issues != new_issues:\n",
        "\n",
        "        changes.append(\n",
        "            \"Open issue count changed.\"\n",
        "        )\n",
        "\n",
        "    return changes\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONNECTION TEST\n",
        "# =========================================================\n",
        "\n",
        "def test_connection() -> bool:\n",
        "    \"\"\"\n",
        "    Test GitHub API connectivity.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        data = github_get(\n",
        "            \"/rate_limit\"\n",
        "        )\n",
        "\n",
        "        return bool(\n",
        "            data.get(\n",
        "                \"rate\",\n",
        "                {},\n",
        "            )\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"GitHub connection test failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 65)\n",
        "    print(\"GITHUB MONITOR\")\n",
        "    print(\"=\" * 65)\n",
        "\n",
        "    print(\n",
        "        f\"Repository: \"\n",
        "        f\"{DEFAULT_REPOSITORY}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Token configured: \"\n",
        "        f\"{bool(GITHUB_TOKEN)}\"\n",
        "    )\n",
        "\n",
        "    print()\n",
        "\n",
        "    if test_connection():\n",
        "\n",
        "        print(\n",
        "            \"✅ GitHub API connection successful.\"\n",
        "        )\n",
        "\n",
        "        try:\n",
        "\n",
        "            status = (\n",
        "                get_project_status()\n",
        "            )\n",
        "\n",
        "            print()\n",
        "            print(\n",
        "                \"Repository:\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                status[\"repository\"]\n",
        "            )\n",
        "\n",
        "            print()\n",
        "            print(\n",
        "                \"Latest commit:\"\n",
        "            )\n",
        "\n",
        "            commit = status[\n",
        "                \"latest_commit\"\n",
        "            ]\n",
        "\n",
        "            print(\n",
        "                commit.get(\n",
        "                    \"short_sha\",\n",
        "                    \"-\",\n",
        "                )\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                commit.get(\n",
        "                    \"message\",\n",
        "                    \"-\",\n",
        "                )\n",
        "            )\n",
        "\n",
        "            print()\n",
        "            print(\n",
        "                \"Successful workflows:\",\n",
        "                status[\n",
        "                    \"successful_workflows\"\n",
        "                ],\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"Failed workflows:\",\n",
        "                status[\n",
        "                    \"failed_workflows\"\n",
        "                ],\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"Open issues:\",\n",
        "                status[\n",
        "                    \"open_issues\"\n",
        "                ],\n",
        "            )\n",
        "\n",
        "        except Exception as exc:\n",
        "\n",
        "            print(\n",
        "                f\"❌ GitHub monitoring failed: \"\n",
        "                f\"{exc}\"\n",
        "            )\n",
        "\n",
        "    else:\n",
        "\n",
        "        print(\n",
        "            \"❌ GitHub API connection failed.\"\n",
        "        )\n",
        "\n",
        "    print(\"=\" * 65)"
      ],
      "metadata": {
        "id": "Dwsoxj9xw9dJ"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}