{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMfUPQOzqohh98qklR868B5",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/gmail.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "services/gmail.py\n",
        "\n",
        "Central Gmail SMTP service.\n",
        "\n",
        "Used by:\n",
        "- news_agent.py\n",
        "- class_agent.py\n",
        "- stem_tip_agent.py\n",
        "- project_agent.py\n",
        "- weekly_report_agent.py\n",
        "- competition_agent.py\n",
        "\n",
        "Authentication:\n",
        "    Gmail SMTP + App Password\n",
        "\n",
        "Environment variables:\n",
        "    GMAIL_ADDRESS=your_email@gmail.com\n",
        "    GMAIL_APP_PASSWORD=your_16_character_app_password\n",
        "    GMAIL_TO=recipient@gmail.com\n",
        "\n",
        "Optional:\n",
        "    GMAIL_FROM_NAME=AI STEM Automation Hub\n",
        "    GMAIL_CC=\n",
        "    GMAIL_BCC=\n",
        "    SMTP_HOST=smtp.gmail.com\n",
        "    SMTP_PORT=465\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import logging\n",
        "import os\n",
        "import smtplib\n",
        "import ssl\n",
        "from email.message import EmailMessage\n",
        "from typing import Optional\n",
        "\n",
        "from dotenv import load_dotenv\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# LOAD ENVIRONMENT\n",
        "# =========================================================\n",
        "\n",
        "load_dotenv()\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.Gmail\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "SMTP_HOST = os.getenv(\n",
        "    \"SMTP_HOST\",\n",
        "    \"smtp.gmail.com\",\n",
        ")\n",
        "\n",
        "SMTP_PORT = int(\n",
        "    os.getenv(\n",
        "        \"SMTP_PORT\",\n",
        "        \"465\",\n",
        "    )\n",
        ")\n",
        "\n",
        "GMAIL_ADDRESS = os.getenv(\n",
        "    \"GMAIL_ADDRESS\"\n",
        ")\n",
        "\n",
        "GMAIL_APP_PASSWORD = os.getenv(\n",
        "    \"GMAIL_APP_PASSWORD\"\n",
        ")\n",
        "\n",
        "GMAIL_TO = os.getenv(\n",
        "    \"GMAIL_TO\"\n",
        ")\n",
        "\n",
        "GMAIL_FROM_NAME = os.getenv(\n",
        "    \"GMAIL_FROM_NAME\",\n",
        "    \"AI STEM Automation Hub\",\n",
        ")\n",
        "\n",
        "GMAIL_CC = os.getenv(\n",
        "    \"GMAIL_CC\",\n",
        "    \"\",\n",
        ")\n",
        "\n",
        "GMAIL_BCC = os.getenv(\n",
        "    \"GMAIL_BCC\",\n",
        "    \"\",\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# VALIDATION\n",
        "# =========================================================\n",
        "\n",
        "def validate_config() -> None:\n",
        "    \"\"\"Validate Gmail SMTP configuration.\"\"\"\n",
        "\n",
        "    missing = []\n",
        "\n",
        "    if not GMAIL_ADDRESS:\n",
        "        missing.append(\n",
        "            \"GMAIL_ADDRESS\"\n",
        "        )\n",
        "\n",
        "    if not GMAIL_APP_PASSWORD:\n",
        "        missing.append(\n",
        "            \"GMAIL_APP_PASSWORD\"\n",
        "        )\n",
        "\n",
        "    if not GMAIL_TO:\n",
        "        missing.append(\n",
        "            \"GMAIL_TO\"\n",
        "        )\n",
        "\n",
        "    if missing:\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"Missing Gmail configuration: \"\n",
        "            + \", \".join(missing)\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ADDRESS HELPERS\n",
        "# =========================================================\n",
        "\n",
        "def parse_addresses(\n",
        "    addresses: Optional[str],\n",
        ") -> list[str]:\n",
        "    \"\"\"\n",
        "    Convert comma/semicolon-separated addresses\n",
        "    into a list.\n",
        "    \"\"\"\n",
        "\n",
        "    if not addresses:\n",
        "        return []\n",
        "\n",
        "    addresses = addresses.replace(\n",
        "        \";\",\n",
        "        \",\",\n",
        "    )\n",
        "\n",
        "    return [\n",
        "        address.strip()\n",
        "        for address in addresses.split(\",\")\n",
        "        if address.strip()\n",
        "    ]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CREATE MESSAGE\n",
        "# =========================================================\n",
        "\n",
        "def create_message(\n",
        "    subject: str,\n",
        "    text_body: str,\n",
        "    html_body: Optional[str] = None,\n",
        "    to: Optional[str] = None,\n",
        "    cc: Optional[str] = None,\n",
        "    bcc: Optional[str] = None,\n",
        ") -> EmailMessage:\n",
        "    \"\"\"Create a Gmail email message.\"\"\"\n",
        "\n",
        "    validate_config()\n",
        "\n",
        "    if not subject.strip():\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Email subject cannot be empty.\"\n",
        "        )\n",
        "\n",
        "    if not text_body.strip():\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Email text body cannot be empty.\"\n",
        "        )\n",
        "\n",
        "    recipients = parse_addresses(\n",
        "        to or GMAIL_TO\n",
        "    )\n",
        "\n",
        "    cc_recipients = parse_addresses(\n",
        "        cc or GMAIL_CC\n",
        "    )\n",
        "\n",
        "    bcc_recipients = parse_addresses(\n",
        "        bcc or GMAIL_BCC\n",
        "    )\n",
        "\n",
        "    if not recipients:\n",
        "\n",
        "        raise ValueError(\n",
        "            \"At least one recipient is required.\"\n",
        "        )\n",
        "\n",
        "    message = EmailMessage()\n",
        "\n",
        "    message[\"Subject\"] = subject\n",
        "\n",
        "    message[\"From\"] = (\n",
        "        f\"{GMAIL_FROM_NAME} \"\n",
        "        f\"<{GMAIL_ADDRESS}>\"\n",
        "    )\n",
        "\n",
        "    message[\"To\"] = \", \".join(\n",
        "        recipients\n",
        "    )\n",
        "\n",
        "    if cc_recipients:\n",
        "\n",
        "        message[\"Cc\"] = \", \".join(\n",
        "            cc_recipients\n",
        "        )\n",
        "\n",
        "    if bcc_recipients:\n",
        "\n",
        "        message[\"Bcc\"] = \", \".join(\n",
        "            bcc_recipients\n",
        "        )\n",
        "\n",
        "    message.set_content(\n",
        "        text_body\n",
        "    )\n",
        "\n",
        "    if html_body:\n",
        "\n",
        "        message.add_alternative(\n",
        "            html_body,\n",
        "            subtype=\"html\",\n",
        "        )\n",
        "\n",
        "    return message\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SEND EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_email(\n",
        "    subject: str,\n",
        "    text_body: str,\n",
        "    html_body: Optional[str] = None,\n",
        "    to: Optional[str] = None,\n",
        "    cc: Optional[str] = None,\n",
        "    bcc: Optional[str] = None,\n",
        "    email_type: str = \"general\",\n",
        ") -> bool:\n",
        "    \"\"\"\n",
        "    Send an email using Gmail SMTP over SSL.\n",
        "\n",
        "    Example:\n",
        "\n",
        "        send_email(\n",
        "            subject=\"Daily AI News\",\n",
        "            text_body=\"Today's AI news...\",\n",
        "            html_body=\"<h1>AI News</h1>\",\n",
        "        )\n",
        "    \"\"\"\n",
        "\n",
        "    message = create_message(\n",
        "        subject=subject,\n",
        "        text_body=text_body,\n",
        "        html_body=html_body,\n",
        "        to=to,\n",
        "        cc=cc,\n",
        "        bcc=bcc,\n",
        "    )\n",
        "\n",
        "    recipients = []\n",
        "\n",
        "    recipients.extend(\n",
        "        parse_addresses(\n",
        "            to or GMAIL_TO\n",
        "        )\n",
        "    )\n",
        "\n",
        "    recipients.extend(\n",
        "        parse_addresses(\n",
        "            cc or GMAIL_CC\n",
        "        )\n",
        "    )\n",
        "\n",
        "    recipients.extend(\n",
        "        parse_addresses(\n",
        "            bcc or GMAIL_BCC\n",
        "        )\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Sending %s email to %s\",\n",
        "        email_type,\n",
        "        \", \".join(recipients),\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        context = ssl.create_default_context()\n",
        "\n",
        "        with smtplib.SMTP_SSL(\n",
        "            SMTP_HOST,\n",
        "            SMTP_PORT,\n",
        "            context=context,\n",
        "            timeout=30,\n",
        "        ) as server:\n",
        "\n",
        "            server.login(\n",
        "                GMAIL_ADDRESS,\n",
        "                GMAIL_APP_PASSWORD,\n",
        "            )\n",
        "\n",
        "            server.send_message(\n",
        "                message,\n",
        "                from_addr=GMAIL_ADDRESS,\n",
        "                to_addrs=recipients,\n",
        "            )\n",
        "\n",
        "        logger.info(\n",
        "            \"%s email sent successfully.\",\n",
        "            email_type,\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except smtplib.SMTPAuthenticationError as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"Gmail authentication failed. \"\n",
        "            \"Check the Gmail address and App Password.\"\n",
        "        )\n",
        "\n",
        "        raise RuntimeError(\n",
        "            \"Gmail authentication failed. \"\n",
        "            \"Use a Gmail App Password, not your \"\n",
        "            \"normal Gmail password.\"\n",
        "        ) from exc\n",
        "\n",
        "    except smtplib.SMTPException as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gmail SMTP error: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        raise RuntimeError(\n",
        "            f\"Gmail SMTP error: {exc}\"\n",
        "        ) from exc\n",
        "\n",
        "    except OSError as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Network error while connecting \"\n",
        "            \"to Gmail SMTP: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        raise RuntimeError(\n",
        "            f\"Could not connect to Gmail SMTP: {exc}\"\n",
        "        ) from exc\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEST EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_test_email(\n",
        "    recipient: Optional[str] = None,\n",
        ") -> bool:\n",
        "    \"\"\"Send a simple Gmail SMTP test.\"\"\"\n",
        "\n",
        "    target = (\n",
        "        recipient\n",
        "        or GMAIL_TO\n",
        "    )\n",
        "\n",
        "    return send_email(\n",
        "        subject=(\n",
        "            \"✅ AI STEM Automation - \"\n",
        "            \"Gmail Test\"\n",
        "        ),\n",
        "\n",
        "        text_body=(\n",
        "            \"Gmail SMTP is working correctly.\\n\\n\"\n",
        "            \"AI STEM Automation Hub can now send \"\n",
        "            \"automated reports.\"\n",
        "        ),\n",
        "\n",
        "        html_body=\"\"\"\n",
        "        <html>\n",
        "        <body style=\"\n",
        "            font-family:Arial,sans-serif;\n",
        "            padding:30px;\n",
        "        \">\n",
        "\n",
        "            <h1>\n",
        "                ✅ Gmail SMTP Working\n",
        "            </h1>\n",
        "\n",
        "            <p>\n",
        "                Your AI STEM Automation Hub\n",
        "                can now send automated emails.\n",
        "            </p>\n",
        "\n",
        "        </body>\n",
        "        </html>\n",
        "        \"\"\",\n",
        "\n",
        "        to=target,\n",
        "\n",
        "        email_type=\"test\",\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SERVICE STATUS\n",
        "# =========================================================\n",
        "\n",
        "def get_status() -> dict[str, object]:\n",
        "    \"\"\"Return Gmail service configuration status.\"\"\"\n",
        "\n",
        "    return {\n",
        "        \"configured\": bool(\n",
        "            GMAIL_ADDRESS\n",
        "            and GMAIL_APP_PASSWORD\n",
        "            and GMAIL_TO\n",
        "        ),\n",
        "        \"smtp_host\": SMTP_HOST,\n",
        "        \"smtp_port\": SMTP_PORT,\n",
        "        \"sender\": GMAIL_ADDRESS or \"\",\n",
        "        \"recipient\": GMAIL_TO or \"\",\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"GMAIL SMTP SERVICE\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    status = get_status()\n",
        "\n",
        "    print(\n",
        "        f\"Configured : \"\n",
        "        f\"{status['configured']}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"SMTP Host  : \"\n",
        "        f\"{status['smtp_host']}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"SMTP Port  : \"\n",
        "        f\"{status['smtp_port']}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Sender     : \"\n",
        "        f\"{status['sender']}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Recipient  : \"\n",
        "        f\"{status['recipient']}\"\n",
        "    )\n",
        "\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    if status[\"configured\"]:\n",
        "\n",
        "        answer = input(\n",
        "            \"Send test email? [y/N]: \"\n",
        "        )\n",
        "\n",
        "        if answer.lower() == \"y\":\n",
        "\n",
        "            if send_test_email():\n",
        "\n",
        "                print(\n",
        "                    \"✅ Test email sent.\"\n",
        "                )\n",
        "\n",
        "            else:\n",
        "\n",
        "                print(\n",
        "                    \"❌ Test email failed.\"\n",
        "                )\n",
        "\n",
        "    else:\n",
        "\n",
        "        print(\n",
        "            \"❌ Gmail is not configured.\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"Set the variables in .env first.\"\n",
        "        )"
      ],
      "metadata": {
        "id": "keoJtoAxwo8Q"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}