{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPj3nVvUTseTYcDqsSjm4EX",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/jobs.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "services/jobs.py\n",
        "\n",
        "Central scheduler for all automation agents.\n",
        "\n",
        "Runs:\n",
        "    - Daily AI/Robotics News\n",
        "    - Daily STEM Tip\n",
        "    - Daily Project Idea\n",
        "    - STEM Class Updates\n",
        "    - Weekly Progress Report\n",
        "    - Competition Update\n",
        "\n",
        "This replaces the need for n8n.\n",
        "\n",
        "Recommended:\n",
        "    Run main.py continuously on:\n",
        "    - Linux PC\n",
        "    - Raspberry Pi\n",
        "    - VPS\n",
        "    - Cloud server\n",
        "\n",
        "Install:\n",
        "    pip install apscheduler python-dotenv\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import logging\n",
        "import os\n",
        "import traceback\n",
        "from datetime import datetime\n",
        "from typing import Callable, Optional\n",
        "\n",
        "from apscheduler.schedulers.blocking import (\n",
        "    BlockingScheduler,\n",
        ")\n",
        "from apscheduler.triggers.cron import (\n",
        "    CronTrigger,\n",
        ")\n",
        "from dotenv import load_dotenv\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ENVIRONMENT\n",
        "# =========================================================\n",
        "\n",
        "load_dotenv()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# LOGGING\n",
        "# =========================================================\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.Jobs\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TIMEZONE\n",
        "# =========================================================\n",
        "\n",
        "TIMEZONE = os.getenv(\n",
        "    \"AUTOMATION_TIMEZONE\",\n",
        "    \"Asia/Kolkata\",\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SCHEDULE\n",
        "# =========================================================\n",
        "\n",
        "NEWS_HOUR = int(\n",
        "    os.getenv(\n",
        "        \"NEWS_HOUR\",\n",
        "        \"8\",\n",
        "    )\n",
        ")\n",
        "\n",
        "NEWS_MINUTE = int(\n",
        "    os.getenv(\n",
        "        \"NEWS_MINUTE\",\n",
        "        \"0\",\n",
        "    )\n",
        ")\n",
        "\n",
        "STEM_TIP_HOUR = int(\n",
        "    os.getenv(\n",
        "        \"STEM_TIP_HOUR\",\n",
        "        \"9\",\n",
        "    )\n",
        ")\n",
        "\n",
        "STEM_TIP_MINUTE = int(\n",
        "    os.getenv(\n",
        "        \"STEM_TIP_MINUTE\",\n",
        "        \"0\",\n",
        "    )\n",
        ")\n",
        "\n",
        "PROJECT_HOUR = int(\n",
        "    os.getenv(\n",
        "        \"PROJECT_HOUR\",\n",
        "        \"10\",\n",
        "    )\n",
        ")\n",
        "\n",
        "PROJECT_MINUTE = int(\n",
        "    os.getenv(\n",
        "        \"PROJECT_MINUTE\",\n",
        "        \"0\",\n",
        "    )\n",
        ")\n",
        "\n",
        "COMPETITION_HOUR = int(\n",
        "    os.getenv(\n",
        "        \"COMPETITION_HOUR\",\n",
        "        \"18\",\n",
        "    )\n",
        ")\n",
        "\n",
        "COMPETITION_MINUTE = int(\n",
        "    os.getenv(\n",
        "        \"COMPETITION_MINUTE\",\n",
        "        \"0\",\n",
        "    )\n",
        ")\n",
        "\n",
        "WEEKLY_REPORT_DAY = os.getenv(\n",
        "    \"WEEKLY_REPORT_DAY\",\n",
        "    \"fri\",\n",
        ")\n",
        "\n",
        "WEEKLY_REPORT_HOUR = int(\n",
        "    os.getenv(\n",
        "        \"WEEKLY_REPORT_HOUR\",\n",
        "        \"17\",\n",
        "    )\n",
        ")\n",
        "\n",
        "WEEKLY_REPORT_MINUTE = int(\n",
        "    os.getenv(\n",
        "        \"WEEKLY_REPORT_MINUTE\",\n",
        "        \"0\",\n",
        "    )\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# JOB WRAPPER\n",
        "# =========================================================\n",
        "\n",
        "def run_job(\n",
        "    name: str,\n",
        "    function: Callable,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Safely execute an automation job.\n",
        "\n",
        "    A failure in one agent will not stop\n",
        "    the scheduler or other agents.\n",
        "    \"\"\"\n",
        "\n",
        "    start = datetime.now()\n",
        "\n",
        "    logger.info(\n",
        "        \"▶ Starting job: %s\",\n",
        "        name,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        result = function()\n",
        "\n",
        "        elapsed = (\n",
        "            datetime.now()\n",
        "            - start\n",
        "        ).total_seconds()\n",
        "\n",
        "        logger.info(\n",
        "            \"✓ Job completed: %s \"\n",
        "            \"(%.2fs)\",\n",
        "            name,\n",
        "            elapsed,\n",
        "        )\n",
        "\n",
        "        if result is not None:\n",
        "\n",
        "            logger.info(\n",
        "                \"Job result [%s]: %s\",\n",
        "                name,\n",
        "                result,\n",
        "            )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"✗ Job failed: %s\",\n",
        "            name,\n",
        "        )\n",
        "\n",
        "        logger.error(\n",
        "            \"Error: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        logger.debug(\n",
        "            traceback.format_exc()\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# AGENT IMPORTS\n",
        "# =========================================================\n",
        "\n",
        "def load_agents():\n",
        "    \"\"\"\n",
        "    Import agents lazily.\n",
        "\n",
        "    Lazy imports prevent the scheduler from\n",
        "    failing during startup if one optional\n",
        "    dependency is unavailable.\n",
        "    \"\"\"\n",
        "\n",
        "    agents = {}\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.news_agent import (\n",
        "            run_daily_news,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"daily_news\"\n",
        "        ] = run_daily_news\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"News agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.stem_tip_agent import (\n",
        "            run_stem_tip,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"stem_tip\"\n",
        "        ] = run_stem_tip\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"STEM tip agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.project_agent import (\n",
        "            run_project_idea,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"project_idea\"\n",
        "        ] = run_project_idea\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Project agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.weekly_report_agent import (\n",
        "            run_weekly_report,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"weekly_report\"\n",
        "        ] = run_weekly_report\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Weekly report agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.competition_agent import (\n",
        "            run_competition_update,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"competition\"\n",
        "        ] = run_competition_update\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Competition agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    try:\n",
        "\n",
        "        from agents.class_agent import (\n",
        "            run_class_update,\n",
        "        )\n",
        "\n",
        "        agents[\n",
        "            \"class_update\"\n",
        "        ] = run_class_update\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Class agent unavailable: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "    return agents\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# JOB REGISTRATION\n",
        "# =========================================================\n",
        "\n",
        "def create_scheduler(\n",
        "    agents: Optional[\n",
        "        dict[str, Callable]\n",
        "    ] = None,\n",
        ") -> BlockingScheduler:\n",
        "    \"\"\"\n",
        "    Create and configure APScheduler.\n",
        "    \"\"\"\n",
        "\n",
        "    if agents is None:\n",
        "\n",
        "        agents = load_agents()\n",
        "\n",
        "    scheduler = BlockingScheduler(\n",
        "        timezone=TIMEZONE\n",
        "    )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # DAILY AI / ROBOTICS NEWS\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"daily_news\" in agents:\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                hour=NEWS_HOUR,\n",
        "                minute=NEWS_MINUTE,\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"Daily AI/Robotics News\",\n",
        "                agents[\n",
        "                    \"daily_news\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"daily_news\",\n",
        "            name=\"Daily AI/Robotics News\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=3600,\n",
        "        )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # DAILY STEM TIP\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"stem_tip\" in agents:\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                hour=STEM_TIP_HOUR,\n",
        "                minute=STEM_TIP_MINUTE,\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"Daily STEM Tip\",\n",
        "                agents[\n",
        "                    \"stem_tip\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"daily_stem_tip\",\n",
        "            name=\"Daily STEM Tip\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=3600,\n",
        "        )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # DAILY PROJECT IDEA\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"project_idea\" in agents:\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                hour=PROJECT_HOUR,\n",
        "                minute=PROJECT_MINUTE,\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"Daily Project Idea\",\n",
        "                agents[\n",
        "                    \"project_idea\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"daily_project_idea\",\n",
        "            name=\"Daily Project Idea\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=3600,\n",
        "        )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # COMPETITION UPDATE\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"competition\" in agents:\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                hour=COMPETITION_HOUR,\n",
        "                minute=COMPETITION_MINUTE,\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"Competition Update\",\n",
        "                agents[\n",
        "                    \"competition\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"competition_update\",\n",
        "            name=\"Competition Update\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=3600,\n",
        "        )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # WEEKLY REPORT\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"weekly_report\" in agents:\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                day_of_week=(\n",
        "                    WEEKLY_REPORT_DAY\n",
        "                ),\n",
        "                hour=(\n",
        "                    WEEKLY_REPORT_HOUR\n",
        "                ),\n",
        "                minute=(\n",
        "                    WEEKLY_REPORT_MINUTE\n",
        "                ),\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"Weekly STEM Progress Report\",\n",
        "                agents[\n",
        "                    \"weekly_report\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"weekly_report\",\n",
        "            name=\"Weekly STEM Progress Report\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=7200,\n",
        "        )\n",
        "\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # CLASS UPDATE\n",
        "    #\n",
        "    # This is intentionally not scheduled every day\n",
        "    # by default because class data needs to be entered\n",
        "    # first.\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if \"class_update\" in agents:\n",
        "\n",
        "        class_hour = int(\n",
        "            os.getenv(\n",
        "                \"CLASS_UPDATE_HOUR\",\n",
        "                \"16\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "        class_minute = int(\n",
        "            os.getenv(\n",
        "                \"CLASS_UPDATE_MINUTE\",\n",
        "                \"30\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "        scheduler.add_job(\n",
        "            run_job,\n",
        "            trigger=CronTrigger(\n",
        "                hour=class_hour,\n",
        "                minute=class_minute,\n",
        "                timezone=TIMEZONE,\n",
        "            ),\n",
        "            args=[\n",
        "                \"STEM Class Update\",\n",
        "                agents[\n",
        "                    \"class_update\"\n",
        "                ],\n",
        "            ],\n",
        "            id=\"class_update\",\n",
        "            name=\"STEM Class Update\",\n",
        "            replace_existing=True,\n",
        "            max_instances=1,\n",
        "            coalesce=True,\n",
        "            misfire_grace_time=3600,\n",
        "        )\n",
        "\n",
        "\n",
        "    return scheduler\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# LIST JOBS\n",
        "# =========================================================\n",
        "\n",
        "def print_jobs(\n",
        "    scheduler: BlockingScheduler,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Print all scheduled jobs.\n",
        "    \"\"\"\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 75)\n",
        "    print(\"AI STEM AUTOMATION SCHEDULE\")\n",
        "    print(\"=\" * 75)\n",
        "\n",
        "    jobs = scheduler.get_jobs()\n",
        "\n",
        "    if not jobs:\n",
        "\n",
        "        print(\n",
        "            \"No jobs are currently registered.\"\n",
        "        )\n",
        "\n",
        "    for job in jobs:\n",
        "\n",
        "        print(\n",
        "            f\"\\n{job.name}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"  ID: \"\n",
        "            f\"{job.id}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"  Next run: \"\n",
        "            f\"{job.next_run_time}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"  Trigger: \"\n",
        "            f\"{job.trigger}\"\n",
        "        )\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 75)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# START SCHEDULER\n",
        "# =========================================================\n",
        "\n",
        "def start_scheduler() -> None:\n",
        "    \"\"\"\n",
        "    Start the automation scheduler.\n",
        "    \"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting AI STEM Automation Scheduler\"\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Timezone: %s\",\n",
        "        TIMEZONE,\n",
        "    )\n",
        "\n",
        "    agents = load_agents()\n",
        "\n",
        "    logger.info(\n",
        "        \"Loaded agents: %s\",\n",
        "        \", \".join(\n",
        "            agents.keys()\n",
        "        )\n",
        "        if agents\n",
        "        else \"NONE\",\n",
        "    )\n",
        "\n",
        "    scheduler = create_scheduler(\n",
        "        agents\n",
        "    )\n",
        "\n",
        "    print_jobs(\n",
        "        scheduler\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Scheduler is running...\"\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        scheduler.start()\n",
        "\n",
        "    except (\n",
        "        KeyboardInterrupt,\n",
        "        SystemExit,\n",
        "    ):\n",
        "\n",
        "        logger.info(\n",
        "            \"Stopping scheduler...\"\n",
        "        )\n",
        "\n",
        "        if scheduler.running:\n",
        "\n",
        "            scheduler.shutdown(\n",
        "                wait=True\n",
        "            )\n",
        "\n",
        "        logger.info(\n",
        "            \"Scheduler stopped.\"\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RUN A SINGLE JOB MANUALLY\n",
        "# =========================================================\n",
        "\n",
        "def run_now(\n",
        "    job_name: str,\n",
        ") -> bool:\n",
        "    \"\"\"\n",
        "    Manually run an agent immediately.\n",
        "\n",
        "    Example:\n",
        "\n",
        "        python services/jobs.py news\n",
        "        python services/jobs.py tip\n",
        "        python services/jobs.py project\n",
        "        python services/jobs.py competition\n",
        "        python services/jobs.py weekly\n",
        "    \"\"\"\n",
        "\n",
        "    agents = load_agents()\n",
        "\n",
        "    aliases = {\n",
        "\n",
        "        \"news\":\n",
        "            \"daily_news\",\n",
        "\n",
        "        \"tip\":\n",
        "            \"stem_tip\",\n",
        "\n",
        "        \"project\":\n",
        "            \"project_idea\",\n",
        "\n",
        "        \"competition\":\n",
        "            \"competition\",\n",
        "\n",
        "        \"weekly\":\n",
        "            \"weekly_report\",\n",
        "\n",
        "        \"class\":\n",
        "            \"class_update\",\n",
        "    }\n",
        "\n",
        "    agent_name = aliases.get(\n",
        "        job_name.lower(),\n",
        "        job_name.lower(),\n",
        "    )\n",
        "\n",
        "    function = agents.get(\n",
        "        agent_name\n",
        "    )\n",
        "\n",
        "    if function is None:\n",
        "\n",
        "        logger.error(\n",
        "            \"Unknown or unavailable job: %s\",\n",
        "            job_name,\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"Available jobs:\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  news\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  tip\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  project\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  competition\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  weekly\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            \"  class\"\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "    run_job(\n",
        "        agent_name,\n",
        "        function,\n",
        "    )\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    import sys\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(name)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    # Example:\n",
        "    #\n",
        "    # python services/jobs.py\n",
        "    #\n",
        "    # Starts scheduler.\n",
        "    #\n",
        "    # python services/jobs.py news\n",
        "    #\n",
        "    # Runs news immediately.\n",
        "\n",
        "    if len(sys.argv) > 1:\n",
        "\n",
        "        command = (\n",
        "            sys.argv[1]\n",
        "            .strip()\n",
        "            .lower()\n",
        "        )\n",
        "\n",
        "        if command in {\n",
        "            \"news\",\n",
        "            \"tip\",\n",
        "            \"project\",\n",
        "            \"competition\",\n",
        "            \"weekly\",\n",
        "            \"class\",\n",
        "        }:\n",
        "\n",
        "            run_now(\n",
        "                command\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            print(\n",
        "                \"Unknown command.\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"Use:\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py news\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py tip\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py project\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py competition\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py weekly\"\n",
        "            )\n",
        "\n",
        "            print(\n",
        "                \"  python services/jobs.py class\"\n",
        "            )\n",
        "\n",
        "    else:\n",
        "\n",
        "        start_scheduler()"
      ],
      "metadata": {
        "id": "WxYzG7UGx0xg"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}