{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMzc4j7eIgu1ylgiP1sjMNF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/news_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "agents/news_agent.py\n",
        "\n",
        "Daily AI & Robotics News Agent\n",
        "\n",
        "Responsibilities:\n",
        "- Collect latest AI and robotics news\n",
        "- Filter duplicate articles\n",
        "- Send articles to Gemini for summarization\n",
        "- Store processed news in SQLite\n",
        "- Generate an email-ready HTML newsletter\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import html\n",
        "import logging\n",
        "from dataclasses import dataclass\n",
        "from datetime import datetime\n",
        "from typing import Any\n",
        "from urllib.parse import urlparse\n",
        "\n",
        "import database\n",
        "from config import (\n",
        "    AI_NEWS_TOPICS,\n",
        "    NEWS_LIMIT,\n",
        "    NEWS_LOOKBACK_HOURS,\n",
        "    ROBOTICS_NEWS_LIMIT,\n",
        "    ROBOTICS_NEWS_TOPICS,\n",
        ")\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\"AI-STEM-Automation.NewsAgent\")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATA MODEL\n",
        "# =========================================================\n",
        "\n",
        "@dataclass\n",
        "class NewsArticle:\n",
        "    \"\"\"Represents one news article.\"\"\"\n",
        "\n",
        "    title: str\n",
        "    url: str\n",
        "    source: str = \"\"\n",
        "    category: str = \"\"\n",
        "    published_at: str = \"\"\n",
        "    description: str = \"\"\n",
        "    summary: str = \"\"\n",
        "    importance: str = \"Medium\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NEWS SOURCES\n",
        "# =========================================================\n",
        "\n",
        "# These are RSS feeds, which avoids scraping websites directly.\n",
        "# You can add/remove feeds later.\n",
        "\n",
        "AI_RSS_FEEDS = [\n",
        "    \"https://feeds.arstechnica.com/arstechnica/technology-lab\",\n",
        "    \"https://www.technologyreview.com/feed/\",\n",
        "]\n",
        "\n",
        "ROBOTICS_RSS_FEEDS = [\n",
        "    \"https://spectrum.ieee.org/feeds/topic/robotics\",\n",
        "]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# OPTIONAL RSS IMPORT\n",
        "# =========================================================\n",
        "\n",
        "def load_rss_library():\n",
        "    \"\"\"\n",
        "    Import feedparser only when needed.\n",
        "\n",
        "    Install with:\n",
        "        pip install feedparser\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "        import feedparser\n",
        "\n",
        "        return feedparser\n",
        "\n",
        "    except ImportError as exc:\n",
        "        raise ImportError(\n",
        "            \"feedparser is required for news collection. \"\n",
        "            \"Install it with: pip install feedparser\"\n",
        "        ) from exc\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPERS\n",
        "# =========================================================\n",
        "\n",
        "def clean_text(value: Any) -> str:\n",
        "    \"\"\"Convert HTML/text input into clean text.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return \"\"\n",
        "\n",
        "    text = str(value)\n",
        "\n",
        "    # Basic HTML cleanup\n",
        "    text = text.replace(\"<p>\", \" \")\n",
        "    text = text.replace(\"</p>\", \" \")\n",
        "    text = text.replace(\"<br>\", \" \")\n",
        "    text = text.replace(\"<br/>\", \" \")\n",
        "    text = text.replace(\"<br />\", \" \")\n",
        "\n",
        "    return \" \".join(text.split())\n",
        "\n",
        "\n",
        "def get_source_from_url(url: str) -> str:\n",
        "    \"\"\"Extract a readable source name from a URL.\"\"\"\n",
        "\n",
        "    try:\n",
        "        hostname = urlparse(url).netloc.lower()\n",
        "\n",
        "        if hostname.startswith(\"www.\"):\n",
        "            hostname = hostname[4:]\n",
        "\n",
        "        return hostname\n",
        "\n",
        "    except Exception:\n",
        "        return \"\"\n",
        "\n",
        "\n",
        "def normalize_url(url: str) -> str:\n",
        "    \"\"\"Normalize article URL for duplicate detection.\"\"\"\n",
        "\n",
        "    if not url:\n",
        "        return \"\"\n",
        "\n",
        "    return url.strip().rstrip(\"/\")\n",
        "\n",
        "\n",
        "def is_valid_article(title: str, url: str) -> bool:\n",
        "    \"\"\"Basic article validation.\"\"\"\n",
        "\n",
        "    if not title:\n",
        "        return False\n",
        "\n",
        "    if len(title.strip()) < 10:\n",
        "        return False\n",
        "\n",
        "    if not url.startswith((\"http://\", \"https://\")):\n",
        "        return False\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RSS COLLECTION\n",
        "# =========================================================\n",
        "\n",
        "def collect_from_feed(\n",
        "    feed_url: str,\n",
        "    category: str,\n",
        "    limit: int = 10,\n",
        ") -> list[NewsArticle]:\n",
        "    \"\"\"Collect articles from one RSS feed.\"\"\"\n",
        "\n",
        "    feedparser = load_rss_library()\n",
        "\n",
        "    logger.info(\n",
        "        \"Reading RSS feed: %s\",\n",
        "        feed_url,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "        feed = feedparser.parse(feed_url)\n",
        "\n",
        "    except Exception as exc:\n",
        "        logger.error(\n",
        "            \"Failed to read feed %s: %s\",\n",
        "            feed_url,\n",
        "            exc,\n",
        "        )\n",
        "        return []\n",
        "\n",
        "    articles: list[NewsArticle] = []\n",
        "\n",
        "    entries = getattr(feed, \"entries\", [])\n",
        "\n",
        "    for entry in entries[:limit]:\n",
        "\n",
        "        title = clean_text(\n",
        "            getattr(entry, \"title\", \"\")\n",
        "        )\n",
        "\n",
        "        url = normalize_url(\n",
        "            getattr(entry, \"link\", \"\")\n",
        "        )\n",
        "\n",
        "        description = clean_text(\n",
        "            getattr(\n",
        "                entry,\n",
        "                \"summary\",\n",
        "                getattr(entry, \"description\", \"\"),\n",
        "            )\n",
        "        )\n",
        "\n",
        "        published_at = clean_text(\n",
        "            getattr(\n",
        "                entry,\n",
        "                \"published\",\n",
        "                getattr(entry, \"updated\", \"\"),\n",
        "            )\n",
        "        )\n",
        "\n",
        "        if not is_valid_article(title, url):\n",
        "            continue\n",
        "\n",
        "        articles.append(\n",
        "            NewsArticle(\n",
        "                title=title,\n",
        "                url=url,\n",
        "                source=get_source_from_url(url),\n",
        "                category=category,\n",
        "                published_at=published_at,\n",
        "                description=description[:2000],\n",
        "            )\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"Collected %d articles from %s\",\n",
        "        len(articles),\n",
        "        feed_url,\n",
        "    )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COLLECT AI NEWS\n",
        "# =========================================================\n",
        "\n",
        "def collect_ai_news() -> list[NewsArticle]:\n",
        "    \"\"\"Collect AI-related news.\"\"\"\n",
        "\n",
        "    articles: list[NewsArticle] = []\n",
        "\n",
        "    for feed_url in AI_RSS_FEEDS:\n",
        "\n",
        "        articles.extend(\n",
        "            collect_from_feed(\n",
        "                feed_url=feed_url,\n",
        "                category=\"AI\",\n",
        "                limit=NEWS_LIMIT * 2,\n",
        "            )\n",
        "        )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COLLECT ROBOTICS NEWS\n",
        "# =========================================================\n",
        "\n",
        "def collect_robotics_news() -> list[NewsArticle]:\n",
        "    \"\"\"Collect robotics-related news.\"\"\"\n",
        "\n",
        "    articles: list[NewsArticle] = []\n",
        "\n",
        "    for feed_url in ROBOTICS_RSS_FEEDS:\n",
        "\n",
        "        articles.extend(\n",
        "            collect_from_feed(\n",
        "                feed_url=feed_url,\n",
        "                category=\"Robotics\",\n",
        "                limit=ROBOTICS_NEWS_LIMIT * 2,\n",
        "            )\n",
        "        )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DUPLICATE FILTER\n",
        "# =========================================================\n",
        "\n",
        "def remove_duplicates(\n",
        "    articles: list[NewsArticle],\n",
        ") -> list[NewsArticle]:\n",
        "    \"\"\"Remove duplicate URLs and titles.\"\"\"\n",
        "\n",
        "    unique: list[NewsArticle] = []\n",
        "\n",
        "    seen_urls: set[str] = set()\n",
        "    seen_titles: set[str] = set()\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        normalized_url = normalize_url(\n",
        "            article.url\n",
        "        )\n",
        "\n",
        "        normalized_title = (\n",
        "            article.title\n",
        "            .lower()\n",
        "            .strip()\n",
        "        )\n",
        "\n",
        "        if normalized_url in seen_urls:\n",
        "            continue\n",
        "\n",
        "        if normalized_title in seen_titles:\n",
        "            continue\n",
        "\n",
        "        if database.news_exists(normalized_url):\n",
        "            logger.info(\n",
        "                \"Skipping previously processed article: %s\",\n",
        "                article.title,\n",
        "            )\n",
        "            continue\n",
        "\n",
        "        if database.news_title_exists(\n",
        "            article.title\n",
        "        ):\n",
        "            continue\n",
        "\n",
        "        seen_urls.add(normalized_url)\n",
        "        seen_titles.add(normalized_title)\n",
        "\n",
        "        unique.append(article)\n",
        "\n",
        "    logger.info(\n",
        "        \"Articles after duplicate filtering: %d\",\n",
        "        len(unique),\n",
        "    )\n",
        "\n",
        "    return unique\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI\n",
        "# =========================================================\n",
        "\n",
        "def summarize_with_gemini(\n",
        "    articles: list[NewsArticle],\n",
        ") -> list[NewsArticle]:\n",
        "    \"\"\"\n",
        "    Ask the shared Gemini service to summarize the articles.\n",
        "\n",
        "    Expected services/gemini.py interface:\n",
        "\n",
        "        summarize_news(articles)\n",
        "\n",
        "    The function should return a list of dictionaries.\n",
        "    \"\"\"\n",
        "\n",
        "    if not articles:\n",
        "        return []\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gemini import summarize_news\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"Gemini service is not available.\"\n",
        "        )\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gemini.py before running \"\n",
        "            \"the news agent.\"\n",
        "        ) from exc\n",
        "\n",
        "    payload = []\n",
        "\n",
        "    for index, article in enumerate(articles):\n",
        "\n",
        "        payload.append(\n",
        "            {\n",
        "                \"id\": index,\n",
        "                \"title\": article.title,\n",
        "                \"source\": article.source,\n",
        "                \"category\": article.category,\n",
        "                \"description\": article.description,\n",
        "                \"url\": article.url,\n",
        "            }\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"Sending %d articles to Gemini...\",\n",
        "        len(payload),\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        results = summarize_news(payload)\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gemini summarization failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return articles\n",
        "\n",
        "    if not isinstance(results, list):\n",
        "        logger.warning(\n",
        "            \"Gemini returned unexpected result.\"\n",
        "        )\n",
        "        return articles\n",
        "\n",
        "    for index, result in enumerate(results):\n",
        "\n",
        "        if index >= len(articles):\n",
        "            break\n",
        "\n",
        "        if not isinstance(result, dict):\n",
        "            continue\n",
        "\n",
        "        articles[index].summary = clean_text(\n",
        "            result.get(\"summary\", \"\")\n",
        "        )\n",
        "\n",
        "        articles[index].importance = clean_text(\n",
        "            result.get(\"importance\", \"Medium\")\n",
        "        )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RANK NEWS\n",
        "# =========================================================\n",
        "\n",
        "def rank_articles(\n",
        "    articles: list[NewsArticle],\n",
        ") -> list[NewsArticle]:\n",
        "    \"\"\"\n",
        "    Rank articles by AI-assigned importance.\n",
        "\n",
        "    High > Medium > Low\n",
        "    \"\"\"\n",
        "\n",
        "    priority = {\n",
        "        \"high\": 3,\n",
        "        \"medium\": 2,\n",
        "        \"low\": 1,\n",
        "    }\n",
        "\n",
        "    articles.sort(\n",
        "        key=lambda article: priority.get(\n",
        "            article.importance.lower(),\n",
        "            2,\n",
        "        ),\n",
        "        reverse=True,\n",
        "    )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAVE NEWS\n",
        "# =========================================================\n",
        "\n",
        "def save_articles(\n",
        "    articles: list[NewsArticle],\n",
        ") -> None:\n",
        "    \"\"\"Save processed articles to the database.\"\"\"\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        database.add_news(\n",
        "            title=article.title,\n",
        "            url=article.url,\n",
        "            source=article.source,\n",
        "            category=article.category,\n",
        "            summary=article.summary,\n",
        "            published_at=article.published_at,\n",
        "        )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML ESCAPING\n",
        "# =========================================================\n",
        "\n",
        "def safe_html(value: str) -> str:\n",
        "    \"\"\"Escape text before inserting it into HTML.\"\"\"\n",
        "\n",
        "    return html.escape(\n",
        "        value or \"\",\n",
        "        quote=True,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML NEWSLETTER\n",
        "# =========================================================\n",
        "\n",
        "def generate_html_email(\n",
        "    articles: list[NewsArticle],\n",
        ") -> str:\n",
        "    \"\"\"Generate a professional HTML newsletter.\"\"\"\n",
        "\n",
        "    today = datetime.now().strftime(\n",
        "        \"%d %B %Y\"\n",
        "    )\n",
        "\n",
        "    article_blocks = []\n",
        "\n",
        "    for number, article in enumerate(\n",
        "        articles,\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        title = safe_html(\n",
        "            article.title\n",
        "        )\n",
        "\n",
        "        source = safe_html(\n",
        "            article.source\n",
        "        )\n",
        "\n",
        "        category = safe_html(\n",
        "            article.category\n",
        "        )\n",
        "\n",
        "        summary = safe_html(\n",
        "            article.summary\n",
        "            or article.description\n",
        "            or \"No summary available.\"\n",
        "        )\n",
        "\n",
        "        url = safe_html(\n",
        "            article.url\n",
        "        )\n",
        "\n",
        "        importance = safe_html(\n",
        "            article.importance\n",
        "        )\n",
        "\n",
        "        article_blocks.append(\n",
        "            f\"\"\"\n",
        "            <div style=\"\n",
        "                margin-bottom:24px;\n",
        "                padding:18px;\n",
        "                border:1px solid #dddddd;\n",
        "                border-radius:10px;\n",
        "            \">\n",
        "\n",
        "                <div style=\"\n",
        "                    font-size:12px;\n",
        "                    color:#666666;\n",
        "                    margin-bottom:6px;\n",
        "                \">\n",
        "                    {category} · {importance}\n",
        "                </div>\n",
        "\n",
        "                <h2 style=\"\n",
        "                    margin:0 0 8px 0;\n",
        "                    font-size:19px;\n",
        "                \">\n",
        "                    {number}. {title}\n",
        "                </h2>\n",
        "\n",
        "                <p style=\"\n",
        "                    color:#555555;\n",
        "                    font-size:13px;\n",
        "                \">\n",
        "                    Source: {source}\n",
        "                </p>\n",
        "\n",
        "                <p style=\"\n",
        "                    font-size:15px;\n",
        "                    line-height:1.6;\n",
        "                \">\n",
        "                    {summary}\n",
        "                </p>\n",
        "\n",
        "                <a\n",
        "                    href=\"{url}\"\n",
        "                    style=\"\n",
        "                        display:inline-block;\n",
        "                        padding:9px 14px;\n",
        "                        background:#111827;\n",
        "                        color:white;\n",
        "                        text-decoration:none;\n",
        "                        border-radius:6px;\n",
        "                    \"\n",
        "                >\n",
        "                    Read Full Story\n",
        "                </a>\n",
        "\n",
        "            </div>\n",
        "            \"\"\"\n",
        "        )\n",
        "\n",
        "    body = \"\".join(article_blocks)\n",
        "\n",
        "    return f\"\"\"\n",
        "    <!DOCTYPE html>\n",
        "\n",
        "    <html>\n",
        "\n",
        "    <head>\n",
        "        <meta charset=\"UTF-8\">\n",
        "        <title>Daily AI & Robotics News</title>\n",
        "    </head>\n",
        "\n",
        "    <body style=\"\n",
        "        margin:0;\n",
        "        padding:0;\n",
        "        background:#f4f6f8;\n",
        "        font-family:Arial,Helvetica,sans-serif;\n",
        "    \">\n",
        "\n",
        "        <div style=\"\n",
        "            max-width:760px;\n",
        "            margin:30px auto;\n",
        "            background:white;\n",
        "            padding:30px;\n",
        "            border-radius:12px;\n",
        "        \">\n",
        "\n",
        "            <h1 style=\"\n",
        "                margin-top:0;\n",
        "                font-size:28px;\n",
        "            \">\n",
        "                🤖 Daily AI & Robotics News\n",
        "            </h1>\n",
        "\n",
        "            <p style=\"\n",
        "                color:#666666;\n",
        "                font-size:14px;\n",
        "            \">\n",
        "                {today}\n",
        "            </p>\n",
        "\n",
        "            <hr style=\"\n",
        "                border:none;\n",
        "                border-top:1px solid #eeeeee;\n",
        "                margin:25px 0;\n",
        "            \">\n",
        "\n",
        "            {body}\n",
        "\n",
        "            <hr style=\"\n",
        "                border:none;\n",
        "                border-top:1px solid #eeeeee;\n",
        "                margin:25px 0;\n",
        "            \">\n",
        "\n",
        "            <p style=\"\n",
        "                color:#777777;\n",
        "                font-size:13px;\n",
        "            \">\n",
        "                Generated automatically by\n",
        "                <strong>AI STEM Automation Hub</strong>.\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "\n",
        "    </body>\n",
        "\n",
        "    </html>\n",
        "    \"\"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PLAIN TEXT EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_text_email(\n",
        "    articles: list[NewsArticle],\n",
        ") -> str:\n",
        "    \"\"\"Generate plain-text fallback email.\"\"\"\n",
        "\n",
        "    today = datetime.now().strftime(\n",
        "        \"%d %B %Y\"\n",
        "    )\n",
        "\n",
        "    lines = [\n",
        "        \"DAILY AI & ROBOTICS NEWS\",\n",
        "        f\"Date: {today}\",\n",
        "        \"\",\n",
        "    ]\n",
        "\n",
        "    for number, article in enumerate(\n",
        "        articles,\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        lines.extend(\n",
        "            [\n",
        "                f\"{number}. {article.title}\",\n",
        "                f\"Category: {article.category}\",\n",
        "                f\"Source: {article.source}\",\n",
        "                \"\",\n",
        "                (\n",
        "                    article.summary\n",
        "                    or article.description\n",
        "                    or \"No summary available.\"\n",
        "                ),\n",
        "                \"\",\n",
        "                article.url,\n",
        "                \"\",\n",
        "                \"-\" * 60,\n",
        "                \"\",\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# EMAIL DELIVERY\n",
        "# =========================================================\n",
        "\n",
        "def send_news_email(\n",
        "    articles: list[NewsArticle],\n",
        ") -> bool:\n",
        "    \"\"\"Send the newsletter using the Gmail service.\"\"\"\n",
        "\n",
        "    if not articles:\n",
        "        logger.warning(\n",
        "            \"No articles available. Email not sent.\"\n",
        "        )\n",
        "        return False\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gmail import send_email\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gmail.py before \"\n",
        "            \"sending email.\"\n",
        "        ) from exc\n",
        "\n",
        "    subject = (\n",
        "        \"🤖 Daily AI & Robotics News - \"\n",
        "        + datetime.now().strftime(\"%d %b %Y\")\n",
        "    )\n",
        "\n",
        "    html_body = generate_html_email(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    text_body = generate_text_email(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        send_email(\n",
        "            subject=subject,\n",
        "            html_body=html_body,\n",
        "            text_body=text_body,\n",
        "            email_type=\"daily_news\",\n",
        "        )\n",
        "\n",
        "        logger.info(\n",
        "            \"Daily news email sent successfully.\"\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Failed to send news email: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# MAIN AGENT\n",
        "# =========================================================\n",
        "\n",
        "def run_news_agent() -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Run the complete Daily AI/Robotics News Agent.\n",
        "\n",
        "    Returns a status dictionary.\n",
        "    \"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"============================================\"\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting Daily AI/Robotics News Agent\"\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Lookback window: %s hours\",\n",
        "        NEWS_LOOKBACK_HOURS,\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 1. Collect AI news\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    ai_articles = collect_ai_news()\n",
        "\n",
        "    logger.info(\n",
        "        \"AI articles collected: %d\",\n",
        "        len(ai_articles),\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 2. Collect robotics news\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    robotics_articles = collect_robotics_news()\n",
        "\n",
        "    logger.info(\n",
        "        \"Robotics articles collected: %d\",\n",
        "        len(robotics_articles),\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 3. Combine\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    articles = (\n",
        "        ai_articles\n",
        "        + robotics_articles\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 4. Remove duplicates\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    articles = remove_duplicates(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    if not articles:\n",
        "\n",
        "        logger.warning(\n",
        "            \"No new articles found.\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"success\": False,\n",
        "            \"articles_found\": 0,\n",
        "            \"email_sent\": False,\n",
        "            \"message\": \"No new articles found.\",\n",
        "        }\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 5. Limit articles\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    max_articles = (\n",
        "        NEWS_LIMIT\n",
        "        + ROBOTICS_NEWS_LIMIT\n",
        "    )\n",
        "\n",
        "    articles = articles[\n",
        "        :max_articles\n",
        "    ]\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 6. Gemini summarization\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    articles = summarize_with_gemini(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 7. Rank\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    articles = rank_articles(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 8. Save to database\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    save_articles(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 9. Send email\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    email_sent = send_news_email(\n",
        "        articles\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"News agent completed.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"success\": True,\n",
        "        \"articles_found\": len(articles),\n",
        "        \"email_sent\": email_sent,\n",
        "        \"articles\": articles,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    result = run_news_agent()\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"NEWS AGENT RESULT\")\n",
        "    print(\"=\" * 60)\n",
        "    print(\n",
        "        f\"Success       : \"\n",
        "        f\"{result.get('success')}\"\n",
        "    )\n",
        "    print(\n",
        "        f\"Articles      : \"\n",
        "        f\"{result.get('articles_found', 0)}\"\n",
        "    )\n",
        "    print(\n",
        "        f\"Email sent    : \"\n",
        "        f\"{result.get('email_sent', False)}\"\n",
        "    )\n",
        "    print(\"=\" * 60)"
      ],
      "metadata": {
        "id": "xhUcJEaKt8D5"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}