{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNElCD/kjxR96zhQv5hzejy",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/project_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "agents/project_agent.py\n",
        "\n",
        "Daily STEM Project Idea Agent\n",
        "\n",
        "Responsibilities:\n",
        "- Generate one Arduino/ESP32/Robotics project daily\n",
        "- Select suitable grade and difficulty\n",
        "- Generate components\n",
        "- Generate circuit concept\n",
        "- Generate working/code outline\n",
        "- Avoid duplicate projects\n",
        "- Store projects in SQLite\n",
        "- Generate HTML/text email\n",
        "- Send through Gmail SMTP\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import html\n",
        "import json\n",
        "import logging\n",
        "import random\n",
        "from datetime import datetime\n",
        "from typing import Any\n",
        "\n",
        "import database\n",
        "\n",
        "from config import (\n",
        "    PROJECT_DIFFICULTIES,\n",
        "    STEM_DOMAINS,\n",
        "    STEM_GRADES,\n",
        ")\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.ProjectAgent\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SETTINGS\n",
        "# =========================================================\n",
        "\n",
        "MAX_PREVIOUS_PROJECTS = 40\n",
        "\n",
        "\n",
        "PROJECT_DOMAINS = [\n",
        "    \"Arduino\",\n",
        "    \"ESP32\",\n",
        "    \"Robotics\",\n",
        "    \"IoT\",\n",
        "    \"Electronics\",\n",
        "    \"Sensors\",\n",
        "    \"AI\",\n",
        "    \"Computer Vision\",\n",
        "    \"Automation\",\n",
        "    \"3D Printing\",\n",
        "]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPERS\n",
        "# =========================================================\n",
        "\n",
        "def clean_text(value: Any) -> str:\n",
        "    \"\"\"Clean text returned by the AI.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return \"\"\n",
        "\n",
        "    return \" \".join(\n",
        "        str(value).strip().split()\n",
        "    )\n",
        "\n",
        "\n",
        "def safe_html(value: str) -> str:\n",
        "    \"\"\"Escape text for HTML.\"\"\"\n",
        "\n",
        "    return html.escape(\n",
        "        value or \"\",\n",
        "        quote=True,\n",
        "    )\n",
        "\n",
        "\n",
        "def format_list(value: Any) -> list[str]:\n",
        "    \"\"\"Convert AI output into a clean list.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return []\n",
        "\n",
        "    if isinstance(value, str):\n",
        "\n",
        "        return [\n",
        "            clean_text(value)\n",
        "        ]\n",
        "\n",
        "    if not isinstance(value, list):\n",
        "\n",
        "        return []\n",
        "\n",
        "    return [\n",
        "        clean_text(item)\n",
        "        for item in value\n",
        "        if clean_text(item)\n",
        "    ]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SELECT PARAMETERS\n",
        "# =========================================================\n",
        "\n",
        "def select_grade() -> str:\n",
        "    \"\"\"Select target grade.\"\"\"\n",
        "\n",
        "    return str(\n",
        "        random.choice(\n",
        "            STEM_GRADES\n",
        "        )\n",
        "    )\n",
        "\n",
        "\n",
        "def select_domain() -> str:\n",
        "    \"\"\"Select project domain.\"\"\"\n",
        "\n",
        "    return random.choice(\n",
        "        PROJECT_DOMAINS\n",
        "    )\n",
        "\n",
        "\n",
        "def select_difficulty() -> str:\n",
        "    \"\"\"Select difficulty.\"\"\"\n",
        "\n",
        "    return random.choice(\n",
        "        PROJECT_DIFFICULTIES\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PREVIOUS PROJECTS\n",
        "# =========================================================\n",
        "\n",
        "def get_previous_projects(\n",
        "    limit: int = MAX_PREVIOUS_PROJECTS,\n",
        ") -> list[str]:\n",
        "    \"\"\"Get recently generated project titles.\"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        with database.get_connection() as connection:\n",
        "\n",
        "            rows = connection.execute(\n",
        "                \"\"\"\n",
        "                SELECT title\n",
        "                FROM projects\n",
        "                ORDER BY created_at DESC\n",
        "                LIMIT ?\n",
        "                \"\"\",\n",
        "                (limit,),\n",
        "            ).fetchall()\n",
        "\n",
        "        return [\n",
        "            row[\"title\"]\n",
        "            for row in rows\n",
        "            if row[\"title\"]\n",
        "        ]\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Unable to read project history: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return []\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI PROJECT GENERATOR\n",
        "# =========================================================\n",
        "\n",
        "def generate_project_with_gemini(\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        "    previous_projects: list[str],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate a project using Gemini.\n",
        "\n",
        "    Expected interface:\n",
        "\n",
        "        generate_project_idea(...)\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gemini import (\n",
        "            generate_project_idea,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gemini.py before \"\n",
        "            \"running the project agent.\"\n",
        "        ) from exc\n",
        "\n",
        "    logger.info(\n",
        "        \"Generating project | Grade=%s | Domain=%s | Difficulty=%s\",\n",
        "        grade,\n",
        "        domain,\n",
        "        difficulty,\n",
        "    )\n",
        "\n",
        "    result = generate_project_idea(\n",
        "        grade=grade,\n",
        "        domain=domain,\n",
        "        difficulty=difficulty,\n",
        "        previous_projects=previous_projects,\n",
        "    )\n",
        "\n",
        "    if isinstance(result, str):\n",
        "\n",
        "        try:\n",
        "\n",
        "            result = json.loads(\n",
        "                result\n",
        "            )\n",
        "\n",
        "        except json.JSONDecodeError:\n",
        "\n",
        "            result = {\n",
        "                \"title\": \"Daily STEM Project\",\n",
        "                \"description\": result,\n",
        "                \"grade\": grade,\n",
        "                \"domain\": domain,\n",
        "                \"difficulty\": difficulty,\n",
        "                \"budget\": \"\",\n",
        "                \"components\": [],\n",
        "                \"circuit_concept\": \"\",\n",
        "                \"working\": [],\n",
        "                \"code_outline\": [],\n",
        "                \"learning_outcomes\": [],\n",
        "                \"extensions\": [],\n",
        "                \"safety\": \"\",\n",
        "            }\n",
        "\n",
        "    if not isinstance(result, dict):\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Gemini returned invalid project data.\"\n",
        "        )\n",
        "\n",
        "    return result\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NORMALIZE PROJECT\n",
        "# =========================================================\n",
        "\n",
        "def normalize_project(\n",
        "    project: dict[str, Any],\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"Normalize Gemini project output.\"\"\"\n",
        "\n",
        "    return {\n",
        "        \"title\": clean_text(\n",
        "            project.get(\n",
        "                \"title\",\n",
        "                \"Daily STEM Project\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"description\": clean_text(\n",
        "            project.get(\n",
        "                \"description\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"grade\": clean_text(\n",
        "            project.get(\n",
        "                \"grade\",\n",
        "                grade,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"domain\": clean_text(\n",
        "            project.get(\n",
        "                \"domain\",\n",
        "                domain,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"difficulty\": clean_text(\n",
        "            project.get(\n",
        "                \"difficulty\",\n",
        "                difficulty,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"budget\": clean_text(\n",
        "            project.get(\n",
        "                \"budget\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"components\": format_list(\n",
        "            project.get(\n",
        "                \"components\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"circuit_concept\": clean_text(\n",
        "            project.get(\n",
        "                \"circuit_concept\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"working\": format_list(\n",
        "            project.get(\n",
        "                \"working\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"code_outline\": format_list(\n",
        "            project.get(\n",
        "                \"code_outline\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"learning_outcomes\": format_list(\n",
        "            project.get(\n",
        "                \"learning_outcomes\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"extensions\": format_list(\n",
        "            project.get(\n",
        "                \"extensions\",\n",
        "                [],\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"safety\": clean_text(\n",
        "            project.get(\n",
        "                \"safety\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# VALIDATION\n",
        "# =========================================================\n",
        "\n",
        "def validate_project(\n",
        "    project: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"Validate generated project.\"\"\"\n",
        "\n",
        "    required = [\n",
        "        \"title\",\n",
        "        \"description\",\n",
        "        \"components\",\n",
        "    ]\n",
        "\n",
        "    for field in required:\n",
        "\n",
        "        value = project.get(\n",
        "            field\n",
        "        )\n",
        "\n",
        "        if not value:\n",
        "\n",
        "            logger.warning(\n",
        "                \"Missing project field: %s\",\n",
        "                field,\n",
        "            )\n",
        "\n",
        "            return False\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAVE PROJECT\n",
        "# =========================================================\n",
        "\n",
        "def save_project(\n",
        "    project: dict[str, Any],\n",
        ") -> int:\n",
        "    \"\"\"Save project to SQLite.\"\"\"\n",
        "\n",
        "    return database.add_project(\n",
        "\n",
        "        title=project[\"title\"],\n",
        "\n",
        "        domain=project[\"domain\"],\n",
        "\n",
        "        grade=project[\"grade\"],\n",
        "\n",
        "        difficulty=project[\"difficulty\"],\n",
        "\n",
        "        budget=project[\"budget\"],\n",
        "\n",
        "        components=json.dumps(\n",
        "            project[\"components\"],\n",
        "            ensure_ascii=False,\n",
        "        ),\n",
        "\n",
        "        description=project[\"description\"],\n",
        "\n",
        "        circuit_concept=(\n",
        "            project[\"circuit_concept\"]\n",
        "        ),\n",
        "\n",
        "        code_outline=json.dumps(\n",
        "            project[\"code_outline\"],\n",
        "            ensure_ascii=False,\n",
        "        ),\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_html_email(\n",
        "    project: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate project HTML email.\"\"\"\n",
        "\n",
        "    date_display = datetime.now().strftime(\n",
        "        \"%d %B %Y\"\n",
        "    )\n",
        "\n",
        "    components = project[\n",
        "        \"components\"\n",
        "    ]\n",
        "\n",
        "    working = project[\n",
        "        \"working\"\n",
        "    ]\n",
        "\n",
        "    code_outline = project[\n",
        "        \"code_outline\"\n",
        "    ]\n",
        "\n",
        "    learning_outcomes = project[\n",
        "        \"learning_outcomes\"\n",
        "    ]\n",
        "\n",
        "    extensions = project[\n",
        "        \"extensions\"\n",
        "    ]\n",
        "\n",
        "    component_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li>\n",
        "            {safe_html(component)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for component in components\n",
        "    )\n",
        "\n",
        "    working_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li style=\"\n",
        "            margin-bottom:8px;\n",
        "        \">\n",
        "            {safe_html(step)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for step in working\n",
        "    )\n",
        "\n",
        "    code_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li style=\"\n",
        "            margin-bottom:8px;\n",
        "        \">\n",
        "            <code>\n",
        "                {safe_html(step)}\n",
        "            </code>\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for step in code_outline\n",
        "    )\n",
        "\n",
        "    learning_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li>\n",
        "            {safe_html(item)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for item in learning_outcomes\n",
        "    )\n",
        "\n",
        "    extensions_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li>\n",
        "            {safe_html(item)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for item in extensions\n",
        "    )\n",
        "\n",
        "    safety_html = \"\"\n",
        "\n",
        "    if project[\"safety\"]:\n",
        "\n",
        "        safety_html = f\"\"\"\n",
        "        <div style=\"\n",
        "            margin-top:25px;\n",
        "            padding:15px;\n",
        "            background:#fff7ed;\n",
        "            border-left:4px solid #f97316;\n",
        "        \">\n",
        "\n",
        "            <strong>\n",
        "                ⚠️ Safety\n",
        "            </strong>\n",
        "\n",
        "            <p>\n",
        "                {safe_html(project[\"safety\"])}\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "        \"\"\"\n",
        "\n",
        "    return f\"\"\"\n",
        "    <!DOCTYPE html>\n",
        "\n",
        "    <html>\n",
        "\n",
        "    <head>\n",
        "\n",
        "        <meta charset=\"UTF-8\">\n",
        "\n",
        "        <title>\n",
        "            Daily STEM Project\n",
        "        </title>\n",
        "\n",
        "    </head>\n",
        "\n",
        "    <body style=\"\n",
        "        margin:0;\n",
        "        padding:0;\n",
        "        background:#f4f6f8;\n",
        "        font-family:Arial,Helvetica,sans-serif;\n",
        "    \">\n",
        "\n",
        "        <div style=\"\n",
        "            max-width:800px;\n",
        "            margin:30px auto;\n",
        "            background:white;\n",
        "            padding:30px;\n",
        "            border-radius:12px;\n",
        "        \">\n",
        "\n",
        "            <h1>\n",
        "                🤖 Daily STEM Project Idea\n",
        "            </h1>\n",
        "\n",
        "            <p style=\"\n",
        "                color:#666;\n",
        "            \">\n",
        "                {date_display}\n",
        "            </p>\n",
        "\n",
        "            <hr>\n",
        "\n",
        "            <h2>\n",
        "                {safe_html(project[\"title\"])}\n",
        "            </h2>\n",
        "\n",
        "            <div style=\"\n",
        "                margin:15px 0;\n",
        "            \">\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    padding:6px 10px;\n",
        "                    margin-right:6px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    Grade {safe_html(project[\"grade\"])}\n",
        "                </span>\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    padding:6px 10px;\n",
        "                    margin-right:6px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    {safe_html(project[\"domain\"])}\n",
        "                </span>\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    padding:6px 10px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    {safe_html(project[\"difficulty\"])}\n",
        "                </span>\n",
        "\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                💡 Project Overview\n",
        "            </h3>\n",
        "\n",
        "            <p style=\"\n",
        "                line-height:1.7;\n",
        "                font-size:15px;\n",
        "            \">\n",
        "                {safe_html(project[\"description\"])}\n",
        "            </p>\n",
        "\n",
        "            <h3>\n",
        "                💰 Estimated Budget\n",
        "            </h3>\n",
        "\n",
        "            <p>\n",
        "                {safe_html(project[\"budget\"])}\n",
        "            </p>\n",
        "\n",
        "            <h3>\n",
        "                🧰 Components Required\n",
        "            </h3>\n",
        "\n",
        "            <ul>\n",
        "                {component_html}\n",
        "            </ul>\n",
        "\n",
        "            <h3>\n",
        "                🔌 Circuit Concept\n",
        "            </h3>\n",
        "\n",
        "            <div style=\"\n",
        "                padding:15px;\n",
        "                background:#f8f9fa;\n",
        "                line-height:1.6;\n",
        "            \">\n",
        "                {safe_html(\n",
        "                    project[\"circuit_concept\"]\n",
        "                )}\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                ⚙️ How It Works\n",
        "            </h3>\n",
        "\n",
        "            <ol>\n",
        "                {working_html}\n",
        "            </ol>\n",
        "\n",
        "            <h3>\n",
        "                💻 Code Outline\n",
        "            </h3>\n",
        "\n",
        "            <ol>\n",
        "                {code_html}\n",
        "            </ol>\n",
        "\n",
        "            <h3>\n",
        "                🎯 Learning Outcomes\n",
        "            </h3>\n",
        "\n",
        "            <ul>\n",
        "                {learning_html}\n",
        "            </ul>\n",
        "\n",
        "            <h3>\n",
        "                🚀 Possible Extensions\n",
        "            </h3>\n",
        "\n",
        "            <ul>\n",
        "                {extensions_html}\n",
        "            </ul>\n",
        "\n",
        "            {safety_html}\n",
        "\n",
        "            <hr style=\"\n",
        "                margin-top:30px;\n",
        "            \">\n",
        "\n",
        "            <p style=\"\n",
        "                color:#777;\n",
        "                font-size:13px;\n",
        "            \">\n",
        "                Generated automatically by\n",
        "                <strong>\n",
        "                    AI STEM Automation Hub\n",
        "                </strong>.\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "\n",
        "    </body>\n",
        "\n",
        "    </html>\n",
        "    \"\"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEXT EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_text_email(\n",
        "    project: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate plain-text project email.\"\"\"\n",
        "\n",
        "    lines = [\n",
        "\n",
        "        \"🤖 DAILY STEM PROJECT IDEA\",\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        f\"Project: {project['title']}\",\n",
        "\n",
        "        f\"Grade: {project['grade']}\",\n",
        "\n",
        "        f\"Domain: {project['domain']}\",\n",
        "\n",
        "        f\"Difficulty: {project['difficulty']}\",\n",
        "\n",
        "        f\"Budget: {project['budget']}\",\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"PROJECT OVERVIEW\",\n",
        "\n",
        "        \"----------------\",\n",
        "\n",
        "        project[\"description\"],\n",
        "\n",
        "        \"\",\n",
        "\n",
        "        \"COMPONENTS\",\n",
        "\n",
        "        \"----------\",\n",
        "    ]\n",
        "\n",
        "    for component in project[\n",
        "        \"components\"\n",
        "    ]:\n",
        "\n",
        "        lines.append(\n",
        "            f\"- {component}\"\n",
        "        )\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"CIRCUIT CONCEPT\",\n",
        "            \"---------------\",\n",
        "            project[\"circuit_concept\"],\n",
        "            \"\",\n",
        "            \"HOW IT WORKS\",\n",
        "            \"-------------\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for index, step in enumerate(\n",
        "        project[\"working\"],\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        lines.append(\n",
        "            f\"{index}. {step}\"\n",
        "        )\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"CODE OUTLINE\",\n",
        "            \"------------\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for index, step in enumerate(\n",
        "        project[\"code_outline\"],\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        lines.append(\n",
        "            f\"{index}. {step}\"\n",
        "        )\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"LEARNING OUTCOMES\",\n",
        "            \"-----------------\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for item in project[\n",
        "        \"learning_outcomes\"\n",
        "    ]:\n",
        "\n",
        "        lines.append(\n",
        "            f\"- {item}\"\n",
        "        )\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"PROJECT EXTENSIONS\",\n",
        "            \"------------------\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for item in project[\n",
        "        \"extensions\"\n",
        "    ]:\n",
        "\n",
        "        lines.append(\n",
        "            f\"- {item}\"\n",
        "        )\n",
        "\n",
        "    if project[\"safety\"]:\n",
        "\n",
        "        lines.extend(\n",
        "            [\n",
        "                \"\",\n",
        "                \"SAFETY\",\n",
        "                \"------\",\n",
        "                project[\"safety\"],\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SEND EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_project_email(\n",
        "    project: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"Send project idea using Gmail SMTP.\"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gmail import (\n",
        "            send_email,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gmail.py before \"\n",
        "            \"sending project emails.\"\n",
        "        ) from exc\n",
        "\n",
        "    subject = (\n",
        "        \"🤖 Daily STEM Project - \"\n",
        "        + datetime.now().strftime(\n",
        "            \"%d %b %Y\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    html_body = generate_html_email(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    text_body = generate_text_email(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        send_email(\n",
        "            subject=subject,\n",
        "            html_body=html_body,\n",
        "            text_body=text_body,\n",
        "            email_type=\"project_idea\",\n",
        "        )\n",
        "\n",
        "        logger.info(\n",
        "            \"Project idea email sent.\"\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Failed to send project email: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RUN PROJECT AGENT\n",
        "# =========================================================\n",
        "\n",
        "def run_project_agent() -> dict[str, Any]:\n",
        "    \"\"\"Run the Daily Project Idea Agent.\"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting Daily STEM Project Agent.\"\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Select parameters\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    grade = select_grade()\n",
        "\n",
        "    domain = select_domain()\n",
        "\n",
        "    difficulty = select_difficulty()\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Previous projects\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    previous_projects = (\n",
        "        get_previous_projects()\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Generate project\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    project = None\n",
        "\n",
        "    max_attempts = 3\n",
        "\n",
        "    for attempt in range(\n",
        "        1,\n",
        "        max_attempts + 1,\n",
        "    ):\n",
        "\n",
        "        logger.info(\n",
        "            \"Project generation attempt %d/%d\",\n",
        "            attempt,\n",
        "            max_attempts,\n",
        "        )\n",
        "\n",
        "        generated = (\n",
        "            generate_project_with_gemini(\n",
        "                grade=grade,\n",
        "                domain=domain,\n",
        "                difficulty=difficulty,\n",
        "                previous_projects=(\n",
        "                    previous_projects\n",
        "                ),\n",
        "            )\n",
        "        )\n",
        "\n",
        "        generated = normalize_project(\n",
        "            generated,\n",
        "            grade=grade,\n",
        "            domain=domain,\n",
        "            difficulty=difficulty,\n",
        "        )\n",
        "\n",
        "        if not validate_project(\n",
        "            generated\n",
        "        ):\n",
        "\n",
        "            logger.warning(\n",
        "                \"Invalid project returned.\"\n",
        "            )\n",
        "\n",
        "            continue\n",
        "\n",
        "        if database.project_exists(\n",
        "            generated[\"title\"]\n",
        "        ):\n",
        "\n",
        "            logger.warning(\n",
        "                \"Duplicate project: %s\",\n",
        "                generated[\"title\"],\n",
        "            )\n",
        "\n",
        "            previous_projects.append(\n",
        "                generated[\"title\"]\n",
        "            )\n",
        "\n",
        "            continue\n",
        "\n",
        "        project = generated\n",
        "\n",
        "        break\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Failure\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if project is None:\n",
        "\n",
        "        logger.error(\n",
        "            \"Unable to generate unique project.\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"success\": False,\n",
        "            \"email_sent\": False,\n",
        "            \"message\": (\n",
        "                \"Unable to generate a unique project.\"\n",
        "            ),\n",
        "        }\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Save\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    project_id = save_project(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"Project saved with ID %s\",\n",
        "        project_id,\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Send email\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    email_sent = send_project_email(\n",
        "        project\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # Mark as sent\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if email_sent:\n",
        "\n",
        "        database.mark_project_sent(\n",
        "            project_id\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"Project Agent completed.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"success\": True,\n",
        "        \"project_id\": project_id,\n",
        "        \"email_sent\": email_sent,\n",
        "        \"project\": project,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    result = run_project_agent()\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"DAILY PROJECT AGENT\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    print(\n",
        "        f\"Success    : \"\n",
        "        f\"{result.get('success')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Email sent : \"\n",
        "        f\"{result.get('email_sent', False)}\"\n",
        "    )\n",
        "\n",
        "    project = result.get(\n",
        "        \"project\"\n",
        "    )\n",
        "\n",
        "    if project:\n",
        "\n",
        "        print(\n",
        "            f\"Project    : \"\n",
        "            f\"{project['title']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Grade      : \"\n",
        "            f\"{project['grade']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Domain     : \"\n",
        "            f\"{project['domain']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Difficulty : \"\n",
        "            f\"{project['difficulty']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Budget     : \"\n",
        "            f\"{project['budget']}\"\n",
        "        )\n",
        "\n",
        "        print()\n",
        "\n",
        "        print(\n",
        "            project[\"description\"]\n",
        "        )\n",
        "\n",
        "    print(\"=\" * 60)"
      ],
      "metadata": {
        "id": "5TlGNX-Zu6NA"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}