{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMIrz+n3YJ22vjFe/QKlPZm",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/stem_tip_agent.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "agents/stem_tip_agent.py\n",
        "\n",
        "Daily STEM Tip Agent\n",
        "\n",
        "Responsibilities:\n",
        "- Generate one practical STEM tip using Gemini\n",
        "- Avoid duplicate tips\n",
        "- Store tips in SQLite\n",
        "- Generate HTML/text email\n",
        "- Send the tip through Gmail SMTP\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import html\n",
        "import json\n",
        "import logging\n",
        "import random\n",
        "from datetime import datetime\n",
        "from typing import Any\n",
        "\n",
        "import database\n",
        "\n",
        "from config import (\n",
        "    PROJECT_DIFFICULTIES,\n",
        "    STEM_DOMAINS,\n",
        "    STEM_GRADES,\n",
        ")\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.STEMTipAgent\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DEFAULT SETTINGS\n",
        "# =========================================================\n",
        "\n",
        "MAX_PREVIOUS_TIPS = 30\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HELPER FUNCTIONS\n",
        "# =========================================================\n",
        "\n",
        "def clean_text(value: Any) -> str:\n",
        "    \"\"\"Clean text returned by the AI.\"\"\"\n",
        "\n",
        "    if value is None:\n",
        "        return \"\"\n",
        "\n",
        "    return \" \".join(\n",
        "        str(value).strip().split()\n",
        "    )\n",
        "\n",
        "\n",
        "def safe_html(value: str) -> str:\n",
        "    \"\"\"Escape text for HTML email.\"\"\"\n",
        "\n",
        "    return html.escape(\n",
        "        value or \"\",\n",
        "        quote=True,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SELECT STEM PARAMETERS\n",
        "# =========================================================\n",
        "\n",
        "def select_grade() -> str:\n",
        "    \"\"\"Select a suitable grade.\"\"\"\n",
        "\n",
        "    grade = random.choice(\n",
        "        STEM_GRADES\n",
        "    )\n",
        "\n",
        "    return str(grade)\n",
        "\n",
        "\n",
        "def select_domain() -> str:\n",
        "    \"\"\"Select a STEM domain.\"\"\"\n",
        "\n",
        "    return random.choice(\n",
        "        STEM_DOMAINS\n",
        "    )\n",
        "\n",
        "\n",
        "def select_difficulty() -> str:\n",
        "    \"\"\"Select project/activity difficulty.\"\"\"\n",
        "\n",
        "    return random.choice(\n",
        "        PROJECT_DIFFICULTIES\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GET PREVIOUS TIPS\n",
        "# =========================================================\n",
        "\n",
        "def get_previous_tips(\n",
        "    limit: int = MAX_PREVIOUS_TIPS,\n",
        ") -> list[str]:\n",
        "    \"\"\"\n",
        "    Get previous STEM tip titles.\n",
        "\n",
        "    This is used to reduce repeated ideas.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        with database.get_connection() as connection:\n",
        "\n",
        "            rows = connection.execute(\n",
        "                \"\"\"\n",
        "                SELECT title\n",
        "                FROM stem_tips\n",
        "                ORDER BY created_at DESC\n",
        "                LIMIT ?\n",
        "                \"\"\",\n",
        "                (limit,),\n",
        "            ).fetchall()\n",
        "\n",
        "        return [\n",
        "            row[\"title\"]\n",
        "            for row in rows\n",
        "            if row[\"title\"]\n",
        "        ]\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Could not load previous tips: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return []\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GEMINI GENERATION\n",
        "# =========================================================\n",
        "\n",
        "def generate_tip_with_gemini(\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        "    previous_titles: list[str],\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"\n",
        "    Generate a STEM tip using Gemini.\n",
        "\n",
        "    Expected services/gemini.py interface:\n",
        "\n",
        "        generate_stem_tip(...)\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gemini import (\n",
        "            generate_stem_tip,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gemini.py before \"\n",
        "            \"running the STEM Tip Agent.\"\n",
        "        ) from exc\n",
        "\n",
        "    logger.info(\n",
        "        \"Generating STEM tip | Grade=%s | Domain=%s | Difficulty=%s\",\n",
        "        grade,\n",
        "        domain,\n",
        "        difficulty,\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        result = generate_stem_tip(\n",
        "            grade=grade,\n",
        "            domain=domain,\n",
        "            difficulty=difficulty,\n",
        "            previous_titles=previous_titles,\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Gemini STEM tip generation failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        raise\n",
        "\n",
        "    if isinstance(result, str):\n",
        "\n",
        "        try:\n",
        "            result = json.loads(result)\n",
        "\n",
        "        except json.JSONDecodeError:\n",
        "\n",
        "            result = {\n",
        "                \"title\": \"Daily STEM Tip\",\n",
        "                \"description\": result,\n",
        "                \"grade\": grade,\n",
        "                \"domain\": domain,\n",
        "                \"difficulty\": difficulty,\n",
        "                \"components\": [],\n",
        "                \"steps\": [],\n",
        "                \"concepts\": [],\n",
        "                \"challenge\": \"\",\n",
        "            }\n",
        "\n",
        "    if not isinstance(result, dict):\n",
        "\n",
        "        raise ValueError(\n",
        "            \"Gemini returned an invalid STEM tip.\"\n",
        "        )\n",
        "\n",
        "    return result\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# VALIDATE GENERATED TIP\n",
        "# =========================================================\n",
        "\n",
        "def validate_tip(\n",
        "    tip: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"Validate the AI-generated STEM tip.\"\"\"\n",
        "\n",
        "    required_fields = [\n",
        "        \"title\",\n",
        "        \"description\",\n",
        "    ]\n",
        "\n",
        "    for field in required_fields:\n",
        "\n",
        "        if not clean_text(\n",
        "            tip.get(field, \"\")\n",
        "        ):\n",
        "\n",
        "            return False\n",
        "\n",
        "    return True\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NORMALIZE TIP\n",
        "# =========================================================\n",
        "\n",
        "def normalize_tip(\n",
        "    tip: dict[str, Any],\n",
        "    grade: str,\n",
        "    domain: str,\n",
        "    difficulty: str,\n",
        ") -> dict[str, Any]:\n",
        "    \"\"\"Normalize the generated response.\"\"\"\n",
        "\n",
        "    return {\n",
        "        \"title\": clean_text(\n",
        "            tip.get(\n",
        "                \"title\",\n",
        "                \"Daily STEM Tip\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"description\": clean_text(\n",
        "            tip.get(\n",
        "                \"description\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"grade\": clean_text(\n",
        "            tip.get(\n",
        "                \"grade\",\n",
        "                grade,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"domain\": clean_text(\n",
        "            tip.get(\n",
        "                \"domain\",\n",
        "                domain,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"difficulty\": clean_text(\n",
        "            tip.get(\n",
        "                \"difficulty\",\n",
        "                difficulty,\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"components\": tip.get(\n",
        "            \"components\",\n",
        "            [],\n",
        "        ),\n",
        "\n",
        "        \"steps\": tip.get(\n",
        "            \"steps\",\n",
        "            [],\n",
        "        ),\n",
        "\n",
        "        \"concepts\": tip.get(\n",
        "            \"concepts\",\n",
        "            [],\n",
        "        ),\n",
        "\n",
        "        \"challenge\": clean_text(\n",
        "            tip.get(\n",
        "                \"challenge\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "\n",
        "        \"safety\": clean_text(\n",
        "            tip.get(\n",
        "                \"safety\",\n",
        "                \"\",\n",
        "            )\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# FORMAT LIST\n",
        "# =========================================================\n",
        "\n",
        "def format_list(\n",
        "    values: Any,\n",
        ") -> list[str]:\n",
        "    \"\"\"Convert AI list output into clean strings.\"\"\"\n",
        "\n",
        "    if values is None:\n",
        "        return []\n",
        "\n",
        "    if isinstance(values, str):\n",
        "\n",
        "        return [\n",
        "            clean_text(values)\n",
        "        ]\n",
        "\n",
        "    if not isinstance(values, list):\n",
        "\n",
        "        return []\n",
        "\n",
        "    result = []\n",
        "\n",
        "    for value in values:\n",
        "\n",
        "        value = clean_text(value)\n",
        "\n",
        "        if value:\n",
        "            result.append(value)\n",
        "\n",
        "    return result\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SAVE TIP\n",
        "# =========================================================\n",
        "\n",
        "def save_tip(\n",
        "    tip: dict[str, Any],\n",
        ") -> int:\n",
        "    \"\"\"Save generated STEM tip to SQLite.\"\"\"\n",
        "\n",
        "    components = format_list(\n",
        "        tip.get(\"components\")\n",
        "    )\n",
        "\n",
        "    steps = format_list(\n",
        "        tip.get(\"steps\")\n",
        "    )\n",
        "\n",
        "    concepts = format_list(\n",
        "        tip.get(\"concepts\")\n",
        "    )\n",
        "\n",
        "    content = json.dumps(\n",
        "        {\n",
        "            \"description\": tip.get(\n",
        "                \"description\",\n",
        "                \"\",\n",
        "            ),\n",
        "            \"components\": components,\n",
        "            \"steps\": steps,\n",
        "            \"concepts\": concepts,\n",
        "            \"challenge\": tip.get(\n",
        "                \"challenge\",\n",
        "                \"\",\n",
        "            ),\n",
        "            \"safety\": tip.get(\n",
        "                \"safety\",\n",
        "                \"\",\n",
        "            ),\n",
        "        },\n",
        "        ensure_ascii=False,\n",
        "    )\n",
        "\n",
        "    return database.add_stem_tip(\n",
        "        title=tip[\"title\"],\n",
        "        topic=tip[\"domain\"],\n",
        "        grade=tip[\"grade\"],\n",
        "        difficulty=tip[\"difficulty\"],\n",
        "        content=content,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_html_email(\n",
        "    tip: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate a professional HTML email.\"\"\"\n",
        "\n",
        "    date_display = datetime.now().strftime(\n",
        "        \"%d %B %Y\"\n",
        "    )\n",
        "\n",
        "    components = format_list(\n",
        "        tip.get(\"components\")\n",
        "    )\n",
        "\n",
        "    steps = format_list(\n",
        "        tip.get(\"steps\")\n",
        "    )\n",
        "\n",
        "    concepts = format_list(\n",
        "        tip.get(\"concepts\")\n",
        "    )\n",
        "\n",
        "    component_html = \"\".join(\n",
        "        f\"<li>{safe_html(item)}</li>\"\n",
        "        for item in components\n",
        "    )\n",
        "\n",
        "    step_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <li style=\"\n",
        "            margin-bottom:8px;\n",
        "        \">\n",
        "            {safe_html(item)}\n",
        "        </li>\n",
        "        \"\"\"\n",
        "        for item in steps\n",
        "    )\n",
        "\n",
        "    concepts_html = \"\".join(\n",
        "        f\"\"\"\n",
        "        <span style=\"\n",
        "            display:inline-block;\n",
        "            margin:4px;\n",
        "            padding:6px 10px;\n",
        "            background:#eeeeee;\n",
        "            border-radius:15px;\n",
        "            font-size:13px;\n",
        "        \">\n",
        "            {safe_html(item)}\n",
        "        </span>\n",
        "        \"\"\"\n",
        "        for item in concepts\n",
        "    )\n",
        "\n",
        "    challenge_html = \"\"\n",
        "\n",
        "    if tip.get(\"challenge\"):\n",
        "\n",
        "        challenge_html = f\"\"\"\n",
        "        <div style=\"\n",
        "            margin-top:25px;\n",
        "            padding:18px;\n",
        "            background:#f3f4f6;\n",
        "            border-radius:8px;\n",
        "        \">\n",
        "\n",
        "            <h3>\n",
        "                💡 Student Challenge\n",
        "            </h3>\n",
        "\n",
        "            <p>\n",
        "                {safe_html(tip[\"challenge\"])}\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "        \"\"\"\n",
        "\n",
        "    safety_html = \"\"\n",
        "\n",
        "    if tip.get(\"safety\"):\n",
        "\n",
        "        safety_html = f\"\"\"\n",
        "        <div style=\"\n",
        "            margin-top:20px;\n",
        "            padding:15px;\n",
        "            background:#fff7ed;\n",
        "            border-left:4px solid #f97316;\n",
        "        \">\n",
        "\n",
        "            <strong>\n",
        "                ⚠️ Safety\n",
        "            </strong>\n",
        "\n",
        "            <p>\n",
        "                {safe_html(tip[\"safety\"])}\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "        \"\"\"\n",
        "\n",
        "    return f\"\"\"\n",
        "    <!DOCTYPE html>\n",
        "\n",
        "    <html>\n",
        "\n",
        "    <head>\n",
        "        <meta charset=\"UTF-8\">\n",
        "        <title>Daily STEM Tip</title>\n",
        "    </head>\n",
        "\n",
        "    <body style=\"\n",
        "        margin:0;\n",
        "        padding:0;\n",
        "        background:#f4f6f8;\n",
        "        font-family:Arial,Helvetica,sans-serif;\n",
        "    \">\n",
        "\n",
        "        <div style=\"\n",
        "            max-width:760px;\n",
        "            margin:30px auto;\n",
        "            background:#ffffff;\n",
        "            padding:30px;\n",
        "            border-radius:12px;\n",
        "        \">\n",
        "\n",
        "            <h1>\n",
        "                🔬 Daily STEM Tip\n",
        "            </h1>\n",
        "\n",
        "            <p style=\"\n",
        "                color:#666666;\n",
        "            \">\n",
        "                {date_display}\n",
        "            </p>\n",
        "\n",
        "            <hr>\n",
        "\n",
        "            <h2>\n",
        "                {safe_html(tip[\"title\"])}\n",
        "            </h2>\n",
        "\n",
        "            <div style=\"\n",
        "                margin:15px 0;\n",
        "            \">\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    margin-right:8px;\n",
        "                    padding:6px 10px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    Grade {safe_html(tip[\"grade\"])}\n",
        "                </span>\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    margin-right:8px;\n",
        "                    padding:6px 10px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    {safe_html(tip[\"domain\"])}\n",
        "                </span>\n",
        "\n",
        "                <span style=\"\n",
        "                    display:inline-block;\n",
        "                    padding:6px 10px;\n",
        "                    background:#eeeeee;\n",
        "                    border-radius:15px;\n",
        "                \">\n",
        "                    {safe_html(tip[\"difficulty\"])}\n",
        "                </span>\n",
        "\n",
        "            </div>\n",
        "\n",
        "            <h3>\n",
        "                💡 Idea\n",
        "            </h3>\n",
        "\n",
        "            <p style=\"\n",
        "                line-height:1.7;\n",
        "                font-size:15px;\n",
        "            \">\n",
        "                {safe_html(tip[\"description\"])}\n",
        "            </p>\n",
        "\n",
        "            <h3>\n",
        "                🧰 Components\n",
        "            </h3>\n",
        "\n",
        "            <ul>\n",
        "                {component_html}\n",
        "            </ul>\n",
        "\n",
        "            <h3>\n",
        "                ⚙️ Steps\n",
        "            </h3>\n",
        "\n",
        "            <ol>\n",
        "                {step_html}\n",
        "            </ol>\n",
        "\n",
        "            <h3>\n",
        "                🧠 STEM Concepts\n",
        "            </h3>\n",
        "\n",
        "            <div>\n",
        "                {concepts_html}\n",
        "            </div>\n",
        "\n",
        "            {challenge_html}\n",
        "\n",
        "            {safety_html}\n",
        "\n",
        "            <hr style=\"\n",
        "                margin-top:30px;\n",
        "            \">\n",
        "\n",
        "            <p style=\"\n",
        "                color:#777777;\n",
        "                font-size:13px;\n",
        "            \">\n",
        "                Generated automatically by\n",
        "                <strong>AI STEM Automation Hub</strong>.\n",
        "            </p>\n",
        "\n",
        "        </div>\n",
        "\n",
        "    </body>\n",
        "\n",
        "    </html>\n",
        "    \"\"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TEXT EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def generate_text_email(\n",
        "    tip: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"Generate plain-text fallback email.\"\"\"\n",
        "\n",
        "    components = format_list(\n",
        "        tip.get(\"components\")\n",
        "    )\n",
        "\n",
        "    steps = format_list(\n",
        "        tip.get(\"steps\")\n",
        "    )\n",
        "\n",
        "    concepts = format_list(\n",
        "        tip.get(\"concepts\")\n",
        "    )\n",
        "\n",
        "    lines = [\n",
        "        \"🔬 DAILY STEM TIP\",\n",
        "        \"\",\n",
        "        f\"Project: {tip['title']}\",\n",
        "        f\"Grade: {tip['grade']}\",\n",
        "        f\"Domain: {tip['domain']}\",\n",
        "        f\"Difficulty: {tip['difficulty']}\",\n",
        "        \"\",\n",
        "        \"IDEA\",\n",
        "        \"----\",\n",
        "        tip[\"description\"],\n",
        "        \"\",\n",
        "        \"COMPONENTS\",\n",
        "        \"----------\",\n",
        "    ]\n",
        "\n",
        "    for item in components:\n",
        "        lines.append(f\"- {item}\")\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"STEPS\",\n",
        "            \"-----\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for index, step in enumerate(\n",
        "        steps,\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        lines.append(\n",
        "            f\"{index}. {step}\"\n",
        "        )\n",
        "\n",
        "    lines.extend(\n",
        "        [\n",
        "            \"\",\n",
        "            \"STEM CONCEPTS\",\n",
        "            \"-------------\",\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    for concept in concepts:\n",
        "        lines.append(f\"- {concept}\")\n",
        "\n",
        "    if tip.get(\"challenge\"):\n",
        "\n",
        "        lines.extend(\n",
        "            [\n",
        "                \"\",\n",
        "                \"STUDENT CHALLENGE\",\n",
        "                \"-----------------\",\n",
        "                tip[\"challenge\"],\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    if tip.get(\"safety\"):\n",
        "\n",
        "        lines.extend(\n",
        "            [\n",
        "                \"\",\n",
        "                \"SAFETY\",\n",
        "                \"------\",\n",
        "                tip[\"safety\"],\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SEND EMAIL\n",
        "# =========================================================\n",
        "\n",
        "def send_tip_email(\n",
        "    tip: dict[str, Any],\n",
        ") -> bool:\n",
        "    \"\"\"Send STEM tip through Gmail.\"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        from services.gmail import (\n",
        "            send_email,\n",
        "        )\n",
        "\n",
        "    except ImportError as exc:\n",
        "\n",
        "        raise ImportError(\n",
        "            \"Create services/gmail.py before \"\n",
        "            \"sending STEM tip emails.\"\n",
        "        ) from exc\n",
        "\n",
        "    subject = (\n",
        "        \"🔬 Daily STEM Tip - \"\n",
        "        + datetime.now().strftime(\n",
        "            \"%d %b %Y\"\n",
        "        )\n",
        "    )\n",
        "\n",
        "    html_body = generate_html_email(\n",
        "        tip\n",
        "    )\n",
        "\n",
        "    text_body = generate_text_email(\n",
        "        tip\n",
        "    )\n",
        "\n",
        "    try:\n",
        "\n",
        "        send_email(\n",
        "            subject=subject,\n",
        "            html_body=html_body,\n",
        "            text_body=text_body,\n",
        "            email_type=\"stem_tip\",\n",
        "        )\n",
        "\n",
        "        logger.info(\n",
        "            \"STEM tip email sent successfully.\"\n",
        "        )\n",
        "\n",
        "        return True\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.exception(\n",
        "            \"Failed to send STEM tip email: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RUN AGENT\n",
        "# =========================================================\n",
        "\n",
        "def run_stem_tip_agent() -> dict[str, Any]:\n",
        "    \"\"\"Run the complete Daily STEM Tip Agent.\"\"\"\n",
        "\n",
        "    logger.info(\n",
        "        \"Starting Daily STEM Tip Agent.\"\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 1. Select parameters\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    grade = select_grade()\n",
        "\n",
        "    domain = select_domain()\n",
        "\n",
        "    difficulty = select_difficulty()\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 2. Load previous ideas\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    previous_titles = get_previous_tips()\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 3. Generate with Gemini\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    max_attempts = 3\n",
        "\n",
        "    tip = None\n",
        "\n",
        "    for attempt in range(\n",
        "        1,\n",
        "        max_attempts + 1,\n",
        "    ):\n",
        "\n",
        "        logger.info(\n",
        "            \"STEM tip generation attempt %d/%d\",\n",
        "            attempt,\n",
        "            max_attempts,\n",
        "        )\n",
        "\n",
        "        generated = (\n",
        "            generate_tip_with_gemini(\n",
        "                grade=grade,\n",
        "                domain=domain,\n",
        "                difficulty=difficulty,\n",
        "                previous_titles=previous_titles,\n",
        "            )\n",
        "        )\n",
        "\n",
        "        generated = normalize_tip(\n",
        "            generated,\n",
        "            grade=grade,\n",
        "            domain=domain,\n",
        "            difficulty=difficulty,\n",
        "        )\n",
        "\n",
        "        if not validate_tip(\n",
        "            generated\n",
        "        ):\n",
        "\n",
        "            logger.warning(\n",
        "                \"Generated tip is invalid.\"\n",
        "            )\n",
        "\n",
        "            continue\n",
        "\n",
        "        if database.stem_tip_exists(\n",
        "            generated[\"title\"]\n",
        "        ):\n",
        "\n",
        "            logger.warning(\n",
        "                \"Duplicate STEM tip generated: %s\",\n",
        "                generated[\"title\"],\n",
        "            )\n",
        "\n",
        "            previous_titles.append(\n",
        "                generated[\"title\"]\n",
        "            )\n",
        "\n",
        "            continue\n",
        "\n",
        "        tip = generated\n",
        "\n",
        "        break\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 4. Failed generation\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if tip is None:\n",
        "\n",
        "        logger.error(\n",
        "            \"Could not generate a unique STEM tip.\"\n",
        "        )\n",
        "\n",
        "        return {\n",
        "            \"success\": False,\n",
        "            \"email_sent\": False,\n",
        "            \"message\": (\n",
        "                \"Could not generate a unique STEM tip.\"\n",
        "            ),\n",
        "        }\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 5. Save to database\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    tip_id = save_tip(\n",
        "        tip\n",
        "    )\n",
        "\n",
        "    logger.info(\n",
        "        \"STEM tip saved with ID %s\",\n",
        "        tip_id,\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 6. Send email\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    email_sent = send_tip_email(\n",
        "        tip\n",
        "    )\n",
        "\n",
        "    # -----------------------------------------------------\n",
        "    # 7. Mark sent\n",
        "    # -----------------------------------------------------\n",
        "\n",
        "    if email_sent:\n",
        "\n",
        "        database.mark_stem_tip_sent(\n",
        "            tip_id\n",
        "        )\n",
        "\n",
        "    logger.info(\n",
        "        \"STEM Tip Agent completed.\"\n",
        "    )\n",
        "\n",
        "    return {\n",
        "        \"success\": True,\n",
        "        \"tip_id\": tip_id,\n",
        "        \"email_sent\": email_sent,\n",
        "        \"tip\": tip,\n",
        "    }\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    result = run_stem_tip_agent()\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(\"DAILY STEM TIP RESULT\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    print(\n",
        "        f\"Success    : \"\n",
        "        f\"{result.get('success')}\"\n",
        "    )\n",
        "\n",
        "    print(\n",
        "        f\"Email sent : \"\n",
        "        f\"{result.get('email_sent', False)}\"\n",
        "    )\n",
        "\n",
        "    tip = result.get(\"tip\")\n",
        "\n",
        "    if tip:\n",
        "\n",
        "        print(\n",
        "            f\"Title      : \"\n",
        "            f\"{tip.get('title')}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Grade      : \"\n",
        "            f\"{tip.get('grade')}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Domain     : \"\n",
        "            f\"{tip.get('domain')}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"Difficulty : \"\n",
        "            f\"{tip.get('difficulty')}\"\n",
        "        )\n",
        "\n",
        "        print()\n",
        "\n",
        "        print(\n",
        "            tip.get(\n",
        "                \"description\",\n",
        "                \"\",\n",
        "            )\n",
        "        )\n",
        "\n",
        "    print(\"=\" * 60)"
      ],
      "metadata": {
        "id": "NH1QrWtwupMw"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}