{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOnIr4LIkSfMC1sYT3b231B",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sackm123-cloud/AI-Website-Agent-/blob/main/web_search.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "AI STEM Automation Hub\n",
        "services/web_search.py\n",
        "\n",
        "Web/news collection service.\n",
        "\n",
        "Used by:\n",
        "    agents/news_agent.py\n",
        "\n",
        "Responsibilities:\n",
        "    - Search for current AI news\n",
        "    - Search for robotics news\n",
        "    - Search for electronics/IoT news\n",
        "    - Collect article metadata\n",
        "    - Remove duplicate URLs\n",
        "    - Filter old articles\n",
        "    - Return clean article data\n",
        "\n",
        "Gemini is NOT used here.\n",
        "Gemini summarization belongs in:\n",
        "    services/gemini.py\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import hashlib\n",
        "import logging\n",
        "import re\n",
        "from datetime import datetime, timedelta, timezone\n",
        "from typing import Any, Optional\n",
        "from urllib.parse import urlparse\n",
        "\n",
        "import requests\n",
        "from bs4 import BeautifulSoup\n",
        "from dotenv import load_dotenv\n",
        "import os\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ENVIRONMENT\n",
        "# =========================================================\n",
        "\n",
        "load_dotenv()\n",
        "\n",
        "\n",
        "logger = logging.getLogger(\n",
        "    \"AI-STEM-Automation.WebSearch\"\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CONFIGURATION\n",
        "# =========================================================\n",
        "\n",
        "REQUEST_TIMEOUT = int(\n",
        "    os.getenv(\n",
        "        \"WEB_SEARCH_TIMEOUT\",\n",
        "        \"15\",\n",
        "    )\n",
        ")\n",
        "\n",
        "MAX_ARTICLES = int(\n",
        "    os.getenv(\n",
        "        \"NEWS_MAX_ARTICLES\",\n",
        "        \"20\",\n",
        "    )\n",
        ")\n",
        "\n",
        "USER_AGENT = os.getenv(\n",
        "    \"NEWS_USER_AGENT\",\n",
        "    \"AI-STEM-Automation-News-Agent/1.0\",\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RSS SOURCES\n",
        "# =========================================================\n",
        "\n",
        "RSS_SOURCES = {\n",
        "\n",
        "    \"AI\":\n",
        "        [\n",
        "            (\n",
        "                \"Google AI Blog\",\n",
        "                \"https://blog.google/technology/ai/rss/\"\n",
        "            ),\n",
        "\n",
        "            (\n",
        "                \"OpenAI\",\n",
        "                \"https://openai.com/news/rss.xml\"\n",
        "            ),\n",
        "\n",
        "            (\n",
        "                \"MIT AI News\",\n",
        "                \"https://news.mit.edu/rss/topic/artificial-intelligence2\"\n",
        "            ),\n",
        "        ],\n",
        "\n",
        "    \"Robotics\":\n",
        "        [\n",
        "            (\n",
        "                \"IEEE Robotics\",\n",
        "                \"https://spectrum.ieee.org/feeds/topic/robotics.rss\"\n",
        "            ),\n",
        "\n",
        "            (\n",
        "                \"Robotics Business Review\",\n",
        "                \"https://www.roboticsbusinessreview.com/feed/\"\n",
        "            ),\n",
        "        ],\n",
        "\n",
        "    \"Electronics\":\n",
        "        [\n",
        "            (\n",
        "                \"Electronics Weekly\",\n",
        "                \"https://www.electronicsweekly.com/feed\"\n",
        "            ),\n",
        "        ],\n",
        "\n",
        "    \"IoT\":\n",
        "        [\n",
        "            (\n",
        "                \"IoT For All\",\n",
        "                \"https://www.iotforall.com/feed\"\n",
        "            ),\n",
        "        ],\n",
        "}\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTTP SESSION\n",
        "# =========================================================\n",
        "\n",
        "session = requests.Session()\n",
        "\n",
        "session.headers.update(\n",
        "    {\n",
        "        \"User-Agent\": USER_AGENT,\n",
        "        \"Accept\": (\n",
        "            \"application/rss+xml,\"\n",
        "            \"application/xml,\"\n",
        "            \"text/xml,\"\n",
        "            \"text/html\"\n",
        "        ),\n",
        "    }\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# REQUEST\n",
        "# =========================================================\n",
        "\n",
        "def fetch_url(\n",
        "    url: str,\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Download a webpage or RSS feed.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        response = session.get(\n",
        "            url,\n",
        "            timeout=REQUEST_TIMEOUT,\n",
        "        )\n",
        "\n",
        "        response.raise_for_status()\n",
        "\n",
        "        return response.text\n",
        "\n",
        "    except requests.RequestException as exc:\n",
        "\n",
        "        logger.warning(\n",
        "            \"Failed to fetch %s: %s\",\n",
        "            url,\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return \"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HTML CLEANING\n",
        "# =========================================================\n",
        "\n",
        "def clean_text(\n",
        "    text: Optional[str],\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Remove HTML and normalize whitespace.\n",
        "    \"\"\"\n",
        "\n",
        "    if not text:\n",
        "\n",
        "        return \"\"\n",
        "\n",
        "    soup = BeautifulSoup(\n",
        "        text,\n",
        "        \"html.parser\",\n",
        "    )\n",
        "\n",
        "    text = soup.get_text(\n",
        "        \" \",\n",
        "        strip=True,\n",
        "    )\n",
        "\n",
        "    text = re.sub(\n",
        "        r\"\\s+\",\n",
        "        \" \",\n",
        "        text,\n",
        "    )\n",
        "\n",
        "    return text.strip()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RSS DATE PARSER\n",
        "# =========================================================\n",
        "\n",
        "def parse_date(\n",
        "    value: Optional[str],\n",
        ") -> Optional[datetime]:\n",
        "    \"\"\"\n",
        "    Parse common RSS/Atom date formats.\n",
        "    \"\"\"\n",
        "\n",
        "    if not value:\n",
        "\n",
        "        return None\n",
        "\n",
        "    value = value.strip()\n",
        "\n",
        "    formats = [\n",
        "\n",
        "        \"%a, %d %b %Y %H:%M:%S %z\",\n",
        "\n",
        "        \"%a, %d %b %Y %H:%M:%S GMT\",\n",
        "\n",
        "        \"%Y-%m-%dT%H:%M:%S%z\",\n",
        "\n",
        "        \"%Y-%m-%dT%H:%M:%SZ\",\n",
        "\n",
        "        \"%Y-%m-%d %H:%M:%S\",\n",
        "\n",
        "        \"%Y-%m-%d\",\n",
        "    ]\n",
        "\n",
        "    for fmt in formats:\n",
        "\n",
        "        try:\n",
        "\n",
        "            result = datetime.strptime(\n",
        "                value,\n",
        "                fmt,\n",
        "            )\n",
        "\n",
        "            if result.tzinfo is None:\n",
        "\n",
        "                result = result.replace(\n",
        "                    tzinfo=timezone.utc\n",
        "                )\n",
        "\n",
        "            return result\n",
        "\n",
        "        except ValueError:\n",
        "\n",
        "            continue\n",
        "\n",
        "    return None\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RSS PARSER\n",
        "# =========================================================\n",
        "\n",
        "def parse_rss(\n",
        "    xml: str,\n",
        "    source_name: str,\n",
        "    category: str,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Parse RSS/Atom feed.\n",
        "\n",
        "    Uses BeautifulSoup rather than depending\n",
        "    on feedparser.\n",
        "    \"\"\"\n",
        "\n",
        "    if not xml:\n",
        "\n",
        "        return []\n",
        "\n",
        "    soup = BeautifulSoup(\n",
        "        xml,\n",
        "        \"xml\",\n",
        "    )\n",
        "\n",
        "    items = soup.find_all(\n",
        "        [\"item\", \"entry\"]\n",
        "    )\n",
        "\n",
        "    articles = []\n",
        "\n",
        "    for item in items:\n",
        "\n",
        "        title_tag = item.find(\n",
        "            \"title\"\n",
        "        )\n",
        "\n",
        "        link_tag = item.find(\n",
        "            \"link\"\n",
        "        )\n",
        "\n",
        "        description_tag = (\n",
        "            item.find(\n",
        "                \"description\"\n",
        "            )\n",
        "            or item.find(\n",
        "                \"summary\"\n",
        "            )\n",
        "            or item.find(\n",
        "                \"content\"\n",
        "            )\n",
        "        )\n",
        "\n",
        "        date_tag = (\n",
        "            item.find(\n",
        "                \"pubDate\"\n",
        "            )\n",
        "            or item.find(\n",
        "                \"published\"\n",
        "            )\n",
        "            or item.find(\n",
        "                \"updated\"\n",
        "            )\n",
        "        )\n",
        "\n",
        "        author_tag = (\n",
        "            item.find(\n",
        "                \"author\"\n",
        "            )\n",
        "            or item.find(\n",
        "                \"dc:creator\"\n",
        "            )\n",
        "        )\n",
        "\n",
        "        title = (\n",
        "            title_tag.get_text(\n",
        "                \" \",\n",
        "                strip=True,\n",
        "            )\n",
        "            if title_tag\n",
        "            else \"\"\n",
        "        )\n",
        "\n",
        "        # RSS <link>\n",
        "        url = \"\"\n",
        "\n",
        "        if link_tag:\n",
        "\n",
        "            url = (\n",
        "                link_tag.get(\n",
        "                    \"href\",\n",
        "                    \"\"\n",
        "                )\n",
        "                or link_tag.get_text(\n",
        "                    strip=True\n",
        "                )\n",
        "            )\n",
        "\n",
        "        # Atom sometimes stores URL in href.\n",
        "        if (\n",
        "            not url\n",
        "            and link_tag\n",
        "        ):\n",
        "\n",
        "            url = link_tag.get(\n",
        "                \"href\",\n",
        "                \"\",\n",
        "            )\n",
        "\n",
        "        description = (\n",
        "            description_tag.get_text(\n",
        "                \" \",\n",
        "                strip=True,\n",
        "            )\n",
        "            if description_tag\n",
        "            else \"\"\n",
        "        )\n",
        "\n",
        "        author = (\n",
        "            author_tag.get_text(\n",
        "                \" \",\n",
        "                strip=True,\n",
        "            )\n",
        "            if author_tag\n",
        "            else \"\"\n",
        "        )\n",
        "\n",
        "        published = (\n",
        "            date_tag.get_text(\n",
        "                \" \",\n",
        "                strip=True,\n",
        "            )\n",
        "            if date_tag\n",
        "            else \"\"\n",
        "        )\n",
        "\n",
        "        published_at = parse_date(\n",
        "            published\n",
        "        )\n",
        "\n",
        "        if not title or not url:\n",
        "\n",
        "            continue\n",
        "\n",
        "        articles.append(\n",
        "            {\n",
        "                \"title\": clean_text(\n",
        "                    title\n",
        "                ),\n",
        "\n",
        "                \"url\": url.strip(),\n",
        "\n",
        "                \"description\": clean_text(\n",
        "                    description\n",
        "                ),\n",
        "\n",
        "                \"source\": source_name,\n",
        "\n",
        "                \"category\": category,\n",
        "\n",
        "                \"author\": clean_text(\n",
        "                    author\n",
        "                ),\n",
        "\n",
        "                \"published\": (\n",
        "                    published_at.isoformat()\n",
        "                    if published_at\n",
        "                    else \"\"\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RSS SEARCH\n",
        "# =========================================================\n",
        "\n",
        "def search_rss(\n",
        "    category: str,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Collect articles from configured RSS sources.\n",
        "    \"\"\"\n",
        "\n",
        "    sources = RSS_SOURCES.get(\n",
        "        category,\n",
        "        [],\n",
        "    )\n",
        "\n",
        "    if not sources:\n",
        "\n",
        "        logger.warning(\n",
        "            \"No RSS sources configured for %s\",\n",
        "            category,\n",
        "        )\n",
        "\n",
        "        return []\n",
        "\n",
        "    articles = []\n",
        "\n",
        "    for source_name, url in sources:\n",
        "\n",
        "        logger.info(\n",
        "            \"Fetching %s\",\n",
        "            source_name,\n",
        "        )\n",
        "\n",
        "        xml = fetch_url(\n",
        "            url\n",
        "        )\n",
        "\n",
        "        parsed = parse_rss(\n",
        "            xml,\n",
        "            source_name,\n",
        "            category,\n",
        "        )\n",
        "\n",
        "        articles.extend(\n",
        "            parsed\n",
        "        )\n",
        "\n",
        "    return articles\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# KEYWORD FILTER\n",
        "# =========================================================\n",
        "\n",
        "def filter_keywords(\n",
        "    articles: list[dict[str, Any]],\n",
        "    keywords: Optional[\n",
        "        list[str]\n",
        "    ] = None,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Keep articles matching keywords.\n",
        "    \"\"\"\n",
        "\n",
        "    if not keywords:\n",
        "\n",
        "        return articles\n",
        "\n",
        "    keywords_lower = [\n",
        "        keyword.lower()\n",
        "        for keyword in keywords\n",
        "    ]\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        searchable = \" \".join(\n",
        "            [\n",
        "                article.get(\n",
        "                    \"title\",\n",
        "                    \"\",\n",
        "                ),\n",
        "                article.get(\n",
        "                    \"description\",\n",
        "                    \"\",\n",
        "                ),\n",
        "                article.get(\n",
        "                    \"category\",\n",
        "                    \"\",\n",
        "                ),\n",
        "            ]\n",
        "        ).lower()\n",
        "\n",
        "        if any(\n",
        "            keyword in searchable\n",
        "            for keyword in keywords_lower\n",
        "        ):\n",
        "\n",
        "            results.append(\n",
        "                article\n",
        "            )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DATE FILTER\n",
        "# =========================================================\n",
        "\n",
        "def filter_recent(\n",
        "    articles: list[dict[str, Any]],\n",
        "    hours: int = 48,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Keep articles published within the last N hours.\n",
        "\n",
        "    Articles without a readable publication date\n",
        "    are retained.\n",
        "    \"\"\"\n",
        "\n",
        "    cutoff = (\n",
        "        datetime.now(\n",
        "            timezone.utc\n",
        "        )\n",
        "        - timedelta(\n",
        "            hours=hours\n",
        "        )\n",
        "    )\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        published = article.get(\n",
        "            \"published\"\n",
        "        )\n",
        "\n",
        "        if not published:\n",
        "\n",
        "            results.append(\n",
        "                article\n",
        "            )\n",
        "\n",
        "            continue\n",
        "\n",
        "        try:\n",
        "\n",
        "            article_time = (\n",
        "                datetime.fromisoformat(\n",
        "                    published\n",
        "                )\n",
        "            )\n",
        "\n",
        "            if (\n",
        "                article_time\n",
        "                >= cutoff\n",
        "            ):\n",
        "\n",
        "                results.append(\n",
        "                    article\n",
        "                )\n",
        "\n",
        "        except ValueError:\n",
        "\n",
        "            results.append(\n",
        "                article\n",
        "            )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# DUPLICATE REMOVAL\n",
        "# =========================================================\n",
        "\n",
        "def article_key(\n",
        "    article: dict[str, Any],\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Generate stable article identifier.\n",
        "    \"\"\"\n",
        "\n",
        "    url = article.get(\n",
        "        \"url\",\n",
        "        \"\",\n",
        "    ).strip().lower()\n",
        "\n",
        "    if url:\n",
        "\n",
        "        return hashlib.sha256(\n",
        "            url.encode(\n",
        "                \"utf-8\"\n",
        "            )\n",
        "        ).hexdigest()\n",
        "\n",
        "    title = article.get(\n",
        "        \"title\",\n",
        "        \"\",\n",
        "    ).strip().lower()\n",
        "\n",
        "    return hashlib.sha256(\n",
        "        title.encode(\n",
        "            \"utf-8\"\n",
        "        )\n",
        "    ).hexdigest()\n",
        "\n",
        "\n",
        "def remove_duplicates(\n",
        "    articles: list[dict[str, Any]],\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Remove duplicate articles.\n",
        "    \"\"\"\n",
        "\n",
        "    seen = set()\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        key = article_key(\n",
        "            article\n",
        "        )\n",
        "\n",
        "        if key in seen:\n",
        "\n",
        "            continue\n",
        "\n",
        "        seen.add(key)\n",
        "\n",
        "        results.append(\n",
        "            article\n",
        "        )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SORT ARTICLES\n",
        "# =========================================================\n",
        "\n",
        "def sort_articles(\n",
        "    articles: list[dict[str, Any]],\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Sort newest articles first.\n",
        "    \"\"\"\n",
        "\n",
        "    def sort_key(\n",
        "        article: dict[str, Any],\n",
        "    ):\n",
        "\n",
        "        value = article.get(\n",
        "            \"published\",\n",
        "            \"\",\n",
        "        )\n",
        "\n",
        "        if not value:\n",
        "\n",
        "            return datetime.min.replace(\n",
        "                tzinfo=timezone.utc\n",
        "            )\n",
        "\n",
        "        try:\n",
        "\n",
        "            return datetime.fromisoformat(\n",
        "                value\n",
        "            )\n",
        "\n",
        "        except ValueError:\n",
        "\n",
        "            return datetime.min.replace(\n",
        "                tzinfo=timezone.utc\n",
        "            )\n",
        "\n",
        "    return sorted(\n",
        "        articles,\n",
        "        key=sort_key,\n",
        "        reverse=True,\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# MULTI-CATEGORY SEARCH\n",
        "# =========================================================\n",
        "\n",
        "def search_news(\n",
        "    categories: Optional[\n",
        "        list[str]\n",
        "    ] = None,\n",
        "    hours: int = 48,\n",
        "    limit: int = MAX_ARTICLES,\n",
        "    keywords: Optional[\n",
        "        list[str]\n",
        "    ] = None,\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Collect current AI/Robotics/STEM news.\n",
        "\n",
        "    Example:\n",
        "\n",
        "        articles = search_news(\n",
        "            categories=[\n",
        "                \"AI\",\n",
        "                \"Robotics\",\n",
        "                \"Electronics\",\n",
        "            ],\n",
        "            hours=24,\n",
        "            limit=15,\n",
        "        )\n",
        "    \"\"\"\n",
        "\n",
        "    if categories is None:\n",
        "\n",
        "        categories = [\n",
        "            \"AI\",\n",
        "            \"Robotics\",\n",
        "            \"Electronics\",\n",
        "            \"IoT\",\n",
        "        ]\n",
        "\n",
        "    all_articles = []\n",
        "\n",
        "    for category in categories:\n",
        "\n",
        "        articles = search_rss(\n",
        "            category\n",
        "        )\n",
        "\n",
        "        all_articles.extend(\n",
        "            articles\n",
        "        )\n",
        "\n",
        "    all_articles = filter_recent(\n",
        "        all_articles,\n",
        "        hours=hours,\n",
        "    )\n",
        "\n",
        "    if keywords:\n",
        "\n",
        "        all_articles = filter_keywords(\n",
        "            all_articles,\n",
        "            keywords,\n",
        "        )\n",
        "\n",
        "    all_articles = remove_duplicates(\n",
        "        all_articles\n",
        "    )\n",
        "\n",
        "    all_articles = sort_articles(\n",
        "        all_articles\n",
        "    )\n",
        "\n",
        "    return all_articles[\n",
        "        :max(1, limit)\n",
        "    ]\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ARTICLE DOMAIN\n",
        "# =========================================================\n",
        "\n",
        "def get_domain(\n",
        "    url: str,\n",
        ") -> str:\n",
        "    \"\"\"\n",
        "    Return hostname from article URL.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        return urlparse(\n",
        "            url\n",
        "        ).netloc\n",
        "\n",
        "    except Exception:\n",
        "\n",
        "        return \"\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMPACT NEWS DATA\n",
        "# =========================================================\n",
        "\n",
        "def compact_articles(\n",
        "    articles: list[dict[str, Any]],\n",
        ") -> list[dict[str, Any]]:\n",
        "    \"\"\"\n",
        "    Remove unnecessary data before sending\n",
        "    articles to Gemini.\n",
        "    \"\"\"\n",
        "\n",
        "    results = []\n",
        "\n",
        "    for article in articles:\n",
        "\n",
        "        results.append(\n",
        "            {\n",
        "                \"title\": article.get(\n",
        "                    \"title\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"url\": article.get(\n",
        "                    \"url\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"description\": article.get(\n",
        "                    \"description\",\n",
        "                    \"\",\n",
        "                )[:1200],\n",
        "\n",
        "                \"source\": article.get(\n",
        "                    \"source\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"category\": article.get(\n",
        "                    \"category\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"published\": article.get(\n",
        "                    \"published\",\n",
        "                    \"\",\n",
        "                ),\n",
        "\n",
        "                \"domain\": get_domain(\n",
        "                    article.get(\n",
        "                        \"url\",\n",
        "                        \"\",\n",
        "                    )\n",
        "                ),\n",
        "            }\n",
        "        )\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# HEALTH CHECK\n",
        "# =========================================================\n",
        "\n",
        "def test_connection() -> bool:\n",
        "    \"\"\"\n",
        "    Test internet/news feed access.\n",
        "    \"\"\"\n",
        "\n",
        "    try:\n",
        "\n",
        "        articles = search_news(\n",
        "            categories=[\"AI\"],\n",
        "            hours=72,\n",
        "            limit=1,\n",
        "        )\n",
        "\n",
        "        return isinstance(\n",
        "            articles,\n",
        "            list,\n",
        "        )\n",
        "\n",
        "    except Exception as exc:\n",
        "\n",
        "        logger.error(\n",
        "            \"News search test failed: %s\",\n",
        "            exc,\n",
        "        )\n",
        "\n",
        "        return False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# COMMAND LINE TEST\n",
        "# =========================================================\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    logging.basicConfig(\n",
        "        level=logging.INFO,\n",
        "        format=(\n",
        "            \"%(asctime)s | \"\n",
        "            \"%(levelname)s | \"\n",
        "            \"%(message)s\"\n",
        "        ),\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 70)\n",
        "    print(\"AI / ROBOTICS NEWS SEARCH\")\n",
        "    print(\"=\" * 70)\n",
        "\n",
        "    articles = search_news(\n",
        "        categories=[\n",
        "            \"AI\",\n",
        "            \"Robotics\",\n",
        "            \"Electronics\",\n",
        "            \"IoT\",\n",
        "        ],\n",
        "        hours=72,\n",
        "        limit=10,\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print(\n",
        "        f\"Found {len(articles)} articles.\"\n",
        "    )\n",
        "\n",
        "    print()\n",
        "\n",
        "    for index, article in enumerate(\n",
        "        articles,\n",
        "        start=1,\n",
        "    ):\n",
        "\n",
        "        print(\n",
        "            f\"{index}. \"\n",
        "            f\"{article['title']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"   Source: \"\n",
        "            f\"{article['source']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"   Category: \"\n",
        "            f\"{article['category']}\"\n",
        "        )\n",
        "\n",
        "        print(\n",
        "            f\"   URL: \"\n",
        "            f\"{article['url']}\"\n",
        "        )\n",
        "\n",
        "        print()"
      ],
      "metadata": {
        "id": "SR56CdETxMHX"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}